### ISSUE TITLE
Unwise use of setattr prevents saving a cube to file

### ISSUE THREAD

**Issue by stephenpascoe** [SciTools/iris#1167]
Iris NetCDF saving uses setattr to copy attributes to the NetCDF4-python object.  This causes problems if your source cube has an attribute which clash with  NetCDF4-python method names.  E.g. the ECHAM5 Aerocom simulations have contain the "dimensions" variable attribute which prevents saving a cube derived from this data.

```
# Executed from /group_workspaces/jasmin/cis/AeroCom/A2/MPIHAM_V2_KZ.A2.CTRL/download on JASMIN

import iris
cube = iris.load_cube('aerocom.MPIHAM_V2_KZ.AEROCOM_A2.CTRL.monthly.loadbc.2007.nc')
iris.save(cube, '/tmp/tmp.nc')
```

Causes the following stack trace in Iris 1.6.1:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/iris/io/__init__.py", line 341, in save
    saver(source, target, **kwargs)
  File "/usr/lib/python2.7/site-packages/iris/fileformats/netcdf.py", line 1568, in save
    least_significant_digit)
  File "/usr/lib/python2.7/site-packages/iris/fileformats/netcdf.py", line 671, in write
    self.update_global_attributes(global_attributes)
  File "/usr/lib/python2.7/site-packages/iris/fileformats/netcdf.py", line 695, in update_global_attributes
    setattr(self._dataset, attr_name, attributes[attr_name])
  File "netCDF4.pyx", line 1832, in netCDF4.Dataset.__setattr__ (netCDF4.c:23365)
AttributeError: 'dimensions' is one of the reserved attributes ('_grpid', '_grp', '_varid', 'groups', 'dimensions', 'variables', 'dtype', 'file_format', '_nunlimdim', 'path', 'parent', 'ndim', 'maskandscale', 'cmptypes', 'vltypes', '_isprimitive', '_isvlen', '_iscompound', '_cmptype', '_vltype'), cannot rebind. Use setncattr instead.
```
I am working with Iris 1.6.1 but I have confirmed the code still uses setattr.

The setncattr() method of NetCDF4-python has been provided to avoid this name clash.

**Comment by ajdawson** [comment]
Closed by #1326.
