### ISSUE TITLE
Difficulty loading RAP grib data

### ISSUE THREAD

**Issue by WeatherGod** [SciTools/iris#1345]
I am trying to use iris for loading up some RAP model data which is in grib2 format. This type of data can be found here: http://nomads.ncep.noaa.gov/pub/data/nccf/com/rap/prod/rap.20140924/ (Note, there is a two-day rolling window, so adjust the URL accordingly). I am using iris 1.7 from binstar.

This product file has lots of different model parameters in it which seems to be causing difficulty.
First, just doing a naive load fails (note the warning hidden in there might be relevant).

```
>>> import iris
>>> cube = iris.load_cube('/nas/data_cellar/NCEP/RAP/2014/20140924/rap.t01z.awp130pgrbf00.grib2')
/home/broot/scratch/miniconda/lib/python2.7/site-packages/iris/fileformats/grib/load_rules.py:335: UserWarning: Different vertical bound types not yet handled.
  warnings.warn("Different vertical bound types not yet handled.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/broot/scratch/miniconda/lib/python2.7/site-packages/iris/__init__.py", line 314, in load_cube
    raise iris.exceptions.ConstraintMismatchError(str(e))
iris.exceptions.ConstraintMismatchError: failed to merge into a single cube.
  cube.shape differs: (337, 451) != (4, 337, 451)
```

So, I try to load up just air temperatures:

```
>>> cube = iris.load_cube('/nas/data_cellar/NCEP/RAP/2014/20140924/rap.t01z.awp130pgrbf00.grib2', 'air_temperature')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/broot/scratch/miniconda/lib/python2.7/site-packages/iris/__init__.py", line 314, in load_cube
    raise iris.exceptions.ConstraintMismatchError(str(e))
iris.exceptions.ConstraintMismatchError: failed to merge into a single cube.
  cube.shape differs: (37, 337, 451) != (2, 337, 451)
```

I am very new to iris and I might be doing something stupid, but I have read the user guide and I have a general sense of how things should be working. If I can get this working right, it would go a long way to convincing my bosses to put some effort into this project.

**Comment by pelson** [comment]
Closing due to inactivity. We've since moved all grib loading functionality into a dedicated "iris-grib" module - with this model, we can technically iterate within an iris-core release cycle, and should allow us to move more quickly if there are translation improvements we can add.
