### ISSUE TITLE
Biggus v0.9.0 breaks sigma_over_z

### ISSUE THREAD

**Issue by ocefpaf** [SciTools/iris#1593]
All other Ocean Dimensionless Coordinates are OK.  Only sigma_over_z is broken when using the latest biggus.  I think that @pelson already expected this, but I am reporting anyways :grinning:

```python
>>> url = "http://geoport.whoi.edu/thredds/dodsC/usgs/data2/rsignell/models/ncom/ncom_sigma_over_z.nc"
>>> cube = iris.load_cube(url, 'sea_water_potential_temperature')
>>> coord = cube.coord('sea_surface_height_above_reference_ellipsoid')
>>> coord
<repr(<iris.coords.AuxCoord at 0x7f487f153250>) failed: IndexError: index slice(None, None, None) is out of bounds for axis 0 with size 1>
```

Full notebook:

http://nbviewer.ipython.org/gist/ocefpaf/1b7cf19e1e6c783d9edc#ocean_sigma_coordinate

**Comment by pelson** [comment]
>  I think that @pelson already expected this, but I am reporting anyways :grinning:

I'm not sure I did. :sob:

I've just tried to reproduce this with biggus 0.9 and iris master:

```
import iris

url = 'http://tds.marine.rutgers.edu/thredds/dodsC/roms/espresso/2013_da/avg_Best/ESPRESSO_Real-Time_v2_Averages_Best_Available_best.ncd'
cube = iris.load_cube(url, 'sea_water_salinity')

>>> print cube

sea_water_salinity                                    (time: 677; S-coordinate at RHO-points: 36; -- : 82; -- : 130)
     Dimension coordinates:
          time                                             x                                -        -        -
          S-coordinate at RHO-points                       -                                x        -        -
     Auxiliary coordinates:
          forecast_reference_time                          x                                -        -        -
          sea_surface_height                               x                                -        x        x
          S-coordinate stretching curves at RHO-points     -                                x        -        -
          latitude                                         -                                -        x        x
          longitude                                        -                                -        x        x
          sea_floor_depth                                  -                                -        x        x
     Derived coordinates:
          sea_surface_height_above_reference_ellipsoid     x                                x        x        x
     Scalar coordinates:
          S-coordinate parameter, critical depth: 5.0 meter
     Attributes:
          CPP_options: MyCPP, ADD_FSOBC, ADD_M2OBC, ANA_BSFLUX, ANA_BTFLUX, ASSUMED_SHAPE, AVERAGES,...
          Conventions: CF-1.4, _Coordinates
          DODS_EXTRA.Unlimited_Dimension: ocean_time
          _ChunkSize: [  1  36  82 130]
          _CoordSysBuilder: ucar.nc2.dataset.conv.CF1Convention
          ana_file: ROMS/Functionals/ana_btflux.h, /home/julia/ROMS/espresso/RealTime/Comp...
          avg_base: espresso_avg_3365
          bry_file: ../Data/espresso_bdry_new.nc
          cdm_data_type: GRID
          clm_file: ../Data/espresso_clm_new.nc
          code_dir: /home/julia/ROMS/espresso/svn1409
          compiler_command: /opt/pgisoft/openmpi/bin/mpif90
          compiler_flags:  -O3 -Mfree
          compiler_system: pgi
          cpu: x86_64
          featureType: GRID
          field: salinity, scalar, series
          file: espresso_avg_3365_0004.nc
          flt_file: espresso_flt_3365.nc
          format: netCDF-4/HDF5 file
          fpos_file: /home/om/roms/espresso/Data/espresso_floats_glider.in
          frc_file_01: /home/om/roms/espresso/Data/espresso_tide_c05_20060101.nc
          frc_file_02: ../Data/espresso_river_20030101_now.nc
          frc_file_03: ../Data/rain_ncepnam_3hourly_MAB_and_GoM.nc
          frc_file_04: ../Data/swrad_ncepnam_3hourly_MAB_and_GoM.nc
          frc_file_05: ../Data/Tair_ncepnam_3hourly_MAB_and_GoM.nc
          frc_file_06: ../Data/Pair_ncepnam_3hourly_MAB_and_GoM.nc
          frc_file_07: ../Data/Qair_ncepnam_3hourly_MAB_and_GoM.nc
          frc_file_08: ../Data/lwrad_down_ncepnam_3hourly_MAB_and_GoM.nc
          frc_file_09: ../Data/Uwind_ncepnam_3hourly_MAB_and_GoM.nc
          frc_file_10: ../Data/Vwind_ncepnam_3hourly_MAB_and_GoM.nc
          grd_file: /home/om/roms/espresso/Data/espresso_grid_c05.nc
          header_dir: /home/julia/ROMS/espresso/RealTime/Compile/fwd
          header_file: espresso.h
          his_base: espresso_his_3365
          history: ROMS/TOMS, Version 3.5, Monday - March 23, 2015 -  4:39:26 PM ;
FMRC Best...
          ini_file: /home/julia/ROMS/espresso/RealTime/Storage/run04/espresso_ini_3365.nc
          location: Proto fmrc:espresso_2013_da_avg_best
          os: Linux
          rst_file: espresso_rst_3365.nc
          script_file: nl_ocean_espresso.in
          summary: Operational nowcast/forecast system version 2 for MARACOOS project (http://maracoos.org)....
          svn_rev: exported
          svn_url: https://www.myroms.org/svn/src/trunk
          tiling: 004x002
          time: ocean_time
          title: ROMS ESPRESSO Real-Time Operational IS4DVAR Forecast System Version 2 (NEW)...
          type: ROMS/TOMS nonlinear model averages file
```

```
>>> print cube.coord('sea_surface_height_above_reference_ellipsoid')
AuxCoord(array([[[[ -2.31439161e+03,  -2.49218561e+03,  -2.62913416e+03, ...,
           -2.75119035e+03,  -2.72837789e+03,  -2.70907694e+03],
         [ -1.74258923e+03,  -1.99725405e+03,  -2.23106442e+03, ...,
           -2.66584419e+03,  -2.63354784e+03,  -2.62208495e+03],
         [ -1.15735103e+03,  -1.42040045e+03,  -1.63303314e+03, ...,
           -2.59221909e+03,  -2.56038152e+03,  -2.53009670e+03],
         ..., 
         [             nan,              nan,              nan, ...,
                       nan,              nan,              nan],
         [             nan,              nan,              nan, ...,
                       nan,              nan,              nan],
         [             nan,              nan,              nan, ...,
                       nan,              nan,              nan]],


...
        [[ -2.13715385e+03,  -2.30131130e+03,  -2.42775834e+03, ...,
           -2.54047289e+03,  -2.51941132e+03,  -2.50159072e+03],
         [ -1.60920789e+03,  -1.84434032e+03,  -2.06022000e+03, ...,
           -2.46167265e+03,  -2.43185459e+03,  -2.42127090e+03],
         [ -1.06886008e+03,  -1.31173405e+03,  -1.50805998e+03, ...,
           -2.39369852e+03,  -2.36430405e+03,  -2.33634204e+03],
         ..., 
         [             nan,              nan,              nan, ...,
                       nan,              nan,              nan],
         [             nan,              nan,              nan, ...,
                       nan,              nan,              nan],
         [             nan,              nan,              nan, ...,
                       nan,              nan,              nan]],
...
        [[ -2.43176639e+00,  -2.61037143e+00,  -2.78537482e+00, ...,
           -3.40448728e+00,  -3.39674610e+00,  -3.37737962e+00],
         [ -1.85758354e+00,  -2.11421429e+00,  -2.38627238e+00, ...,
           -3.31871346e+00,  -3.30146086e+00,  -3.29005211e+00],
         [ -1.36061507e+00,  -1.62586962e+00,  -1.86839102e+00, ...,
           -3.28266050e+00,  -3.26395927e+00,  -3.23364036e+00],
         ..., 
         [             nan,              nan,              nan, ...,
                       nan,              nan,              nan],
         [             nan,              nan,              nan, ...,
                       nan,              nan,              nan],
         [             nan,              nan,              nan, ...,
                       nan,              nan,              nan]]]]), standard_name='sea_surface_height_above_reference_ellipsoid', units=Unit('meter'), attributes={'positive': 'up'})
```

Am I missing a step here?

**Comment by ocefpaf** [comment]
> Am I missing a step here?

Yes, ESPRESSO is `ocean_s_coordinate_g1` and that one is fine.  The issue happens only with `sigma_over_z` right [here](https://github.com/SciTools/iris/pull/1105/files#diff-42d68d7f5fd99ece9d3d591cd777d86cR857).

Use the NCOM  URL above.  NCOM is a `sigma_over_z`.  Or just go for [this](http://nbviewer.ipython.org/gist/ocefpaf/d297c7f422c549dd3b31) notebook.

PS: `sigma_over_z` is an obscure ODVC and there is no hurry to fix this.  I only reported this because I thought that kind of slicing bug might surface elsewhere too.

**Comment by pelson** [comment]
With biggus v0.10.0 and iris master:

```
>>> import iris
>>> url = 'http://geoport.whoi.edu/thredds/dodsC/usgs/data2/rsignell/models/ncom/ncom_sigma_over_z.nc'
>>> cube = iris.load_cube(url, 'sea_water_potential_temperature')
>>> print cube
sea_water_potential_temperature                  (time: 1; -- : 40; -- : 1280; -- : 2048)
     Dimension coordinates:
          time                                             x       -        -          -
     Auxiliary coordinates:
          sea_surface_height                               x       -        x          x
          siglay                                           -       x        -          -
          zlay                                             -       x        -          -
          depth                                            -       -        x          x
          latitude                                         -       -        x          x
          longitude                                        -       -        x          x
     Derived coordinates:
          sea_surface_height_above_reference_ellipsoid     x       x        x          x
     Scalar coordinates:
          depth_c: 137.869 m
          nsiglay: 19
     Attributes:
          Conventions: CF-1.6
```

```
>>> print cube.coord('sea_surface_height_above_reference_ellipsoid')
AuxCoord(array([[[[    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         ..., 
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ]],

        [[    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         ..., 
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ]],

        [[    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         ..., 
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ],
         [    0.        ,     0.        ,     0.        , ...,
              0.        ,     0.        ,     0.        ]],

        ..., 
        [[-3573.40039062, -3573.40039062, -3573.40039062, ...,
          -3573.40039062, -3573.40039062, -3573.40039062],
         [-3573.40039062, -3573.40039062, -3573.40039062, ...,
          -3573.40039062, -3573.40039062, -3573.40039062],
         [-3573.40039062, -3573.40039062, -3573.40039062, ...,
          -3573.40039062, -3573.40039062, -3573.40039062],
         ..., 
         [-3573.40039062, -3573.40039062, -3573.40039062, ...,
          -3573.40039062, -3573.40039062, -3573.40039062],
         [-3573.40039062, -3573.40039062, -3573.40039062, ...,
          -3573.40039062, -3573.40039062, -3573.40039062],
         [-3573.40039062, -3573.40039062, -3573.40039062, ...,
          -3573.40039062, -3573.40039062, -3573.40039062]],

        [[-4252.66503906, -4252.66503906, -4252.66503906, ...,
          -4252.66503906, -4252.66503906, -4252.66503906],
         [-4252.66503906, -4252.66503906, -4252.66503906, ...,
          -4252.66503906, -4252.66503906, -4252.66503906],
         [-4252.66503906, -4252.66503906, -4252.66503906, ...,
          -4252.66503906, -4252.66503906, -4252.66503906],
         ..., 
         [-4252.66503906, -4252.66503906, -4252.66503906, ...,
          -4252.66503906, -4252.66503906, -4252.66503906],
         [-4252.66503906, -4252.66503906, -4252.66503906, ...,
          -4252.66503906, -4252.66503906, -4252.66503906],
         [-4252.66503906, -4252.66503906, -4252.66503906, ...,
          -4252.66503906, -4252.66503906, -4252.66503906]],

        [[-5060.86816406, -5060.86816406, -5060.86816406, ...,
          -5060.86816406, -5060.86816406, -5060.86816406],
         [-5060.86816406, -5060.86816406, -5060.86816406, ...,
          -5060.86816406, -5060.86816406, -5060.86816406],
         [-5060.86816406, -5060.86816406, -5060.86816406, ...,
          -5060.86816406, -5060.86816406, -5060.86816406],
         ..., 
         [-5060.86816406, -5060.86816406, -5060.86816406, ...,
          -5060.86816406, -5060.86816406, -5060.86816406],
         [-5060.86816406, -5060.86816406, -5060.86816406, ...,
          -5060.86816406, -5060.86816406, -5060.86816406],
         [-5060.86816406, -5060.86816406, -5060.86816406, ...,
          -5060.86816406, -5060.86816406, -5060.86816406]]]], dtype=float32), standard_name='sea_surface_height_above_reference_ellipsoid', units=Unit('m'), attributes={'positive': 'up'})

```

**Comment by ocefpaf** [comment]
After some conda cache cleanups I can confirm that things work OK with latest master.

http://nbviewer.ipython.org/gist/ocefpaf/c8e59b74c9d0c2f3eb1f

However, this problem exists in https://github.com/SciTools/iris/pull/1560. (And I guess due to my messy vens it was there all  the time and not on master :flushed:)

**Comment by pelson** [comment]
P.S. I think I'm still missing something. FWIW, in this case, I don't think the notebook is helping - I just want to reproduce the traceback so that I can see where the problem lies.

**Comment by ocefpaf** [comment]
Here is the full traceback (This happens only in #1560, `master` is fine.):

```python
>>> import iris
>>> url = "http://geoport.whoi.edu/thredds/dodsC/usgs/data2/rsignell/models/ncom/ncom_sigma_over_z.nc"
>>> cube = iris.load_cube(url, 'sea_water_potential_temperature')
>>> coord = cube.coord('sea_surface_height_above_reference_ellipsoid')
>>> print(coord)
IndexError                                Traceback (most recent call last)
<ipython-input-2-b02647f46158> in <module>()
      3 cube = iris.load_cube(url, 'sea_water_potential_temperature')
      4 coord = cube.coord('sea_surface_height_above_reference_ellipsoid')
----> 5 print(coord)

/home/filipe/miniconda/envs/SECOORA/lib/python2.7/site-packages/Iris-1.8.0.dev0-py2.7.egg/iris/coords.py in __str__(self)
    558                                 other_metadata=self._repr_other_metadata())
    559         else:
--> 560             result = repr(self)
    561         return result
    562 

/home/filipe/miniconda/envs/SECOORA/lib/python2.7/site-packages/Iris-1.8.0.dev0-py2.7.egg/iris/coords.py in __repr__(self)
    570         result = fmt.format(self=self, cls=type(self).__name__,
    571                             bounds=bounds,
--> 572                             other_metadata=self._repr_other_metadata())
    573         return result
    574 

/home/filipe/miniconda/envs/SECOORA/lib/python2.7/site-packages/Iris-1.8.0.dev0-py2.7.egg/iris/coords.py in points(self)
   1508             points = points.ndarray()
   1509             self._points = points
-> 1510         return points.view()
   1511 
   1512     @points.setter

/home/filipe/miniconda/envs/SECOORA/lib/python2.7/site-packages/Iris-1.8.0.dev0-py2.7.egg/iris/aux_factory.py in view(self, *args, **kwargs)
    101 
    102         """
--> 103         return self._cached_array().view(*args, **kwargs)
    104 
    105 

/home/filipe/miniconda/envs/SECOORA/lib/python2.7/site-packages/Iris-1.8.0.dev0-py2.7.egg/iris/aux_factory.py in _cached_array(self)
     73     def _cached_array(self):
     74         if self._array is None:
---> 75             self._array = self._func()
     76             del self._func
     77         return self._array

/home/filipe/miniconda/envs/SECOORA/lib/python2.7/site-packages/Iris-1.8.0.dev0-py2.7.egg/iris/aux_factory.py in calc_points()
    928                                 nd_points_by_key['zlev'],
    929                                 points_shape,
--> 930                                 nsigma_slice)
    931 
    932         points = LazyArray(points_shape, calc_points, points_dtype)

/home/filipe/miniconda/envs/SECOORA/lib/python2.7/site-packages/Iris-1.8.0.dev0-py2.7.egg/iris/aux_factory.py in _derive(self, sigma, eta, depth, depth_c, nsigma, zlev, shape, nsigma_slice)
    880         # Perform the ocean sigma over z coordinate nsigma slice.
    881         if eta.ndim:
--> 882             eta = eta[nsigma_slice]
    883         if sigma.ndim:
    884             sigma = sigma[nsigma_slice]

/home/filipe/miniconda/envs/SECOORA/lib/python2.7/site-packages/Biggus-0.10.0-py2.7.egg/biggus/__init__.pyc in __getitem__(self, keys)
    791         for axis in sorted(axes_to_combine, reverse=True):
    792             new_axes[axis] += new_axes.pop(axis + 1)
--> 793         new_array = NewAxesArray(self.array[tuple(contained_array_keys)],
    794                                  new_axes)
    795         if broadcast_dict:

/home/filipe/miniconda/envs/SECOORA/lib/python2.7/site-packages/Biggus-0.10.0-py2.7.egg/biggus/__init__.pyc in __getitem__(self, keys)
    532             indexed_array = array[keys]
    533         else:
--> 534             indexed_array = self._getitem_full_keys(keys)
    535         return indexed_array
    536 

/home/filipe/miniconda/envs/SECOORA/lib/python2.7/site-packages/Biggus-0.10.0-py2.7.egg/biggus/__init__.pyc in _getitem_full_keys(self, keys)
   1289                 indices = tuple(range(start, stop, stride))
   1290                 new_key = new_keys.pop(0)
-> 1291                 result_key = self._remap_new_key(indices, new_key, axis)
   1292             else:
   1293                 new_key = new_keys.pop(0)

/home/filipe/miniconda/envs/SECOORA/lib/python2.7/site-packages/Biggus-0.10.0-py2.7.egg/biggus/__init__.pyc in _remap_new_key(self, indices, new_key, axis)
   1260                     msg = 'index {0} is out of bounds for axis {1}' \
   1261                           ' with size {2}'.format(sub_key, axis, size)
-> 1262                     raise IndexError(msg)
   1263             result_key = tuple(indices[key] for key in new_key)
   1264         else:

IndexError: index slice(None, None, None) is out of bounds for axis 0 with size 1
```

**Comment by ocefpaf** [comment]
@pelson now that #1560 has landed on master you can probably reproduce it using the lines above.

**Comment by rhattersley** [comment]
FWIW, I can reproduce using Iris master & biggus v0.10.0.

**Comment by rhattersley** [comment]
When Iris executes the line `eta = eta[nsigma_slice]`, `nsigma_slice` is a *list*, not a tuple. This is the root cause.

**Comment by rhattersley** [comment]
```python
>>> a = biggus.NumpyArrayAdapter(np.arange(10))
>>> a[[0, 3, 4]].ndarray()
array([0, 3, 4])
>>> a[[0, slice(None), 4]].ndarray()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/richard/miniconda/lib/python2.7/site-packages/biggus/__init__.py", line 535, in __getitem__
    indexed_array = self._getitem_full_keys(keys)
  File "/home/richard/miniconda/lib/python2.7/site-packages/biggus/__init__.py", line 1314, in _getitem_full_keys
    result_key = self._cleanup_new_key(new_key, size, axis)
  File "/home/richard/miniconda/lib/python2.7/site-packages/biggus/__init__.py", line 1225, in _cleanup_new_key
    raise IndexError(msg)
IndexError: index slice(None, None, None) is out of bounds for axis 0 with size 10
```

**Comment by rhattersley** [comment]
When I try @ocefpaf's example with biggus 0.8.0 I get `IndexError: too many keys`, so it isn't the biggus change that's to blame.

**Comment by rhattersley** [comment]
Interestingly, with numpy:
```python
>>> a = np.zeros((1, 1280, 2048))
>>> a[[0, 3, 4]].shape
(3, 1280, 2048)
>>> a[[0, slice(None), 4]].shape
(1280,)
```
So numpy has some heuristic for deciding whether a list triggers fancy indexing or is "unpacked" and effectively ignored.... Oh, for a "vomit" emoji. :expressionless:

**Comment by ocefpaf** [comment]
> When I try @ocefpaf's example with biggus 0.8.0 I get IndexError: too many keys

Sorry for misleading you  :flushed: !  I guess it was a while since I ran that notebook.

**Comment by QuLogic** [comment]
> So numpy has some heuristic for deciding whether a list triggers fancy indexing or is "unpacked" and effectively ignored.... Oh, for a "vomit" emoji. :expressionless:

I think what you're seeing here is [noted in the advanced indexing information](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#advanced-indexing).

**Comment by rhattersley** [comment]
> I think what you're seeing here is noted in the advanced indexing information.

It's noted, but not what I'd call explained! It says, "`x[[1,2,slice(None)]]` will trigger basic slicing" despite having previously stated that advanced indexing is triggered "when the selection object, *obj*, is a non-tuple sequence object, ..."! Last time I checked, `[1, 2, slice(None]` was not a tuple. :wink:

**Comment by QuLogic** [comment]
Yes, I was not able to understand the warning from the text above it, but I _think_ it might be explained by the second subsection further below. But I really haven't had to try and understand that subsection before.
