### ISSUE TITLE
Cannot install on RHEL 6.5 with Conda 

### ISSUE THREAD

**Issue by jacobtomlinson** [SciTools/iris#1651]
I've just tried to install Iris on a fresh RHEL 6.5 box and I'm unable to use it.

```
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.5 (Santiago)
```

To install it I've first installed Conda using their [documentation](http://conda.pydata.org/docs/installation.html).

```
wget http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O ~/miniconda.sh
bash ~/miniconda.sh -b -p $HOME/miniconda
export PATH="$HOME/miniconda/bin:$PATH"
```

I've then run the install command from the Iris [documentation](http://scitools.org.uk/iris/docs/latest/installing.html).

```
conda install -c scitools iris python=2.7
```

I specified python 2.7 as RHEL 6.5 comes with 3.4 as the default.

When running `import iris` within python 2.7 I get the following error message.

```
$ python
Python 2.7.9 |Continuum Analytics, Inc.| (default, Mar  9 2015, 16:20:48)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import iris
WARNING:shapely.libgeos:cannot open shared object from 'geos-config --clibs': '-L/home/ec2-user/miniconda/lib -lgeos_c'
WARNING:shapely.libgeos:there were 2 guess(es) for this path:
	/home/ec2-user/miniconda/lib/libgeos_c.so
	/home/ec2-user/miniconda/lib/libgeos_c.so.1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/iris/__init__.py", line 104, in <module>
    import iris.cube
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/iris/cube.py", line 36, in <module>
    import iris.analysis
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/iris/analysis/__init__.py", line 57, in <module>
    from iris.analysis._interpolator import (_LINEAR_EXTRAPOLATION_MODES,
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/iris/analysis/_interpolator.py", line 25, in <module>
    from iris.analysis.cartography import wrap_lons as wrap_circular_points
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/iris/analysis/cartography.py", line 29, in <module>
    import cartopy.img_transform
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/cartopy/__init__.py", line 24, in <module>
    import shapely.speedups
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/shapely/speedups/__init__.py", line 3, in <module>
    from shapely.geometry import linestring, polygon
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/shapely/geometry/base.py", line 9, in <module>
    from shapely.coords import CoordinateSequence
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/shapely/geos.py", line 15, in <module>
    from .libgeos import lgeos as _lgeos, geos_version
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/shapely/libgeos.py", line 148, in <module>
    fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
  File "/home/ec2-user/miniconda/lib/python2.7/site-packages/shapely/libgeos.py", line 143, in load_dll
    libname, fallbacks))
OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
```

I have also tried installing `geos` from the PostgreSQL repository but it made no difference.

@pelson @niallrobinson @simonstanley

**Comment by ocefpaf** [comment]
Hi @jacobtomlinson 

Can you try the IOOS RHEL6 channel?

`conda install -c ioos-rhel6 iris python=2.7`

Please let me know if that works for you.

**Comment by jacobtomlinson** [comment]
Perfect thank you very much!

Is this mentioned in the documentation anywhere?

**Comment by ocefpaf** [comment]
The default SciTools channel (as well as the default [IOOS](https://binstar.org/ioos) channel) are built using a modern Linux distribution.  Modern Linuxes libc are incompatible with RHEL (and Centos) libc.  The [IOOS-RHEL6](https://binstar.org/ioos-rhel6) tries to solve that deficiency by re-building the channel using a RHEL6 machine.

In the near future I believe that we all (IOOS and SciTools) will be using a RHEL compatible solution and this confusion will go away.

**Comment by jacobtomlinson** [comment]
Great thanks for the explanation. Happy for the issue to be closed.

**Comment by pelson** [comment]
We automated the build using an old CentOS build, so this should now be fixed (and as ever, the ioos channel provided a nice safety net).
