### ISSUE TITLE
BUG: NETCDF4_CLASSIC

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#1689]
Inability to save to NETCDF4_CLASSIC.

```Python
import iris
cube = iris.cube.Cube([1])
iris.save(cube, 'tmp.nc', netcdf_format='NETCDF4_CLASSIC')
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/h05/cpelley/git/iris/lib/iris/io/__init__.py", line 350, in save
    saver(source, target, **kwargs)
  File "/home/h05/cpelley/git/iris/lib/iris/fileformats/netcdf.py", line 1758, in save
    least_significant_digit)
  File "/home/h05/cpelley/git/iris/lib/iris/fileformats/netcdf.py", line 763, in write
    least_significant_digit=least_significant_digit)
  File "/home/h05/cpelley/git/iris/lib/iris/fileformats/netcdf.py", line 1502, in _create_cf_data_variable
    fill_value=fill_value, **kwargs)
  File "netCDF4.pyx", line 1676, in netCDF4.Dataset.createVariable (netCDF4.c:19077)
  File "netCDF4.pyx", line 2203, in netCDF4.Variable.__init__ (netCDF4.c:24529)
RuntimeError: NetCDF: Attempting netcdf-4 operation on strict nc3 netcdf-4 file
```

Any hints on how to debug this would be great.  Looks like this never actually worked.  Since I doubt this would have been unnoticed, I think there may be a bug with the version of the underlying netCDF library??

**Comment by cpelley** [comment]
Argh, it was because my data was 64bit.  The netCDF library does NOT give a suitable error whatsoever!
