### ISSUE TITLE
Test failures with newer netcdf

### ISSUE THREAD

**Issue by QuLogic** [SciTools/iris#1786]
After updating `netcdf4` via:

```
    curl:      7.38.0-0         --> 7.43.0-1        
    hdf5:      1.8.14-0         --> 1.8.15.1-1      
    libnetcdf: 4.3.2-1          --> 4.3.3.1-1       
    netcdf4:   1.1.1-np19py27_1 --> 1.1.9-np19py27_0
```

there are several new test failures:

``` python
======================================================================
ERROR: test_deferred_loading (iris.tests.test_netcdf.TestNetCDFLoad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../iris/tests/test_netcdf.py", line 209, in test_deferred_loading
    ('netcdf', 'netcdf_deferred_tuple_0.cml'))
  File ".../iris/tests/__init__.py", line 351, in assertCML
    byteorder=False)
  File ".../iris/cube.py", line 251, in xml
    doc, checksum=checksum, order=order, byteorder=byteorder))
  File ".../iris/cube.py", line 2583, in _xml_element
    data = self.data
  File ".../iris/cube.py", line 1505, in data
    data = data.masked_array()
  File ".../biggus/__init__.py", line 1392, in masked_array
    array = self._apply_keys()
  File ".../biggus/__init__.py", line 1478, in _apply_keys
    array = self.concrete.__getitem__(self._keys)
  File ".../iris/fileformats/netcdf.py", line 274, in __getitem__
    data = variable[keys]
  File "netCDF4/_netCDF4.pyx", line 3318, in netCDF4._netCDF4.Variable.__getitem__ (netCDF4/_netCDF4.c:30994)
  File ".../netCDF4/utils.py", line 222, in _StartCountStride
    raise IndexError(msg)
IndexError: integer sequences in slices must be sorted and cannot have duplicates

======================================================================
FAIL: test_save (iris.tests.integration.test_netcdf.TestHybridPressure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../iris/tests/integration/test_netcdf.py", line 57, in test_save
    self.assertCDL(filename)
  File ".../iris/tests/__init__.py", line 316, in assertCDL
    self._check_same(cdl, reference_path, type_comparison_name='CDL')
  File ".../iris/tests/__init__.py", line 442, in _check_same
    type_comparison_name)
  File ".../iris/tests/__init__.py", line 203, in _assert_str_same
    self.fail("%s do not match: %s\n%s" % (type_comparison_name, reference_filename, diff))
AssertionError: CDL do not match: .../iris/tests/results/integration/netcdf/TestHybridPressure/save.cdl
--- Reference
+++ Test result
@@ -12 +12 @@
-       air_potential_temperature:coordinates = "forecast_period level_pressure sigma surface_air_pressure" ;
+       string air_potential_temperature:coordinates = "forecast_period level_pressure sigma surface_air_pressure" ;
@@ -46 +46 @@
-       level_pressure:bounds = "level_pressure_bnds" ;
+       string level_pressure:bounds = "level_pressure_bnds" ;
@@ -48 +48 @@
-       level_pressure:long_name = "level_pressure" ;
+       string level_pressure:long_name = "level_pressure" ;


======================================================================
FAIL: test_with_bounds (iris.tests.unit.fileformats.grib.save_rules.test__missing_forecast_period.TestNoForecastReferenceTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../iris/tests/unit/fileformats/grib/save_rules/test__missing_forecast_period.py", line 69, in test_with_bounds
    self.assertEqual(res, expected)
AssertionError: Tuples differ: (datetime.datetime(1970, 1, 1,... != (datetime.datetime(1970, 1, 1,...

First differing element 0:
1970-01-01 14:00:00.000006
1970-01-01 14:00:00

- (datetime.datetime(1970, 1, 1, 14, 0, 0, 6), 3, 0, 1)
?                                       -------------

+ (datetime.datetime(1970, 1, 1, 14, 0), 3, 0, 1)
?                                    +++++++


======================================================================
FAIL: test_no_bounds (iris.tests.unit.fileformats.grib.save_rules.test__missing_forecast_period.TestWithForecastReferenceTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../iris/tests/unit/fileformats/grib/save_rules/test__missing_forecast_period.py", line 90, in test_no_bounds
    self.assertEqual(res, expected)
AssertionError: Tuples differ: (datetime.datetime(1970, 1, 1,... != (datetime.datetime(1970, 1, 1,...

First differing element 0:
1970-01-01 08:00:00.000006
1970-01-01 08:00:00

- (datetime.datetime(1970, 1, 1, 8, 0, 0, 6), 1, 64, 1)
?                                    ------

+ (datetime.datetime(1970, 1, 1, 8, 0), 1, 64, 1)

======================================================================
FAIL: test_with_bounds (iris.tests.unit.fileformats.grib.save_rules.test__missing_forecast_period.TestWithForecastReferenceTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../iris/tests/unit/fileformats/grib/save_rules/test__missing_forecast_period.py", line 109, in test_with_bounds
    self.assertEqual(res, expected)
AssertionError: Tuples differ: (datetime.datetime(1970, 1, 1,... != (datetime.datetime(1970, 1, 1,...

First differing element 0:
1970-01-01 08:00:00.000006
1970-01-01 08:00:00

- (datetime.datetime(1970, 1, 1, 8, 0, 0, 6), 1, 40, 1)
?                                    ------

+ (datetime.datetime(1970, 1, 1, 8, 0), 1, 40, 1)

======================================================================
FAIL: test_0d_str (iris.tests.test_cdm.TestStockCubeStringRepresentations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../iris/tests/test_cdm.py", line 246, in test_0d_str
    self.assertString(str(self.cube[0, 0, 0, 0]))
  File ".../iris/tests/__init__.py", line 431, in assertString
    type_comparison_name='Strings')
  File ".../iris/tests/__init__.py", line 442, in _check_same
    type_comparison_name)
  File ".../iris/tests/__init__.py", line 203, in _assert_str_same
    self.fail("%s do not match: %s\n%s" % (type_comparison_name, reference_filename, diff))
AssertionError: Strings do not match: .../iris/tests/results/cdm/TestStockCubeStringRepresentations/0d_str.txt
--- Reference
+++ Test result
@@ -11 +11 @@
-          time: 2009-09-09 17:10:00
+          time: 2009-09-09 17:10:00.000011


======================================================================
FAIL: test_1d_str (iris.tests.test_cdm.TestStockCubeStringRepresentations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../iris/tests/test_cdm.py", line 240, in test_1d_str
    self.assertString(str(self.cube[0, 0, 0]))
  File ".../iris/tests/__init__.py", line 431, in assertString
    type_comparison_name='Strings')
  File ".../iris/tests/__init__.py", line 442, in _check_same
    type_comparison_name)
  File ".../iris/tests/__init__.py", line 203, in _assert_str_same
    self.fail("%s do not match: %s\n%s" % (type_comparison_name, reference_filename, diff))
AssertionError: Strings do not match: .../iris/tests/results/cdm/TestStockCubeStringRepresentations/1d_str.txt
--- Reference
+++ Test result
@@ -14 +14 @@
-          time: 2009-09-09 17:10:00
+          time: 2009-09-09 17:10:00.000011


======================================================================
FAIL: test_2d_str (iris.tests.test_cdm.TestStockCubeStringRepresentations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../iris/tests/test_cdm.py", line 234, in test_2d_str
    self.assertString(str(self.cube[0, 0]))
  File ".../iris/tests/__init__.py", line 431, in assertString
    type_comparison_name='Strings')
  File ".../iris/tests/__init__.py", line 442, in _check_same
    type_comparison_name)
  File ".../iris/tests/__init__.py", line 203, in _assert_str_same
    self.fail("%s do not match: %s\n%s" % (type_comparison_name, reference_filename, diff))
AssertionError: Strings do not match: .../iris/tests/results/cdm/TestStockCubeStringRepresentations/2d_str.txt
--- Reference
+++ Test result
@@ -14 +14 @@
-          time: 2009-09-09 17:10:00
+          time: 2009-09-09 17:10:00.000011


======================================================================
FAIL: test_3d_str (iris.tests.test_cdm.TestStockCubeStringRepresentations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../iris/tests/test_cdm.py", line 228, in test_3d_str
    self.assertString(str(self.cube[0]))
  File ".../iris/tests/__init__.py", line 431, in assertString
    type_comparison_name='Strings')
  File ".../iris/tests/__init__.py", line 442, in _check_same
    type_comparison_name)
  File ".../iris/tests/__init__.py", line 203, in _assert_str_same
    self.fail("%s do not match: %s\n%s" % (type_comparison_name, reference_filename, diff))
AssertionError: Strings do not match: .../iris/tests/results/cdm/TestStockCubeStringRepresentations/3d_str.txt
--- Reference
+++ Test result
@@ -14 +14 @@
-          time: 2009-09-09 17:10:00
+          time: 2009-09-09 17:10:00.000011


======================================================================
FAIL: test_AuxCoord_str (iris.tests.test_coord_api.TestCoord_ReprStr_time)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../iris/tests/test_coord_api.py", line 274, in test_AuxCoord_str
    ('coord_api', 'str_repr', 'aux_time_str.txt'))
  File ".../iris/tests/__init__.py", line 431, in assertString
    type_comparison_name='Strings')
  File ".../iris/tests/__init__.py", line 442, in _check_same
    type_comparison_name)
  File ".../iris/tests/__init__.py", line 203, in _assert_str_same
    self.fail("%s do not match: %s\n%s" % (type_comparison_name, reference_filename, diff))
AssertionError: Strings do not match: .../iris/tests/results/coord_api/str_repr/aux_time_str.txt
--- Reference
+++ Test result
@@ -1,2 +1,3 @@
-DimCoord([2009-09-09 17:10:00, 2009-09-09 17:20:00, 2009-09-09 17:30:00,
-       2009-09-09 17:40:00, 2009-09-09 17:50:00, 2009-09-09 18:00:00], standard_name='time', calendar='gregorian')+DimCoord([2009-09-09 17:10:00.000011, 2009-09-09 17:20:00,
+       2009-09-09 17:30:00, 2009-09-09 17:40:00, 2009-09-09 17:50:00,
+       2009-09-09 18:00:00], standard_name='time', calendar='gregorian')

======================================================================
FAIL: test_DimCoord_str (iris.tests.test_coord_api.TestCoord_ReprStr_time)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../iris/tests/test_coord_api.py", line 270, in test_DimCoord_str
    ('coord_api', 'str_repr', 'dim_time_str.txt'))
  File ".../iris/tests/__init__.py", line 431, in assertString
    type_comparison_name='Strings')
  File ".../iris/tests/__init__.py", line 442, in _check_same
    type_comparison_name)
  File ".../iris/tests/__init__.py", line 203, in _assert_str_same
    self.fail("%s do not match: %s\n%s" % (type_comparison_name, reference_filename, diff))
AssertionError: Strings do not match: .../iris/tests/results/coord_api/str_repr/dim_time_str.txt
--- Reference
+++ Test result
@@ -1,2 +1,3 @@
-DimCoord([2009-09-09 17:10:00, 2009-09-09 17:20:00, 2009-09-09 17:30:00,
-       2009-09-09 17:40:00, 2009-09-09 17:50:00, 2009-09-09 18:00:00], standard_name='time', calendar='gregorian')+DimCoord([2009-09-09 17:10:00.000011, 2009-09-09 17:20:00,
+       2009-09-09 17:30:00, 2009-09-09 17:40:00, 2009-09-09 17:50:00,
+       2009-09-09 18:00:00], standard_name='time', calendar='gregorian')

======================================================================
FAIL: test_time_gregorian (iris.tests.test_pandas.TestAsDataFrame)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../iris/tests/test_pandas.py", line 230, in test_time_gregorian
    self.assertTrue(all(data_frame.columns == timestamps))
AssertionError: False is not true

======================================================================
FAIL: test_time_360 (iris.tests.test_pandas.TestAsSeries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../iris/tests/test_pandas.py", line 112, in test_time_360
    'time_360.txt')))
  File ".../iris/tests/__init__.py", line 431, in assertString
    type_comparison_name='Strings')
  File ".../iris/tests/__init__.py", line 442, in _check_same
    type_comparison_name)
  File ".../iris/tests/__init__.py", line 203, in _assert_str_same
    self.fail("%s do not match: %s\n%s" % (type_comparison_name, reference_filename, diff))
AssertionError: Strings do not match: .../iris/tests/results/pandas/as_series/time_360.txt
--- Reference
+++ Test result
@@ -4,2 +4,2 @@
-2000-11-01 07:12:00    3
-2001-02-11 09:36:00    4
+2000-11-01 07:11:59    3
+2001-02-11 09:35:59    4


======================================================================
FAIL: test_time_gregorian (iris.tests.test_pandas.TestAsSeries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../iris/tests/test_pandas.py", line 98, in test_time_gregorian
    'time_gregorian.txt')))
  File ".../iris/tests/__init__.py", line 431, in assertString
    type_comparison_name='Strings')
  File ".../iris/tests/__init__.py", line 442, in _check_same
    type_comparison_name)
  File ".../iris/tests/__init__.py", line 203, in _assert_str_same
    self.fail("%s do not match: %s\n%s" % (type_comparison_name, reference_filename, diff))
AssertionError: Strings do not match: .../iris/tests/results/pandas/as_series/time_gregorian.txt
--- Reference
+++ Test result
@@ -1,5 +1,5 @@
-2000-01-01 00:00:00    0
-2000-04-10 02:24:00    1
-2000-07-19 04:48:00    2
-2000-10-27 07:12:00    3
-2001-02-04 09:36:00    4
+2000-01-01 00:00:00           0
+2000-04-10 02:24:00.000001    1
+2000-07-19 04:48:00.000009    2
+2000-10-27 07:12:00           3
+2001-02-04 09:36:00           4


======================================================================
FAIL: test_netcdf_save_ndim_auxiliary (iris.tests.test_netcdf.TestNetCDFSave)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../iris/tests/test_netcdf.py", line 575, in test_netcdf_save_ndim_auxiliary
    'netcdf_save_ndim_auxiliary.cdl'))
  File ".../iris/tests/__init__.py", line 316, in assertCDL
    self._check_same(cdl, reference_path, type_comparison_name='CDL')
  File ".../iris/tests/__init__.py", line 442, in _check_same
    type_comparison_name)
  File ".../iris/tests/__init__.py", line 203, in _assert_str_same
    self.fail("%s do not match: %s\n%s" % (type_comparison_name, reference_filename, diff))
AssertionError: CDL do not match:.../iris/tests/results/netcdf/netcdf_save_ndim_auxiliary.cdl
--- Reference
+++ Test result
@@ -9,2 +9,2 @@
-       pr:standard_name = "precipitation_flux" ;
-       pr:long_name = "Precipitation" ;
+       string pr:standard_name = "precipitation_flux" ;
+       string pr:long_name = "Precipitation" ;
@@ -12 +12 @@
-       pr:cell_methods = "time: mean" ;
+       string pr:cell_methods = "time: mean" ;
@@ -25,2 +25,2 @@
-       time:long_name = "Julian Day" ;
-       time:calendar = "gregorian" ;
+       string time:long_name = "Julian Day" ;
+       string time:calendar = "gregorian" ;
@@ -31,2 +31,2 @@
-       rlat:standard_name = "grid_latitude" ;
-       rlat:long_name = "rotated latitude" ;
+       string rlat:standard_name = "grid_latitude" ;
+       string rlat:long_name = "rotated latitude" ;
@@ -36,2 +36,2 @@
-       rlon:standard_name = "grid_longitude" ;
-       rlon:long_name = "rotated longitude" ;
+       string rlon:standard_name = "grid_longitude" ;
+       string rlon:long_name = "rotated longitude" ;
@@ -40,2 +40,2 @@
-       lat:standard_name = "latitude" ;
-       lat:long_name = "latitude" ;
+       string lat:standard_name = "latitude" ;
+       string lat:long_name = "latitude" ;
@@ -44,2 +44,2 @@
-       lon:standard_name = "longitude" ;
-       lon:long_name = "longitude" ;
+       string lon:standard_name = "longitude" ;
+       string lon:long_name = "longitude" ;
```

At the moment, the current requirements somehow limit this set of packages from occurring if you install based on the file (so not triggered on Travis), but it might get upgraded if you are not careful.

**Comment by QuLogic** [comment]
Conda is a bit loose with versions sometimes, so I can try out downgrading a few of them. It looks like it's definitely constrained to the `netcdf4-1.1.1 -> netcdf4-1.1.9` upgrade, and not any of the other packages.

**Comment by QuLogic** [comment]
This first error is probably due to this change in 1.1.2:
> * indexing netCDF variables with integer sequences and boolean arrays now
>   behave the same way (integer sequences are converted to boolean arrays
>   internally). Addresses issue Unidata/netcdf4-python#300.  Since indexing using integer sequences
>   does not behave exactly as before, some client code may break.  For example,
>   previously when integer index arrays had the same length, and that length
>   was equal to the number of dimensions of the array being indexed,
>   netcdf4-python mirrored the numpy indexing behavior and treated the elements
>   of the index arrays as individual sets of integer indices.  This special
>   case has been removed. An IndexError is now raised when the new behavior
>   would produce a different result than the old, i.e. when the
>   indices in an integer sequence are not sorted, or there are duplicate
>   indices in the sequence.

I think the changes to the `.cdl` are caused by this change in 1.1.8:
>  * unicode attributes now written as strings, not bytes (using
>   nc_put_att_string instead of nc_put_att_text, issue Unidata/netcdf4-python#388).

There are various changes to date times across various releases and conda does not provide very many packages in between, so I cannot say with any certainty what caused the failures.

**Comment by shoyer** [comment]
The first error (indexing with duplicate integer labels) should be fixed in the next release of netCDF4: https://github.com/Unidata/netcdf4-python/issues/467

**Comment by rhattersley** [comment]
Thanks for the update @shoyer :+1:

**Comment by pelson** [comment]
We test against the latest NetCDF, so should be resolved.
