### ISSUE TITLE
Issues with soil variables while saving as grib2

### ISSUE THREAD

**Issue by raghu330** [SciTools/iris#1834]
Hi all!

Sorry! could not upload the following as a file, hence pasting the same..  Let me know where I am going wrong? Should I stage the files mentioned below on our ftp?

-Raghu

{{{python
[ncmlogin3][/gpfs3/home/umfcst/NCUM/fcst/20151109/00]> 
[ncmlogin3][/gpfs3/home/umfcst/NCUM/fcst/20151109/00]> python
Python 2.7.9 (default, Jul 15 2015, 11:59:47) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, sys
>>> import numpy, scipy
>>> import gribapi, netCDF4
>>> import iris
>>> 
>>> fname1='umglaa_pd000'
>>> fname2='umglaa_pi000'
>>> 
>>> cubes1 = iris.load(fname1)
>>> print cubes1
0: unknown / (unknown)                 (time: 8; pressure: 18; latitude: 1152; longitude: 1536)
1: air_temperature / (K)               (time: 8; pressure: 18; latitude: 1152; longitude: 1536)
2: geopotential_height / (m)           (time: 8; pressure: 18; latitude: 1152; longitude: 1536)
3: relative_humidity / (%)             (time: 8; pressure: 18; latitude: 1152; longitude: 1536)
4: specific_humidity / (1)             (time: 8; pressure: 18; latitude: 1153; longitude: 1536)
5: upward_air_velocity / (m s-1)       (time: 8; pressure: 18; latitude: 1152; longitude: 1536)
6: x_wind / (m s-1)                    (time: 8; pressure: 18; latitude: 1152; longitude: 1536)
7: y_wind / (m s-1)                    (time: 8; pressure: 18; latitude: 1153; longitude: 1536)
>>> cubes2 = iris.load(fname2)
>>> 
>>> 
>>> print cubes2
0: atmosphere_optical_thickness_due_to_dust_ambient_aerosol / (1) (pseudo_level: 6; time: 7; latitude: 1152; longitude: 1536)
1: moisture_content_of_soil_layer / (kg m-2) (time: 8; soil_model_level_number: 4; latitude: 1152; longitude: 1536)
2: soil_temperature / (K)              (time: 8; soil_model_level_number: 4; latitude: 1152; longitude: 1536)
>>> 
>>> 
>>> iris.save(cubes1[2][0][0],'/gpfs2/home/umtid/test/testGPH.grib2')
>>> 
>>> 
>>> iris.save(cubes2[1][0][0],'/gpfs2/home/umtid/test/testSoilM.grib2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs2/home/umtid/Pythons/Python-2.7.9/lib/python2.7/site-packages/Iris-1.8.1-py2.7-linux-x86_64.egg/iris/io/__init__.py", line 367, in save
    saver(source, target, **kwargs)
  File "/gpfs2/home/umtid/Pythons/Python-2.7.9/lib/python2.7/site-packages/Iris-1.8.1-py2.7-linux-x86_64.egg/iris/fileformats/grib/__init__.py", line 964, in save_grib2
    _save_rules.run(slice2D, grib_message)
  File "/gpfs2/home/umtid/Pythons/Python-2.7.9/lib/python2.7/site-packages/Iris-1.8.1-py2.7-linux-x86_64.egg/iris/fileformats/grib/_save_rules.py", line 1051, in run
    product_definition_section(cube, grib)
  File "/gpfs2/home/umtid/Pythons/Python-2.7.9/lib/python2.7/site-packages/Iris-1.8.1-py2.7-linux-x86_64.egg/iris/fileformats/grib/_save_rules.py", line 948, in product_definition_section
    product_definition_template_8(cube, grib)
  File "/gpfs2/home/umtid/Pythons/Python-2.7.9/lib/python2.7/site-packages/Iris-1.8.1-py2.7-linux-x86_64.egg/iris/fileformats/grib/_save_rules.py", line 877, in product_definition_template_8
    product_definition_template_common(cube, grib)
  File "/gpfs2/home/umtid/Pythons/Python-2.7.9/lib/python2.7/site-packages/Iris-1.8.1-py2.7-linux-x86_64.egg/iris/fileformats/grib/_save_rules.py", line 851, in product_definition_template_common
    set_fixed_surfaces(cube, grib)
  File "/gpfs2/home/umtid/Pythons/Python-2.7.9/lib/python2.7/site-packages/Iris-1.8.1-py2.7-linux-x86_64.egg/iris/fileformats/grib/_save_rules.py", line 683, in set_fixed_surfaces
    'are not recognised or handled.'.format(v_coords_str))
iris.exceptions.TranslationError: The vertical-axis coordinate(s) ('soil_model_level_number') are not recognised or handled.
>>> 
>>> 
>>> iris.save(cubes2[2][0][0],'/gpfs2/home/umtid/test/testSoilT.grib2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs2/home/umtid/Pythons/Python-2.7.9/lib/python2.7/site-packages/Iris-1.8.1-py2.7-linux-x86_64.egg/iris/io/__init__.py", line 367, in save
    saver(source, target, **kwargs)
  File "/gpfs2/home/umtid/Pythons/Python-2.7.9/lib/python2.7/site-packages/Iris-1.8.1-py2.7-linux-x86_64.egg/iris/fileformats/grib/__init__.py", line 964, in save_grib2
    _save_rules.run(slice2D, grib_message)
  File "/gpfs2/home/umtid/Pythons/Python-2.7.9/lib/python2.7/site-packages/Iris-1.8.1-py2.7-linux-x86_64.egg/iris/fileformats/grib/_save_rules.py", line 1051, in run
    product_definition_section(cube, grib)
  File "/gpfs2/home/umtid/Pythons/Python-2.7.9/lib/python2.7/site-packages/Iris-1.8.1-py2.7-linux-x86_64.egg/iris/fileformats/grib/_save_rules.py", line 944, in product_definition_section
    product_definition_template_0(cube, grib)
  File "/gpfs2/home/umtid/Pythons/Python-2.7.9/lib/python2.7/site-packages/Iris-1.8.1-py2.7-linux-x86_64.egg/iris/fileformats/grib/_save_rules.py", line 864, in product_definition_template_0
    product_definition_template_common(cube, grib)
  File "/gpfs2/home/umtid/Pythons/Python-2.7.9/lib/python2.7/site-packages/Iris-1.8.1-py2.7-linux-x86_64.egg/iris/fileformats/grib/_save_rules.py", line 851, in product_definition_template_common
    set_fixed_surfaces(cube, grib)
  File "/gpfs2/home/umtid/Pythons/Python-2.7.9/lib/python2.7/site-packages/Iris-1.8.1-py2.7-linux-x86_64.egg/iris/fileformats/grib/_save_rules.py", line 683, in set_fixed_surfaces
    'are not recognised or handled.'.format(v_coords_str))
iris.exceptions.TranslationError: The vertical-axis coordinate(s) ('soil_model_level_number') are not recognised or handled.
>>> 
>>> 
>>> print cubes2
0: atmosphere_optical_thickness_due_to_dust_ambient_aerosol / (1) (pseudo_level: 6; time: 7; latitude: 1152; longitude: 1536)
1: moisture_content_of_soil_layer / (kg m-2) (time: 8; soil_model_level_number: 4; latitude: 1152; longitude: 1536)
2: soil_temperature / (K)              (time: 8; soil_model_level_number: 4; latitude: 1152; longitude: 1536)
>>> iris.save(cubes2[0][0][0],'/gpfs2/home/umtid/test/testAOT.grib2')
/gpfs2/home/umtid/Pythons/Python-2.7.9/lib/python2.7/site-packages/Iris-1.8.1-py2.7-linux-x86_64.egg/iris/fileformats/grib/_save_rules.py:571: UserWarning: forecast_period encoding problem: scaling required.
  warnings.warn("forecast_period encoding problem: "
/gpfs2/home/umtid/Pythons/Python-2.7.9/lib/python2.7/site-packages/Iris-1.8.1-py2.7-linux-x86_64.egg/iris/fileformats/grib/_save_rules.py:530: UserWarning: Unable to determine Grib2 parameter code for cube.
discipline, parameterCategory and parameterNumber have been set to "missing".
  warnings.warn('Unable to determine Grib2 parameter code for cube.\n'
/gpfs2/home/umtid/Pythons/Python-2.7.9/lib/python2.7/site-packages/Iris-1.8.1-py2.7-linux-x86_64.egg/iris/fileformats/grib/_save_rules.py:989: UserWarning: Unable to determine Grib2 parameter code for cube.
Message data may not be correctly scaled.
  warnings.warn('Unable to determine Grib2 parameter code for cube.\n'
>>> 
>>> exit()
[ncmlogin3][/gpfs3/home/umfcst/NCUM/fcst/20151109/00]> ls -lrt $HOME/test
-rw-r--r-- 1 umtid staff    5308595 Nov  9 21:01 testGPH.grib2
-rw-r--r-- 1 umtid staff          0 Nov  9 21:02 testSoilM.grib2
-rw-r--r-- 1 umtid staff          0 Nov  9 21:02 testSoilT.grib2
-rw-r--r-- 1 umtid staff    5308595 Nov  9 21:03 testAOT.grib2

}}}

**Comment by raghu330** [comment]
This issue has been resolved by AAT@NCMRWF. More information from Arulalan (AAT) soon.
