### ISSUE TITLE
Unable to merge cubes with cell measures when using a time constraint

### ISSUE THREAD

**Issue by ehogan** [SciTools/iris#2076]
I am unable to merge cubes with cell measures when using a time constraint (discovered in #2048). The problem can be reproduced by executing the code below (I can send the netCDF files directly to the person investigating the issue, if required). 

If I try to load the netCDF files using `iris.load_cube` and I don't use a time constraint, `iris.load_cube` fails with a `ConstraintMismatchError: failed to merge into a single cube. Coordinates in cube.dim_coords differ: time.`, which is what I expect (I can instead use `iris.load` then concatenate the resulting cubes).

However, when I use a time constraint, the `time` coordinate in each cube is demoted to a scalar coordinate, which means it should be possible to merge the cubes. But `iris.load_cube` fails with a `Unequal lengths. Cube dimension 0 => 3; metadata u'area of T grid cells' dimension 0 => 1020.`. Dimension 0 corresponds to the `time` coordinate (the constraint selects 3 months of monthly data) and the `area of T grid cells` is the long name of the variable specified as the value of the `cell_measures` attribute of the data variable in the netCDF file I am trying to load. However, the cell measures is described only by the `latitude` and `longitude` auxiliary coordinates, so I don't understand why it's trying to compare the `time` dimension with the cell measures?

```
% ipython
Python 2.7.6 (default, Jan  3 2014, 16:42:21) 
Type "copyright", "credits" or "license" for more information.

IPython 2.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import iris

In [2]: from iris.time import PartialDateTime

In [3]: print iris.__version__
1.10.0-DEV

In [4]: filenames = <filenames>

In [5]: variable_name = 'sst'

In [6]: def time_constraint(cell):
   ...:     return PartialDateTime(2023, 7, 21) <= cell.point <= PartialDateTime(2023, 9, 21)
   ...: 

In [7]: def callback(cube, field, filename):
   ...:     for attribute in cube.attributes.keys():
   ...:         if attribute.startswith('comment') or attribute == 'history':
   ...:             del cube.attributes[attribute]
   ...:     return cube
   ...: 

In [8]: with iris.FUTURE.context(cell_datetime_objects=True):
   ...:     constraint = iris.Constraint(cube_func=lambda cube: cube.var_name == variable_name) & iris.Constraint(time=time_constraint)
   ...:     merged_cube = iris.load_cube(filenames, constraint, callback)
   ...:     
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-e62f45e558b9> in <module>()
      1 with iris.FUTURE.context(cell_datetime_objects=True):
      2         constraint = iris.Constraint(cube_func=lambda cube: cube.var_name == variable_name) & iris.Constraint(time=time_constraint)
----> 3         merged_cube = iris.load_cube(filenames, constraint, callback)
      4 

/project/avd/iris/live/testing/iris/__init__.pyc in load_cube(uris, constraint, callback)
    345         raise ValueError('only a single constraint is allowed')
    346 
--> 347     cubes = _load_collection(uris, constraints, callback).merged().cubes()
    348 
    349     try:

/project/avd/iris/live/testing/iris/cube.pyc in merged(self, unique)
    182         """
    183         return _CubeFilterCollection([pair.merged(unique) for pair in
--> 184                                       self.pairs])
    185 
    186 

/project/avd/iris/live/testing/iris/cube.pyc in merged(self, unique)
    124 
    125         """
--> 126         return _CubeFilter(self.constraint, self.cubes.merge(unique))
    127 
    128 

/project/avd/iris/live/testing/iris/cube.pyc in merge(self, unique)
    466         for name in sorted(proto_cubes_by_name, key=_none_sort):
    467             for proto_cube in proto_cubes_by_name[name]:
--> 468                 merged_cubes.extend(proto_cube.merge(unique=unique))
    469 
    470         return merged_cubes

/project/avd/iris/live/testing/iris/_merge.pyc in merge(self, unique)
   1236                         ma.count_masked(merged_data) == 0):
   1237                     merged_data = merged_data.data
-> 1238             merged_cube = self._get_cube(merged_data)
   1239             merged_cubes.append(merged_cube)
   1240 

/project/avd/iris/live/testing/iris/_merge.pyc in _get_cube(self, data)
   1483                               aux_coords_and_dims=aux_coords_and_dims,
   1484                               cell_measures_and_dims=cms_and_dims,
-> 1485                               **kwargs)
   1486 
   1487         # Add on any aux coord factories.

/project/avd/iris/live/testing/iris/cube.pyc in __init__(self, data, standard_name, long_name, var_name, units, attributes, cell_methods, dim_coords_and_dims, aux_coords_and_dims, aux_factories, cell_measures_and_dims)
    771         if cell_measures_and_dims:
    772             for cell_measure, dims in cell_measures_and_dims:
--> 773                 self.add_cell_measure(cell_measure, dims)
    774 
    775     @property

/project/avd/iris/live/testing/iris/cube.pyc in add_cell_measure(self, cell_measure, data_dims)
    979         if self.cell_measures(cell_measure):
    980             raise ValueError('Duplicate cell_measures are not permitted.')
--> 981         data_dims = self._check_multi_dim_metadata(cell_measure, data_dims)
    982         self._cell_measures_and_dims.append([cell_measure, data_dims])
    983         self._cell_measures_and_dims.sort(key=lambda cm_dims:

/project/avd/iris/live/testing/iris/cube.pyc in _check_multi_dim_metadata(self, metadata, data_dims)
    928                     raise ValueError(msg.format(dim, self.shape[dim],
    929                                                 metadata.name(), i,
--> 930                                                 metadata.shape[i]))
    931         elif metadata.shape != (1,):
    932             msg = 'Missing data dimensions for multi-valued {} {!r}'

ValueError: Unequal lengths. Cube dimension 0 => 3; metadata u'area of T grid cells' dimension 0 => 1020.
```

**Comment by trexfeathers** [comment]
Have been reviewing some historic records elsewhere - this problem has also been experienced by @rcomer, so this is not an isolated issue.

**Comment by BenjaminHarrisonMO** [comment]
I have the same issue. The responses acknowledge the issue has been highlighted before but does provide any solutions or alternatives.

**Comment by HGWright** [comment]
@SciTools/peloton We have not forgotten about this, there are many merge/concatenate problems and we hope to be able to get to them in a future sprint.

**Comment by berndbecker** [comment]
cubelist or cube? return cube, not cubelist! 
0: sea_water_potential_temperature / (degree_C) (-- : 3606; -- : 4322)
1: sea_water_potential_temperature / (degree_C) (-- : 3606; -- : 4322)
2: sea_water_potential_temperature / (degree_C) (-- : 3606; -- : 4322)
3: sea_water_potential_temperature / (degree_C) (-- : 3606; -- : 4322)
4: sea_water_potential_temperature / (degree_C) (-- : 3606; -- : 4322) Unequal lengths. Cube dimension 0 => 5; metadata 'cell_area' dimension 0 => 3606.
Traceback (most recent call last):
  File "/net/home/h03/orca12/repositories/BB-FrontFinding/code_base/front_finder.py", line 335, in make_extended_mask_cube
    d3mask_cube = slice_list_mask.merge_cube()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/h03/orca12/.conda/envs/geovista-env/lib/python3.11/site-packages/iris/cube.py", line 442, in merge_cube
    (merged_cube,) = proto_cube.merge()
                     ^^^^^^^^^^^^^^^^^^
  File "/home/h03/orca12/.conda/envs/geovista-env/lib/python3.11/site-packages/iris/_merge.py", line 1325, in merge
    merged_cube = self._get_cube(merged_data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/h03/orca12/.conda/envs/geovista-env/lib/python3.11/site-packages/iris/_merge.py", line 1606, in _get_cube
    cube = iris.cube.Cube(
           ^^^^^^^^^^^^^^^
  File "/home/h03/orca12/.conda/envs/geovista-env/lib/python3.11/site-packages/iris/cube.py", line 1031, in __init__
    self.add_cell_measure(cell_measure, dims)
  File "/home/h03/orca12/.conda/envs/geovista-env/lib/python3.11/site-packages/iris/cube.py", line 1336, in add_cell_measure
    data_dims = self._check_multi_dim_metadata(cell_measure, data_dims)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/h03/orca12/.conda/envs/geovista-env/lib/python3.11/site-packages/iris/cube.py", line 1218, in _check_multi_dim_metadata
    raise iris.exceptions.CannotAddError(
iris.exceptions.CannotAddError: Unequal lengths. Cube dimension 0 => 5; metadata 'cell_area' dimension 0 => 3606.

The same issue still presents itself when trying to merge horizontal slices of orca12 ocean data.
Is there a work around available anywhere? Cheers!

**Comment by bjlittle** [comment]
@ehogan @BenjaminHarrisonMO @berndbecker @rcomer  Is this still an issue that you'd like to see resolved?

**Comment by berndbecker** [comment]
no longer an issue.

**Comment by pp-mo** [comment]
> no longer an issue.

Oooh, do you mean you don't need it, or the actual problem no longer occurs ?

**Comment by ehogan** [comment]
The CDDS ticket related to this issue was closed in 2022 with the following comment:

> At iris v3.1 it is possible to use iris.util.new_axis to promote a scalar axis back to a dim_coord, and then the cubes can be concatenated. Once concatenated, the data is still lazy loaded so I think this issue can be closed

Therefore, I assume this is no longer an issue 👍

**Comment by pp-mo** [comment]
I think I'm happy that this issue is now "solvable" with newer features, if not totally dead.
If anyone comes across this again though, please re-open with explanation.  I think with a specific need outlined we could add a facility into the new ["equalise_cubes" operation](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris.util.html#iris.util.equalise_cubes).  Which will hopefully also be part of a generalised "combine_cubes" operation by iris 3.12.

**Comment by jmancell** [comment]
Hi, sorry to bring this up again but I've just hit this problem when trying to add some post processing of NEMO data to the seasonal workflow. It can be replicated with the following code:

```python
import iris

# Load the NetCDF file
cube = iris.load_cube("n216_cplfco.1d.c3s.grid_T.nc", "sea surface absolute salinity")
ps_cube_list = iris.cube.CubeList()
# Create a separate lat lon cube for each time point
for sub_cube in cube.slices_over(['time']):
    # In the real code would be converting to practical salinity
    # but for this example just leave it as is
    ps_cube_list.append(sub_cube)

# Combine the sub_cubes back into a single cube
new_cube = ps_cube_list.merge_cube()
```

And gives the following output:
```
Traceback (most recent call last):
  File "/home/users/joseph.mancell/proto_convert_salinity/./merge_fail.py", line 14, in <module>
    new_cube = ps_cube_list.merge_cube()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/apps/sss/environments/production-os47-2/lib/python3.12/site-packages/iris/cube.py", line 340, in merge_cube
    (merged_cube,) = proto_cube.merge()
                     ^^^^^^^^^^^^^^^^^^
  File "/data/apps/sss/environments/production-os47-2/lib/python3.12/site-packages/iris/_merge.py", line 1263, in merge
    merged_cube = self._get_cube(merged_data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/apps/sss/environments/production-os47-2/lib/python3.12/site-packages/iris/_merge.py", line 1535, in _get_cube
    cube = iris.cube.Cube(
           ^^^^^^^^^^^^^^^
  File "/data/apps/sss/environments/production-os47-2/lib/python3.12/site-packages/iris/cube.py", line 1328, in __init__
    self.add_cell_measure(cell_measure, cmdims)
  File "/data/apps/sss/environments/production-os47-2/lib/python3.12/site-packages/iris/cube.py", line 1678, in add_cell_measure
    data_dims = self._check_multi_dim_metadata(cell_measure, data_dims)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/apps/sss/environments/production-os47-2/lib/python3.12/site-packages/iris/cube.py", line 1549, in _check_multi_dim_metadata
    raise iris.exceptions.CannotAddError(
iris.exceptions.CannotAddError: Unequal lengths. Cube dimension 0 => 18; metadata 'Solid angle subtended by gridcell' dimension 0 => 324.
```


I need this for PS47 so have used the work around suggested in the comments above to promote the time scalar to a dim coord and then concatenate rather than merge, but do you think someone might be able to take a look to find a solution to allow merge? I was using production-os46-2

**Comment by rcomer** [comment]
We can actually reproduce this with existing Iris test data

```python
import iris
import iris.tests

# Load the NetCDF file
fname = iris.tests.get_data_path(["NetCDF", "ORCA2", "votemper.nc"])
cube = iris.load_cube(fname)
sub_cubes = iris.cube.CubeList()

# Create a separate lat lon cube for each depth point
for sub_cube in cube.slices_over(['depth']):
    sub_cubes.append(sub_cube)

# Combine the sub_cubes back into a single cube
new_cube = sub_cubes.merge_cube()
```
```
  File "/[path-to-script]/cell_measure_merge.py", line 14, in <module>
    new_cube = sub_cubes.merge_cube()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "[site-packages-path]/iris/cube.py", line 351, in merge_cube
    (merged_cube,) = proto_cube.merge()
                     ^^^^^^^^^^^^^^^^^^
  File "[site-packages-path]/iris/_merge.py", line 1263, in merge
    merged_cube = self._get_cube(merged_data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[site-packages-path]/iris/_merge.py", line 1562, in _get_cube
    cube = iris.cube.Cube(
           ^^^^^^^^^^^^^^^
  File "[site-packages-path]/iris/cube.py", line 1339, in __init__
    self.add_cell_measure(cell_measure, cmdims)
  File "[site-packages-path]/iris/cube.py", line 1692, in add_cell_measure
    data_dims = self._check_multi_dim_metadata(cell_measure, data_dims)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[site-packages-path]/iris/cube.py", line 1563, in _check_multi_dim_metadata
    raise iris.exceptions.CannotAddError(
iris.exceptions.CannotAddError: Unequal lengths. Cube dimension 1 => 1; metadata 'cell_area' dimension 0 => 148.
```

**Comment by pp-mo** [comment]
Just FYI, I thought this might be to do with the new ["LOAD_POLICY/COMBINE_POLICY" changes](https://scitools-iris.readthedocs.io/en/stable/whatsnew/3.12.html#v3-12-24-mar-2025).
But it still occurs when I add `iris.COMBINE_POLICY.set("legacy")`, and also with Iris v3.10 😢

**Comment by rcomer** [comment]
I think I may have figured this one out and am working on a branch.

**Comment by trexfeathers** [comment]
@jmancell Has kindly provided example data for this issue which has been archived under `${DATADIR}/iris-issue-2076-data` for the team account at the UK Met Office 👍

**Comment by rcomer** [comment]
I have confirmed that @jmancell's example works with my branch from #6688 and `new_cube == cube`.
