### ISSUE TITLE
Biggus/Iris interconnectivity issues with v1.10 pre-release

### ISSUE THREAD

**Issue by dkillick** [SciTools/iris#2120]
We are getting reports of issues in the interconnectivity of Iris in the v1.10 pre-release:

> The second issue appears to be a bug in the netcdf saver code. When I try to save my cube I now get a fairly obscure traceback report from the guts of biggus. This seems to stem from Iris attempting to write out a 'least_significant_digit' attribute, even though my code doesn't do anything related to data packing/compression. That might be a red herring though.

``` python
Traceback (most recent call last):
  File "/net/data/cr1/hadby/dev/afterburner_srs/turbofan/branches/r152_jet_diagnostics/bin/abrun.py", line 60, in main
    app.run()
  File "/net/data/cr1/hadby/dev/afterburner_srs/turbofan/branches/r152_jet_diagnostics/lib/afterburner/apps/jet_speed_calc.py", line 174, in run
    self._write_jet_data()
  File "/.../r152_jet_diagnostics/lib/afterburner/apps/jet_speed_calc.py", line 488, in _write_jet_data
    iris.save(jet_cubes, self.outfile)
  File "/.../iris/io/__init__.py", line 421, in save
    saver(source, target, **kwargs)
  File "/.../iris/fileformats/netcdf.py", line 2030, in save
    least_significant_digit)
  File "/.../iris/fileformats/netcdf.py", line 899, in write
    least_significant_digit=least_significant_digit)
  File "/.../iris/fileformats/netcdf.py", line 1786, in _create_cf_data_variable
    biggus.save([cube.lazy_data()], [cf_var], masked=True)
  File "/.../biggus/__init__.py", line 2145, in save
    target[keys] = array[keys].masked_array()
  File "/.../biggus/__init__.py", line 2031, in masked_array
    data[indices] = tile.masked_array()
  File "/.../biggus/__init__.py", line 878, in masked_array
    array = super(NewAxesArray, self).masked_array()
  File "/.../biggus/__init__.py", line 742, in masked_array
    return self.array.masked_array()
  File "/.../biggus/__init__.py", line 1447, in masked_array
    array = self._apply_keys()
  File "/.../biggus/__init__.py", line 1505, in _apply_keys
    array = self.concrete.__getitem__(keys)
  File "/.../python2.7/site-packages/numpy/ma/core.py", line 2992, in __getitem__
    dout = ndarray.__getitem__(_data, indx)
IndexError: unsupported iterator index
```

> The problem comes when I am using an extract from our library to limit a cubelist to only be for a specific site. If I access the data in the object before I try and do this extract, the code works fine. However, if I don’t access it before this then the extract seem to work okay but the print of the data fails:

``` python
Traceback (most recent call last):
File "demo.py", line 50, in <module>
test_code()
File "demo.py", line 46, in test_code
print har_cube.data
File "/.../iris/cube.py", line 1683, in data
data = data.masked_array()
File "/.../biggus/_init.py", line 845, in masked_array
array = super(NewAxesArray, self).masked_array()
File "/.../biggus/_init.py", line 709, in masked_array
return self.array.masked_array()
File "/.../biggus/_init.py", line 1466, in masked_array
array = self._apply_keys()
File "/.../biggus/_init.py", line 1525, in _apply_keys
array = self.concrete._getitem_(keys)
IndexError: unsupported iterator index
```

**Comment by djkirkham** [comment]
This is due to a bug in older versions of NumPy where, for a 1D ndarray, tuples of a certain form cause an error when used as an index. The form which causes the error is a tuple of ints inside a 1-tuple (e.g. `((1,2,3),)`).

This issue has long existed in biggus, it seems, but Iris previously wasn't triggering the error.

**Comment by pp-mo** [comment]
@djkirkham has proposed a possibly relevant workaround here :
  https://github.com/SciTools/biggus/pull/188

**Comment by pp-mo** [comment]
It's not clear whether this SciTools/biggus#188 is really needed...

The problem lies with a new Iris and old numpy version.
We might need this to make our forthcoming internal 1.10 release function properly, _if we can't manage a numpy upgrade for that_.

At present, @marqh believes we are going to need numpy >=1.9 for other reasons.
That would make this fix unnecessary.
We can revive it if needed (if we can't manage a numpy upgrade yet).

**Comment by marqh** [comment]
I think it would be worth having a test in iris to make sure this is working effectively.  I would like to leave this issue open until i can get a test case provided

at present Iris is pinned to numpy 1.8, al be it indirectly, so until that changes this is a problem

**Comment by marqh** [comment]
none of this should hold up the 1.10.0 release, so I am removing this from the milestone

**Comment by pp-mo** [comment]
Note that SciTools/biggus#188 now superceded by SciTools/biggus#189
Adopting that should fix the problems encountered here.

Not yet done : it may also/still be useful to enhance the Iris tests to contain an example,
as suggested [above](https://github.com/SciTools/iris/issues/2120#issuecomment-244327106)

**Comment by dkillick** [comment]
Given that [we've now retired biggus](https://github.com/SciTools/biggus/pull/207), I think we can close this issue.
