### ISSUE TITLE
sporadic failure modes

### ISSUE THREAD

**Issue by marqh** [SciTools/iris#2276]
I would like to catalogue known sporadic failure modes for continuous integration testing and see if we can fix some of them, so here's an issue to corral effort

 * [ ] netcdf4 cannot allocate memort

**Comment by marqh** [comment]
```
======================================================================

ERROR: test_no_hybrid (iris.tests.test_netcdf.TestSave)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/miniconda/envs/test-environment/lib/python3.4/site-packages/Iris-1.12.0rc0-py3.4-linux-x86_64.egg/iris/tests/test_netcdf.py", line 322, in test_no_hybrid

    iris.save(cube, file_out, netcdf_format='NETCDF3_CLASSIC')

  File "/home/travis/miniconda/envs/test-environment/lib/python3.4/site-packages/Iris-1.12.0rc0-py3.4-linux-x86_64.egg/iris/io/__init__.py", line 402, in save

    saver(source, target, **kwargs)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.4/site-packages/Iris-1.12.0rc0-py3.4-linux-x86_64.egg/iris/fileformats/netcdf.py", line 2245, in save

    least_significant_digit, packing=packspec)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.4/site-packages/Iris-1.12.0rc0-py3.4-linux-x86_64.egg/iris/fileformats/netcdf.py", line 954, in write

    least_significant_digit=least_significant_digit, packing=packing)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.4/site-packages/Iris-1.12.0rc0-py3.4-linux-x86_64.egg/iris/fileformats/netcdf.py", line 1932, in _create_cf_data_variable

    cf_var[:] = data

  File "netCDF4/_netCDF4.pyx", line 3996, in netCDF4._netCDF4.Variable.__setitem__ (netCDF4/_netCDF4.c:43637)

  File "netCDF4/_netCDF4.pyx", line 4208, in netCDF4._netCDF4.Variable._put (netCDF4/_netCDF4.c:45517)

RuntimeError: Cannot allocate memory

----------------------------------------------------------------------
```
