### ISSUE TITLE
problem with importing iris from Spyder in the Windows 64-bit system

### ISSUE THREAD

**Issue by WenguangWei** [SciTools/iris#2277]
Hi all,

I might meet a problem common to some people who are under the windows environment. When I firstly run `import iris` statement in a python or ipython console. The error is as follows:

```python
import iris
```

```
Traceback (most recent call last):

File "<ipython-input-1-005053b25f37>", line 1, in <module>
  import iris

File "D:\Users\Administrator\Anaconda2\lib\site-packages\iris\__init__.py", line 111, in <module>
  import iris.cube

File "D:\Users\Administrator\Anaconda2\lib\site-packages\iris\cube.py", line 40, in <module>
  import iris.analysis

File "D:\Users\Administrator\Anaconda2\lib\site-packages\iris\analysis\__init__.py", line 61, in <module>
  from iris.analysis._area_weighted import AreaWeightedRegridder

File "D:\Users\Administrator\Anaconda2\lib\site-packages\iris\analysis\_area_weighted.py", line 23, in <module>
  from iris.analysis._interpolation import get_xy_dim_coords, snapshot_grid

File "D:\Users\Administrator\Anaconda2\lib\site-packages\iris\analysis\_interpolation.py", line 31, in <module>
  from iris.analysis.cartography import wrap_lons as wrap_circular_points

File "D:\Users\Administrator\Anaconda2\lib\site-packages\iris\analysis\cartography.py", line 29, in <module>
  import cf_units

File "D:\Users\Administrator\Anaconda2\lib\site-packages\cf_units\__init__.py", line 403, in <module>
  _status_msg, _error_msg))

OSError: [UT_PARSE] Failed to open UDUNITS-2 XML unit database : "No such file or directory"
```

After that, a different error occurs when I re-run the code:

```python
import iris
```

```
Traceback (most recent call last):

File "<ipython-input-2-005053b25f37>", line 1, in <module>
  import iris

File "D:\Users\Administrator\Anaconda2\lib\site-packages\iris\__init__.py", line 111, in <module>
  import iris.cube

File "D:\Users\Administrator\Anaconda2\lib\site-packages\iris\cube.py", line 40, in <module>
  import iris.analysis

File "D:\Users\Administrator\Anaconda2\lib\site-packages\iris\analysis\__init__.py", line 61, in <module>
  from iris.analysis._area_weighted import AreaWeightedRegridder

File "D:\Users\Administrator\Anaconda2\lib\site-packages\iris\analysis\_area_weighted.py", line 23, in <module>
  from iris.analysis._interpolation import get_xy_dim_coords, snapshot_grid

File "D:\Users\Administrator\Anaconda2\lib\site-packages\iris\analysis\_interpolation.py", line 31, in <module>
  from iris.analysis.cartography import wrap_lons as wrap_circular_points

File "D:\Users\Administrator\Anaconda2\lib\site-packages\iris\analysis\cartography.py", line 29, in <module>
  import cf_units

File "D:\Users\Administrator\Anaconda2\lib\site-packages\cf_units\__init__.py", line 44, in <module>
  from . import config

ImportError: cannot import name config
```

I had followed some threads about similar problems in this forum, such like the following two:
#2055 SciTools/conda-recipes-scitools#115.

But after I had tried all the solutions above, the problem is still there. So I tried to locate to the place where the error happened and do some debugging. It seems that there is something wrong with the loading of udunits xml database. I found that the separator in `sys.prefix` is not the same as that in windows which makes two types of separator in the path string (`/`and `\\`). I thought this might be the reason, so I changed the separator in the path string to make a windows-type path.  the corresponding codes are as follows:

```python
#
# load the UDUNITS-2 xml-formatted unit-database
#
if not _ud_system:
    # Ignore standard noisy UDUNITS-2 start-up.
    with suppress_errors():
        # Load the unit-database from the default location (modified via
        # the UDUNITS2_XML_PATH environment variable) and if that fails look
        # relative to sys.prefix to support environments such as conda.
        _ud_system = _ut_read_xml(None)
        if _ud_system is None:
            _alt_xml_path = config.get_option(
                'System', 'udunits2_xml_path',
                default=os.path.join(sys.prefix, 'share', 'udunits',
                                     'udunits2.xml'))
            print('_alt_xml_path_before_change: '+_alt_xml_path)
            _alt_xml_path = _alt_xml_path.replace('/','\\')
            print('_alt_xml_path_after_change: '+_alt_xml_path)
            _ud_system = _ut_read_xml(_alt_xml_path.encode())
    if not _ud_system:
        _status_msg = 'UNKNOWN'
        _error_msg = ''
        _status = _ut_get_status()
        try:
            _status_msg = _UT_STATUS[_status]
        except IndexError:
            pass
        _errno = ctypes.get_errno()
        if _errno != 0:
            _error_msg = ': "%s"' % _strerror(_errno)
            ctypes.set_errno(0)
        raise OSError('[%s] Failed to open UDUNITS-2 XML unit database %s' % (
            _status_msg, _error_msg))
```

How, the problem remains and the output are as follows:

```python
import iris
```

```
_alt_xml_path_before_change: D:/Users/Administrator/Anaconda2\Library\share\udunits\udunits2.xml
_alt_xml_path_after_change: D:\Users\Administrator\Anaconda2\Library\share\udunits\udunits2.xml

Traceback (most recent call last):

File "<ipython-input-1-005053b25f37>", line 1, in <module>
  import iris

File "D:\Users\Administrator\Anaconda2\lib\site-packages\iris\__init__.py", line 111, in <module>
  import iris.cube

File "D:\Users\Administrator\Anaconda2\lib\site-packages\iris\cube.py", line 40, in <module>
  import iris.analysis

File "D:\Users\Administrator\Anaconda2\lib\site-packages\iris\analysis\__init__.py", line 61, in <module>
  from iris.analysis._area_weighted import AreaWeightedRegridder

File "D:\Users\Administrator\Anaconda2\lib\site-packages\iris\analysis\_area_weighted.py", line 23, in <module>
  from iris.analysis._interpolation import get_xy_dim_coords, snapshot_grid

File "D:\Users\Administrator\Anaconda2\lib\site-packages\iris\analysis\_interpolation.py", line 31, in <module>
  from iris.analysis.cartography import wrap_lons as wrap_circular_points

File "D:\Users\Administrator\Anaconda2\lib\site-packages\iris\analysis\cartography.py", line 29, in <module>
  import cf_units

File "D:\Users\Administrator\Anaconda2\lib\site-packages\cf_units\__init__.py", line 404, in <module>
  _status_msg, _error_msg))

OSError: [UT_PARSE] Failed to open UDUNITS-2 XML unit database : "No such file or directory"
```

I wonder whether there are other places using the `sys.prefix` which leads to some errors. But I can't discover them all. Does anyone have some idea about this?

**Comment by WenguangWei** [comment]
The error finally dispeared when I removed the anaconda and iris installed in D driver but re-installed them into the C driver. No idea how it works but I can import and use the iris now.

**Comment by WenguangWei** [comment]
A remaining problem is that if I want to use the iris, the first time I import it should be from the C driver, or the same error will show up again! After that you can import it from whatever driver, e.g. D and E. This still bothers me a lot.

**Comment by dkillick** [comment]
Hi @WenguangWei - thanks for raising this with us. What you're encountering here is not a problem with file path formatting or existence of the XML file, but a known bug in UDUNITS2 (see Unidata/UDUNITS-2#43) that affects its behaviour on Windows. Specifically (and a little simplistically), it means you cannot use UDUNITS2 unless you are on the drive that UDUNITS2 is installed to. 

Sadly this won't go away until we can get to the bottom of the bug with UDUNITS2, but the easy workaround is to only use UDUNITS2 when you're on the drive (`C:` in your case) that UDUNITS2 is installed to.

**Comment by WenguangWei** [comment]
Thanks, @dkillick -Yeh, this is the way currently I use iris: Each time I start a Python console or IPython console, I have to firstly import it from c driver. Sometimes the Python or IPython console dies for some reason and I start a new one. I also have to re-import it from c driver, or it will not work.

**Comment by rcomer** [comment]
From above conversation, this seems to have been a problem with UDUNITS, rather than Iris.  From conversation [there](https://github.com/Unidata/UDUNITS-2/issues/43), it may even have been fixed.  Anyway, there doesn’t seem to be anything we can do about it in Iris, so closing.
