### ISSUE TITLE
(prior) netCDF loading

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2308]
Load to a cube with dask array content

**Comment by pp-mo** [comment]
**Relevant code sections**
```
fileformats
    _pyke_rules."fc_rules_cf.krb"
        build_auxiliary_coordinate : OrthoArrayAdapter
        build_cell_measures : OrthoArrayAdapter
    netcdf
        _load_cube() : OrthoArrayAdapter
        Saver._create_cf_data_variable : save
```

**Comment by marqh** [comment]
progress so far:
https://github.com/SciTools/iris/compare/master...marqh:dasking?expand=1

(remember to rebuild or hack the pyke rules)

**Comment by marqh** [comment]
i chose to ignore unit tests, as we are changing behaviour, so:
`python -m unittest discover -v -s iris.tests.integration`


```
======================================================================
ERROR: test_round_trip (iris.tests.integration.test_netcdf.TestCellMeasures)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marky/coding/scitools/iris/lib/iris/tests/integration/test_netcdf.py", line 275, in test_round_trip
    iris.save(cube, filename, unlimited_dimensions=[])
  File "/home/marky/coding/scitools/iris/lib/iris/io/__init__.py", line 402, in save
    saver(source, target, **kwargs)
  File "/home/marky/coding/scitools/iris/lib/iris/fileformats/netcdf.py", line 2247, in save
    least_significant_digit, packing=packspec)
  File "/home/marky/coding/scitools/iris/lib/iris/fileformats/netcdf.py", line 967, in write
    self._add_cell_measures(cube, cf_var_cube, dimension_names)
  File "/home/marky/coding/scitools/iris/lib/iris/fileformats/netcdf.py", line 1150, in _add_cell_measures
    cm)
  File "/home/marky/coding/scitools/iris/lib/iris/fileformats/netcdf.py", line 1497, in _create_cf_cell_measure_variable
    data = self._ensure_valid_dtype(cell_measure.data, 'coordinate',
  File "/home/marky/coding/scitools/iris/lib/iris/coords.py", line 1749, in data
    return data.view()
TypeError: view() missing 1 required positional argument: 'dtype'

======================================================================
ERROR: test_lazy_mask_preserve_fill_value (iris.tests.integration.test_netcdf.TestLazySave)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marky/coding/scitools/iris/lib/iris/tests/integration/test_netcdf.py", line 224, in test_lazy_mask_preserve_fill_value
    self.assertEqual(avar._FillValue, -1)
  File "netCDF4/_netCDF4.pyx", line 3586, in netCDF4._netCDF4.Variable.__getattr__ (netCDF4/_netCDF4.c:35943)
  File "netCDF4/_netCDF4.pyx", line 3401, in netCDF4._netCDF4.Variable.getncattr (netCDF4/_netCDF4.c:33305)
  File "netCDF4/_netCDF4.pyx", line 1101, in netCDF4._netCDF4._get_att (netCDF4/_netCDF4.c:4070)
AttributeError: NetCDF: Attribute not found

======================================================================
ERROR: test_tri_polar__nearest (iris.tests.integration.test_trajectory.TestTriPolar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marky/coding/scitools/iris/lib/iris/tests/integration/test_trajectory.py", line 206, in test_tri_polar__nearest
    test_cube.data.set_fill_value(0.0)
AttributeError: 'numpy.ndarray' object has no attribute 'set_fill_value'

======================================================================
FAIL: test_agg_by_aux_coord (iris.tests.integration.test_aggregated_cube.Test_aggregated_by)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marky/coding/scitools/iris/lib/iris/tests/integration/test_aggregated_cube.py", line 48, in test_agg_by_aux_coord
    self.assertIsInstance(forecast_period_coord._points, biggus.Array)
AssertionError: array([ 1.16666668,  1.33333333,  1.5       ,  1.66666667,  1.83333334,  2.        ]) is not an instance of <class 'biggus._init.Array'>

======================================================================
FAIL: test_lazy_preserved_save (iris.tests.integration.test_netcdf.TestLazySave)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marky/coding/scitools/iris/lib/iris/tests/integration/test_netcdf.py", line 207, in test_lazy_preserved_save
    self.assertTrue(acube.has_lazy_data())
AssertionError: False is not true

======================================================================
FAIL: test_multi_packed_multi_dtype (iris.tests.integration.test_netcdf.TestPackedData)
Test saving multiple packed cubes with pack_dtype list.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marky/coding/scitools/iris/lib/iris/tests/integration/test_netcdf.py", line 432, in test_multi_packed_multi_dtype
    self._multi_test('multi_packed_multi_dtype.cdl', multi_dtype=True)
  File "/home/marky/coding/scitools/iris/lib/iris/tests/integration/test_netcdf.py", line 420, in _multi_test
    decimal=decimal)
  File "/home/marky/coding/scitools/iris/lib/iris/tests/__init__.py", line 561, in assertArrayAlmostEqual
    np.testing.assert_array_almost_equal(a, b, decimal=decimal)
  File "/data/pyenvs/envs/irisdask34/lib/python3.4/site-packages/numpy/testing/utils.py", line 892, in assert_array_almost_equal
    precision=decimal)
  File "/data/pyenvs/envs/irisdask34/lib/python3.4/site-packages/numpy/testing/utils.py", line 713, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 2 decimals

(mismatch 3.9637239979128935e-05%)
 x: array([[[ 239.93,  239.93,  239.93, ...,  239.93,  239.93,  239.93],
        [ 236.94,  236.73,  236.78, ...,  235.7 ,  236.55,  237.08],
        [ 236.58,  235.8 ,  235.44, ...,  235.21,  236.16,  236.69],...
 y: array([[[ 239.93,  239.93,  239.93, ...,  239.93,  239.93,  239.93],
        [ 236.94,  236.73,  236.79, ...,  235.7 ,  236.55,  237.08],
        [ 236.58,  235.8 ,  235.44, ...,  235.21,  236.16,  236.69],...

======================================================================
FAIL: test_multi_packed_single_dtype (iris.tests.integration.test_netcdf.TestPackedData)
Test saving multiple packed cubes with the same pack_dtype.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marky/coding/scitools/iris/lib/iris/tests/integration/test_netcdf.py", line 427, in test_multi_packed_single_dtype
    self._multi_test('multi_packed_single_dtype.cdl')
  File "/home/marky/coding/scitools/iris/lib/iris/tests/integration/test_netcdf.py", line 420, in _multi_test
    decimal=decimal)
  File "/home/marky/coding/scitools/iris/lib/iris/tests/__init__.py", line 561, in assertArrayAlmostEqual
    np.testing.assert_array_almost_equal(a, b, decimal=decimal)
  File "/data/pyenvs/envs/irisdask34/lib/python3.4/site-packages/numpy/testing/utils.py", line 892, in assert_array_almost_equal
    precision=decimal)
  File "/data/pyenvs/envs/irisdask34/lib/python3.4/site-packages/numpy/testing/utils.py", line 713, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals

(mismatch 1.9337027524099426%)
 x: array([[[  0.0000000e+00,   0.0000000e+00,   0.0000000e+00, ...,
           0.0000000e+00,   0.0000000e+00,   0.0000000e+00],
        [  1.8784527e-07,   1.7914272e-07,   1.3874165e-07, ...,...
 y: array([[[  0.0000000e+00,   0.0000000e+00,   0.0000000e+00, ...,
           0.0000000e+00,   0.0000000e+00,   0.0000000e+00],
        [  1.7938430e-07,   1.7938430e-07,   1.4948692e-07, ...,...

----------------------------------------------------------------------
Ran 225 tests in 24.232s

FAILED (failures=4, errors=3, skipped=48)


```

not a bad score

**Comment by marqh** [comment]
clearly some issues with handling masks and fill values here

and there is a biggus.save operation which is tested which enables streaming of lazy data onto files which we would need to provide as a capability

**Comment by marqh** [comment]
@bjlittle that's about all i've got for now

**Comment by pp-mo** [comment]
By my understanding, it shouldn't be possible to compare a dask array with a real array, but it seems somehow it does.
After some investigation, I discovered that the 'bool' function is causing realization of lazy arrays, which I think is probably affecting anything calling np.all with a lazy array :
```
>>> class fakearray(object):
...   def __init__(self, array):
...     self._array = array
...     self.dtype = array.dtype
...     self.shape = array.shape
...   def __getitem__(self, keys):
...     print '!access: keys=', keys
...     return self._array[keys]
... 
>>> fa1 = fakearray(np.array([0,1,2])
... )
>>> da1 = dask.array.from_array(fa1, 1e6)
>>> da1
dask.array<array-f..., shape=(3,), dtype=int64, chunksize=(3,)>
>>> da1.compute()
!access: keys= (slice(0, 3, None),)
array([0, 1, 2])
>>> da1[0]
dask.array<getitem..., shape=(), dtype=int64, chunksize=()>
>>> da1[0].compute()
!access: keys= (0,)
array(0)
>>> datst = da1 == [0, 0, 2]
>>> datst
dask.array<eq-81f8..., shape=(3,), dtype=bool, chunksize=(3,)>
>>> datst.compute()
!access: keys= (slice(0, 3, None),)
array([ True, False,  True], dtype=bool)
>>> list(x for x in datst)
[dask.array<getitem..., shape=(), dtype=bool, chunksize=()>, dask.array<getitem..., shape=(), dtype=bool, chunksize=()>, dask.array<getitem..., shape=(), dtype=bool, chunksize=()>]
>>> list(x.compute() for x in datst)
!access: keys= (slice(0, 3, None),)
!access: keys= (slice(0, 3, None),)
!access: keys= (slice(0, 3, None),)
[True, False, True]
>>> list(bool(x) for x in datst)
!access: keys= (slice(0, 3, None),)
!access: keys= (slice(0, 3, None),)
!access: keys= (slice(0, 3, None),)
[True, False, True]
>>> 
```
Note how "bool" is causing a "compute" here.
I think this is causing np.allclose and similar to "magically" realize the data + makes it work.
But I don't really understand if that is intended behaviour.
I find it highly unexpected, and it's not anywhere I can find in the documentation.
