### ISSUE TITLE
Iris compatibility with latest netcdf4

### ISSUE THREAD

**Issue by dkillick** [SciTools/iris#2322]
Iris is not compatible with the latest version of netcdf4 (v1.2.7). For example:

```python
import datetime
import os

import iris
from iris.time import PartialDateTime


iris.FUTURE.cell_datetime_objects = True

fn = 'A1B_north_america.nc'  # Has 360-day calendar.
cube = iris.load_cube(iris.sample_data_path(fn))
cube.coord('time').bounds = None  # Necessary for running constraints on time.

dt = datetime.datetime(2014, 12, 22)
pdt = PartialDateTime(year=dt.year, month=dt.month, day=dt.day)

t_cstr = iris.Constraint(time=lambda cell: cell < pdt)
subcube = cube.extract(t_cstr)

Traceback (most recent call last):
  File "/.../sample_code.py", line 43, in <module>
    baseline_cube = cube.extract(baseline_cstr)
  File "/.../miniconda/envs/dist_forge/lib/python2.7/site-packages/iris/cube.py", line 2312, in extract
    return constraint.extract(self)
  File "/.../envs/dist_forge/lib/python2.7/site-packages/iris/_constraints.py", line 151, in extract
    resultant_CIM = self._CIM_extract(cube)
  File "/.../miniconda/envs/dist_forge/lib/python2.7/site-packages/iris/_constraints.py", line 175, in _CIM_extract
    resultant_CIM = resultant_CIM & coord_constraint.extract(cube)
  File "/.../miniconda/envs/dist_forge/lib/python2.7/site-packages/iris/_constraints.py", line 290, in extract
    r = np.array([call_func(cell) for cell in coord.cells()])
  File "/.../sample_code.py", line 42, in <lambda>
    baseline_cstr = iris.Constraint(time=lambda c: baseline[0] < c <= baseline[1])
  File "/.../miniconda/envs/dist_forge/lib/python2.7/functools.py", line 62, in <lambda>
    '__gt__': [('__lt__', lambda self, other: not (self > other or self == other)),
  File "/.../miniconda/envs/dist_forge/lib/python2.7/site-packages/iris/coords.py", line 346, in __lt__
    return self.__common_cmp__(other, operator.lt)
  File "/.../miniconda/envs/dist_forge/lib/python2.7/site-packages/iris/coords.py", line 332, in __common_cmp__
    result = operator_method(me, other)
  File "netcdftime/_netcdftime.pyx", line 1295, in netcdftime._netcdftime.datetime.__richcmp__ (netcdftime/_netcdftime.c:23410)
TypeError: cannot compare netcdftime._netcdftime.Datetime360Day(1861, 6, 30, 12, 0, 0, 0, -1, 180) and PartialDateTime(year=1986, month=1, day=1, hour=0, minute=0, second=0, microsecond=0)
```

This same operation works fine with previous versions of netcdf4, such as v1.2.4.

See also https://github.com/SciTools/conda-recipes-scitools/pull/229.

**Comment by dkillick** [comment]
I added an integration test to try and replicate this; see #2337.

**Comment by pelson** [comment]
Looks like a bunch of tests got merged, but I can't actually see where it got fixed...

@dkillick - could you confirm the status on this please?

**Comment by pelson** [comment]
cc @djkirkham, in case you have any input.

**Comment by djkirkham** [comment]
It was fixed in #2440, [here](https://github.com/SciTools/iris/pull/2440/files#diff-fae2e3bb7827f6df8671256d1c779951R332)

**Comment by djkirkham** [comment]
Hang on, it looks like the fix is wrong - the reverse of `lt` should be `ge` not `gt`, and similarly for the others. My bad, I'll put up a PR.

**Comment by djkirkham** [comment]
Anyway, I'll close this issue now.
