### ISSUE TITLE
Sphinx fails to build interpolate_column.py

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#2333]
```
 from /net/home/h05/itwl/projects/git/iris/docs/iris/src/userguide/regridding_plots/interpolate_column.py:
Traceback (most recent call last):
  File "/opt/scitools/environments/default/2017_01_23/lib/python2.7/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in run_code
    six.exec_(code, ns)
  File "/opt/scitools/environments/default/2017_01_23/lib/python2.7/site-packages/matplotlib/externals/six.py", line 672, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "<string>", line 14, in <module>
  File "/home/h05/itwl/projects/git/iris/lib/iris/__init__.py", line 376, in load_cube
    raise iris.exceptions.ConstraintMismatchError(str(e))
ConstraintMismatchError: failed to merge into a single cube.
  cube.standard_name differs: u'air_potential_temperature' != u'surface_altitude'
  cube.var_name differs: u'air_potential_temperature' != u'surface_altitude'
  cube.units differs: Unit('K') != Unit('m')
  cube.attributes values differ for keys: 'STASH'
  cube.shape differs: (15, 100, 100) != (100, 100)
```

This fails. It's always failed from what I can see ... we need to fix this.

**Comment by tkknight** [comment]
As part of the new read the docs for Iris (https://github.com/SciTools/iris/pull/3752) , this code seems to work and generates a plot.  See https://scitools-iris.readthedocs.io/en/latest/userguide/interpolation_and_regridding.html#interpolating-non-horizontal-coordinates (scroll down a a bit to see the plot)

I can also download the source (https://scitools-iris.readthedocs.io/en/latest/userguide/regridding_plots/interpolate_column.py) and run locally and the plot works ok.

Am I missing something?  Could this issue now be closed?

**Comment by bjlittle** [comment]
@tkknight Awesome, thanks :tada:
