### ISSUE TITLE
Fix NCProperties error

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/iris#2377]
FAIL: test_no_global_attributes (__main__.TestNetCDFSave)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/h06/cbosley/Projects/iris/lib/iris/tests/test_netcdf.py", line 796, in test_no_global_attributes
    'netcdf_save_no_global_attr.cdl'))
  File "/home/h06/cbosley/Projects/iris/lib/iris/tests/__init__.py", line 361, in assertCDL
    self._check_same(cdl, reference_path, type_comparison_name='CDL')
  File "/home/h06/cbosley/Projects/iris/lib/iris/tests/__init__.py", line 493, in _check_same
    type_comparison_name)
  File "/home/h06/cbosley/Projects/iris/lib/iris/tests/__init__.py", line 239, in _assert_str_same
    self.fail("%s do not match: %s\n%s" % (type_comparison_name, reference_filename, diff))
AssertionError: CDL do not match: /home/h06/cbosley/Projects/iris/lib/iris/tests/results/netcdf/netcdf_save_no_global_attr.cdl
--- Reference
+++ Test result
@@ -46,0 +47 @@
+		:_NCProperties = "version=1|netcdflibversion=4.4.1|hdf5libversion=1.8.17" ;

What does it even mean???

**Comment by corinnebosley** [comment]
This seems to be a problem that my PyCharm is having with getting all the bits of the scitools/default-next environment to talk to each other.  Not necessarily a problem in itself, certainly not for the big picture.  Might have to come back to it later though.

**Comment by corinnebosley** [comment]
This is because of an ncdump version conflict, and can be got around by operating in a terminal in PyCharm in which a module load has been performed rather than just using the scitools Python interpreter.
