### ISSUE TITLE
Address test for fill value for some lazy data

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/iris#2378]
```
ERROR: test_netcdf_save_single (__main__.TestNetCDFSave)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/h06/cbosley/Projects/iris/lib/iris/tests/test_netcdf.py", line 437, in test_netcdf_save_single
    iris.save(cube, file_out)
  File "/home/h06/cbosley/Projects/iris/lib/iris/io/__init__.py", line 402, in save
    saver(source, target, **kwargs)
  File "/home/h06/cbosley/Projects/iris/lib/iris/fileformats/netcdf.py", line 2246, in save
    least_significant_digit, packing=packspec)
  File "/home/h06/cbosley/Projects/iris/lib/iris/fileformats/netcdf.py", line 955, in write
    least_significant_digit=least_significant_digit, packing=packing)
  File "/home/h06/cbosley/Projects/iris/lib/iris/fileformats/netcdf.py", line 1940, in _create_cf_data_variable
    fill_value = cube.lazy_data().fill_value
AttributeError: 'Array' object has no attribute 'fill_value'
```

**Comment by corinnebosley** [comment]
https://github.com/marqh/iris/pull/39

**Comment by corinnebosley** [comment]
This particular test still fails, but for a different reason (which will only be solved when we address the NetCDF Saver).  For now, the whole module TestNetCDFSave needs to be skipped.  I think.
