### ISSUE TITLE
Address tests for data which was deferred and is now loaded

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/iris#2379]
```
FAIL: test_trajectory (iris.tests.test_netcdf.TestNetCDFSave)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/net/home/h06/cbosley/Projects/iris/lib/iris/tests/test_netcdf.py", line 695, in test_trajectory
    checksum=False)
  File "/net/home/h06/cbosley/Projects/iris/lib/iris/tests/__init__.py", line 397, in assertCML
    self._check_same(xml, reference_path)
  File "/net/home/h06/cbosley/Projects/iris/lib/iris/tests/__init__.py", line 490, in _check_same
    type_comparison_name)
  File "/net/home/h06/cbosley/Projects/iris/lib/iris/tests/__init__.py", line 236, in _assert_str_same
    self.fail("%s do not match: %s\n%s" % (type_comparison_name, reference_filename, diff))
AssertionError: CML do not match: /net/home/h06/cbosley/Projects/iris/lib/iris/tests/results/netcdf/save_load_traj.cml
--- Reference
+++ Test result
@@ -39 +39 @@
-    <data dtype="float64" shape="(10,)" state="deferred"/>
+    <data dtype="float64" shape="(10,)" state="loaded"/>
```

**Comment by corinnebosley** [comment]
Magically fixed.
