### ISSUE TITLE
Cube arithmetic on cubes with differing coordinates

### ISSUE THREAD

**Issue by djkirkham** [SciTools/iris#2446]
Given two cubes of the same shape with different coordinates, multiplying or dividing the cubes will result in a cube with the same coordinates as the first. This differs from addition and subtraction, where an error is raised about differing coordinates:

```
>>> from iris import DimCoord, Cube
>>> import numpy as np
>>> data = np.zeros((3,4))
>>> a = DimCoord([1,2,3], long_name='a')
>>> b = DimCoord([1,2,3,4], long_name='b')
>>> x = DimCoord([4,5,6], long_name='x')
>>> y = DimCoord([5,6,7,8], long_name='y')
>>> c1 = Cube(data, dim_coords_and_dims=[(a,0),(b,1)])
>>> c2 = Cube(data, dim_coords_and_dims=[(x,0),(y,1)])
>>> print c1
unknown / (unknown)                 (a: 3; b: 4)
     Dimension coordinates:
          a                           x     -
          b                           -     x
>>> print c2
unknown / (unknown)                 (x: 3; y: 4)
     Dimension coordinates:
          x                           x     -
          y                           -     x
>>> print c1 * c2
unknown / (unknown)                 (a: 3; b: 4)
     Dimension coordinates:
          a                           x     -
          b                           -     x
>>> c1 + c2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../iris/cube.py", line 2823, in __add__
    return iris.analysis.maths.add(self, other, ignore=True)
  File ".../iris/analysis/maths.py", line 197, in add
    ignore=ignore, in_place=in_place)
  File ".../iris/analysis/maths.py", line 279, in _add_subtract_common
    in bad_coord_grps}))
ValueError: This operation cannot be performed as there are differing coordinates (a, x, b, y) remaining which cannot be ignored.
```

This is especially confusing when the cubes contain the same coordinates, albeit with one of them in reverse order, where users might reasonably expect it to "just work".

**Comment by djkirkham** [comment]
@marqh

**Comment by pp-mo** [comment]
Cf. #1911 #2599

**Comment by bjlittle** [comment]
Tidying up... closed by https://github.com/SciTools/iris/pull/2498
