### ISSUE TITLE
duplicate stash codes and names

### ISSUE THREAD

**Issue by rwbodman** [SciTools/iris#2529]
Hi, I am trying to extract some data from a UM file but it contains two variables with the same stash code and name, the only difference is one is a single surface temp  whereas the other contains temps at 8 time steps.  I am getting the following error.  How can a deal with this?

```python
tas_cube = iris.load_cube(filename, iris.AttributeConstraint(STASH='m01s00i024'))
```

```
/projects/access/apps/pythonlib/iris/1.9.1/lib/python2.7/site-packages/Iris-1.9.1-py2.7-linux-x86_64.egg/iris/fileformats/ff.py:699: UserWarning: The STASH code m01s03i365 was not found in the STASH to grid type mapping. Picking the P position as the cell type
  'position as the cell type'.format(stash))
/projects/access/apps/pythonlib/iris/1.9.1/lib/python2.7/site-packages/Iris-1.9.1-py2.7-linux-x86_64.egg/iris/fileformats/ff.py:699: UserWarning: The STASH code m01s03i366 was not found in the STASH to grid type mapping. Picking the P position as the cell type
  'position as the cell type'.format(stash))
/projects/access/apps/pythonlib/iris/1.9.1/lib/python2.7/site-packages/Iris-1.9.1-py2.7-linux-x86_64.egg/iris/fileformats/ff.py:699: UserWarning: The STASH code m01s03i367 was not found in the STASH to grid type mapping. Picking the P position as the cell type
  'position as the cell type'.format(stash))
/projects/access/apps/pythonlib/iris/1.9.1/lib/python2.7/site-packages/Iris-1.9.1-py2.7-linux-x86_64.egg/iris/fileformats/ff.py:699: UserWarning: The STASH code m01s03i370 was not found in the STASH to grid type mapping. Picking the P position as the cell type
  'position as the cell type'.format(stash))
/projects/access/apps/pythonlib/iris/1.9.1/lib/python2.7/site-packages/Iris-1.9.1-py2.7-linux-x86_64.egg/iris/fileformats/ff.py:699: UserWarning: The STASH code m01s03i371 was not found in the STASH to grid type mapping. Picking the P position as the cell type
  'position as the cell type'.format(stash))
/projects/access/apps/pythonlib/iris/1.9.1/lib/python2.7/site-packages/Iris-1.9.1-py2.7-linux-x86_64.egg/iris/fileformats/ff.py:707: UserWarning: The stash code m01s26i001 is on a grid 23 which has not been explicitly handled by the fieldsfile loader. Assuming the data is on a P grid.
  subgrid))
/projects/access/apps/pythonlib/iris/1.9.1/lib/python2.7/site-packages/Iris-1.9.1-py2.7-linux-x86_64.egg/iris/fileformats/ff.py:707: UserWarning: The stash code m01s26i002 is on a grid 23 which has not been explicitly handled by the fieldsfile loader. Assuming the data is on a P grid.
  subgrid))
/projects/access/apps/pythonlib/iris/1.9.1/lib/python2.7/site-packages/Iris-1.9.1-py2.7-linux-x86_64.egg/iris/fileformats/ff.py:707: UserWarning: The stash code m01s26i003 is on a grid 23 which has not been explicitly handled by the fieldsfile loader. Assuming the data is on a P grid.
  subgrid))
/projects/access/apps/pythonlib/iris/1.9.1/lib/python2.7/site-packages/Iris-1.9.1-py2.7-linux-x86_64.egg/iris/fileformats/ff.py:707: UserWarning: The stash code m01s26i006 is on a grid 23 which has not been explicitly handled by the fieldsfile loader. Assuming the data is on a P grid.
  subgrid))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/projects/access/apps/pythonlib/iris/1.9.1/lib/python2.7/site-packages/Iris-1.9.1-py2.7-linux-x86_64.egg/iris/__init__.py", line 341, in load_cube
    raise iris.exceptions.ConstraintMismatchError(str(e))
iris.exceptions.ConstraintMismatchError: failed to merge into a single cube.
  cube.cell_methods differ
  cube.shape differs: (144, 192) != (8, 144, 192)
```

**Comment by ajdawson** [comment]
You can load the data into multiple cubes using `iris.load` (as opposed to `iris.load_cube`). If the result is useful as is, then you are done. If not you can investigate what has been loaded and attempt to modify the metadata using a [load time callback](http://scitools.org.uk/iris/docs/latest/iris/iris.html), so that it merges into a single cube.

**Comment by pelson** [comment]
Thanks for the helpful solution @ajdawson.
