### ISSUE TITLE
[Dask] Cannot perform reordered multidim slice of lazy cube

### ISSUE THREAD

**Issue by dkillick** [SciTools/iris#2579]
In cases where a slice of a cube will require transposing the intermediate result (that is, when the requested slice dims are not in the same order as they are on the cube), the following error will occur:

```python
>>> cube = iris.load_cube(iris.sample_data_path('A1B_north_america.nc'))
>>> ht_slice = next(cube.slices(['latitude', 'time']))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/.../git/iris/lib/iris/cube.py", line 3965, in __next__
    cube.transpose(self._mod_requested_dims)
  File "/.../git/iris/lib/iris/cube.py", line 2793, in transpose
    data = dm.core_data().transpose(new_order)
  File "/.../python2.7/site-packages/dask/array/core.py", line 1266, in transpose
    return transpose(self, axes=axes)
  File "/.../python2.7/site-packages/dask/array/core.py", line 2362, in transpose
    if axes:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

This is because `iris.cube._SliceIterator` passes a NumPy array of reordering dims to `cube.transpose`, which dask cannot handle. This case was missed when `cube.transpose` was originally daskified, as was a test for this case that would have picked up on the error.

**Comment by dkillick** [comment]
Closed now #2580 is merged.
