### ISSUE TITLE
Merge Problems

### ISSUE THREAD

**Issue by djkirkham** [SciTools/iris#2761]
There appear to be a problem with the method used by Iris to determine which coordinates to use to construct new dimensions, and the shape of those dimensions, when merging. It looks like the problem stems from the fact that in order to determine if two scalar coordinates A and B can be 'separated' (can appear on separate dimensions in the new cube), Iris constructs, for each point of A, the _set_ of points with it appears on a cube in the list, and likewise for B. It then tries to construct a shape for the new cube based on this idea of separability, which causes problems.

For example, consider four scalar cubes each with scalar coordinates A and B with points taken from the following two lists of points:
```
A = [1, 1, 2, 2]
B = [3, 4, 3, 4]
```
These four cubes can be merged into a single 2 x 2 cubes with coordinates A=[1,2], B=[3,4] on separate dimensions. To determine the new dimensions, Iris constructs the following dictionaries (called 'indexes' in the code):

I<sub>A</sub> = `{ 1: set(3, 4), 2: set(3,4) }`
I<sub>B</sub> = `{ 3: set(1, 2), 4: set(1,2) }`

It then uses the reasoning I outlined above: it compares the sets in I<sub>A</sub>, sees that they are all the same, and determines that A is separable from B. It does the same for I<sub>B</sub>. It later uses this information, together with the size of the sets, when determining the shape of the new cube (2,2).

Now consider six scalar cubes with coordinates based on the following points:
```
A = [1, 2, 1, 2, 1, 2]
B = [3, 4, 4, 4, 4, 3]
C = [5, 6, 7, 5, 6, 7]
```

**Comment by djkirkham** [comment]
Example code:

```
from itertools import imap, repeat

import iris
from iris.coords import AuxCoord
from iris.cube import Cube, CubeList


def make_scalar_coords(name, points):
    return [AuxCoord(point, long_name=name) for point in points]


def make_scalar_cubes(**kwargs):
    # Make a list of scalar cubes with coordinates based on the keyword arguments
    all_scalar_coords = [make_scalar_coords(name, points) 
                         for name, points in kwargs.iteritems()]
    
    cubes = [Cube(0, aux_coords_and_dims=zip(scalar_coords, repeat(None)))
             for scalar_coords in zip(*all_scalar_coords)]
    
    return CubeList(cubes)

a = [5, 5, 6, 6, 7, 7]
b = [1, 2, 1, 2, 1, 2]
c = [3, 4, 4, 4, 4, 3]

cubes = make_scalar_cubes(a=a, b=b, c=c)
cubes.merge_cube()
```
Result:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
...
.../iris/_merge.py in merge(self, unique)
   1213                 stack[nd_index] = data
   1214 
-> 1215             merged_data = biggus.ArrayStack(stack)
   1216             if all_have_data:
   1217                 merged_data = merged_data.masked_array()

.../biggus/_init.py in __init__(self, stack)
   1731         for array in stack.flat:
   1732             if not isinstance(array, Array):
-> 1733                 raise ValueError('sub-array must be subclass of Array')
   1734             if fill_value is not None and not fill_value_ok(array):
   1735                 fill_value = None

ValueError: sub-array must be subclass of Array
```

**Comment by dkillick** [comment]
The cheapest fix (though I'm not necessarily advocating it) would be to capture the above error and re-raise it as a `MergeError`.

**Comment by rcomer** [comment]
This came up again for me today.  This time on load.

> The cheapest fix (though I'm not necessarily advocating it) would be to capture the above error and re-raise it as a MergeError.

The merge codebase is somewhat beyond me, so I don't know how realistic this suggestion is: could the error be caught and then trigger a fall back approach of putting A, B and C on one anonymous dimension?  It wouldn't be ideal, but it would allow the user to continue with their analysis.

**Comment by pelson** [comment]
I've just seen this in the wild. Ouch.
Thanks for making such an easy case to reproduce Dan.

With Iris 2 and dask, the exception looks like:

```
Traceback (most recent call last):
  File "simple_bug.py", line 27, in <module>
    print(cubes.merge_cube())
  File "/net/home/h02/itpe/dev/scitools/iris/lib/iris/cube.py", line 380, in merge_cube
    merged_cube, = proto_cube.merge()
  File "/net/home/h02/itpe/dev/scitools/iris/lib/iris/_merge.py", line 1236, in merge
    merged_data = multidim_lazy_stack(stack)
  File "/net/home/h02/itpe/dev/scitools/iris/lib/iris/_lazy_data.py", line 159, in multidim_lazy_stack
    for subarray in stack])
  File "/net/home/h02/itpe/dev/scitools/iris/lib/iris/_lazy_data.py", line 159, in <listcomp>
    for subarray in stack])
  File "/net/home/h02/itpe/dev/scitools/iris/lib/iris/_lazy_data.py", line 155, in multidim_lazy_stack
    result = da.stack(list(stack))
  File "/scratch/itpe/conda/envs/dev-iris-2/lib/python3.6/site-packages/dask/array/core.py", line 3297, in stack
    if not all(x.shape == seq[0].shape for x in seq):
  File "/scratch/itpe/conda/envs/dev-iris-2/lib/python3.6/site-packages/dask/array/core.py", line 3297, in <genexpr>
    if not all(x.shape == seq[0].shape for x in seq):
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by bjlittle** [comment]
Thinking about this a little.. the case that breaks down appears be solveable when the separable test maintains each of the individual values in the proposed dimension coordinate relationship i.e.

I<sub>A,B</sub> = `{ 1: [3, 4, 4], 2: [3, 4, 4] }`
I<sub>B,A</sub> = `{ 3: [1, 2], 4: [1, 1, 2, 2] }`

Clearly this fails, and quit right too! This is what we want BTW, as Iris gets this wrong currently, and that's the crux of this particular issue. 

However,

I<sub>A,C</sub> = `{ 1: [5, 6, 7], 2: [5, 6, 7] }`
I<sub>C,A</sub> = `{ 5: [1, 2], 6: [1, 2], 7: [1, 2] }`

most certainly works (that's very good news indeed). And for completeness, 

I<sub>B,C</sub> = `{ 3: [5, 7], 4: [5, 6, 7] }`
I<sub>C,B</sub> = `{ 5: [3, 4], 6: [4, 4], 7: [3, 4] }`

also fails, which is what we want. Interesting, huh?

There may be some side-effect in this subtle change of approach, but it seems to have enough potential to warrant me applying this to `merge` to see how she flies...

**Comment by rcomer** [comment]
This one is difficult to work around, so I would very much like to see a fix for it.

**Comment by trexfeathers** [comment]
@SciTools/peloton 👁️

**Comment by HGWright** [comment]
From @SciTools/peloton @rcomer @djkirkham Is this still a problem for your work, and hard to workaround?

**Comment by rcomer** [comment]
This has only come up occasionally for me, but is difficult to work around when it does.

NB: @djkirkham was working in support - he created this minimal issue based on my emailed more complicated report.
