### ISSUE TITLE
Time units of 'months' or 'years' cause print() to ValueError

### ISSUE THREAD

**Issue by samizdis** [SciTools/iris#2793]
If the units of a time coord are months or years, printing the cube fails with
```
ValueError: units must be one of 'seconds', 'minutes', 'hours' or 'days' (or singular version of these), got 'months'
```

It looks like this was addressed back in Feb (https://groups.google.com/forum/#!topic/scitools-iris/c8B75mRQ7JU), with two identically-named PRs (https://github.com/SciTools/cf_units/pull/72 and https://github.com/SciTools/iris/pull/2354, one of which is merged, but this still breaks in v1.13.0

**Comment by djkirkham** [comment]
Thanks for raising this. We'll need to do a release of cf_units before #2354 can be merged, once that's done this issue will be fixed.

**Comment by rcomer** [comment]
Looks like #2354 fixed the printing of coordinates, but not the printing of a cube with a scalar time coordinate:

```python
import iris

print(iris.__version__)

cube = iris.cube.Cube(1)
cube.add_aux_coord(iris.coords.DimCoord(1, standard_name='time', units='years since 2020-03-23'))

print(cube)
```

```
3.0.1
Traceback (most recent call last):
  File "print_cube_year_coord.py", line 8, in <module>
    print(cube)
  File "[site-packages-path]/iris/cube.py", line 2594, in __str__
    return self.summary()
  File "[site-packages-path]/iris/cube.py", line 2505, in summary
    coord_cell = coord.cell(0)
  File "[site-packages-path]/iris/coords.py", line 1904, in cell
    point = self.units.num2date(point)
  File "[site-packages-path]/cf_units/__init__.py", line 2026, in num2date
    cdf_utime = self.utime()
  File "[site-packages-path]/cf_units/__init__.py", line 1940, in utime
    raise ValueError(emsg.format(interval))
ValueError: Time units with interval of "months", "years" (or singular of these) cannot be processed, got "years".
```
```

**Comment by rcomer** [comment]
https://github.com/SciTools/cf-units/pull/279 may well address this.  I vote we leave this open till that is done.
