### ISSUE TITLE
Example warnings: "default for ma.minimum.reduce will be axis=0"

### ISSUE THREAD

**Issue by pelson** [SciTools/iris#2877]
When running the documentation examples, sometimes warnings such as the following are seen:

```
MaskedArrayFutureWarning: In the future the default for ma.minimum.reduce will be axis=0, not the current None, to match np.minimum.reduce. Explicitly pass 0 or None to silence this warning.
```

Do we need to do something in the iris codebase to prevent this, or do we need to update the example code?

**Comment by rcomer** [comment]
I've just noticed this from my code, and the traceback indicates the problem was in Matplotlib (version 1.5.3).  I think this issue was opened before pinning Iris to that latest Matplotlib version, so may now be fixed?

**Comment by rcomer** [comment]
Full traceback in case it's useful:

```
Traceback (most recent call last):
  File "./../../run_west_african_monsoon.py", line 24, in <module>
    args.hindcastproc, args.newhindcast, args.oldhindcast, args.plotdir)
  File "[path-to-my-module]/wam_hovmoller.py", line 300, in plot_hovmollers
    _plot_mean_and_sd(hovmollers, obs_label, plot_num)
  File "[path-to-my-module]/wam_hovmoller.py", line 293, in _plot_mean_and_sd
    _plot_hovmoller(hov_agg, levels, label)
  File "[path-to-my-module]/wam_hovmoller.py", line 243, in _plot_hovmoller
    colors=colors, extend='max')
  File "[site-packages-path]/iris/quickplot.py", line 187, in contourf
    result = iplt.contourf(cube, *args, **kwargs)
  File "[site-packages-path]/iris/plot.py", line 808, in contourf
    result = _draw_2d_from_points('contourf', None, cube, *args, **kwargs)
  File "[site-packages-path]/iris/plot.py", line 400, in _draw_2d_from_points
    result = draw_method(u, v, data, *args, **kwargs)
  File "[site-packages-path]/matplotlib/pyplot.py", line 2790, in contourf
    ret = ax.contourf(*args, **kwargs)
  File "[site-packages-path]/matplotlib/__init__.py", line 1819, in inner
    return func(ax, *args, **kwargs)
  File "[site-packages-path]/matplotlib/axes/_axes.py", line 5627, in contourf
    return mcontour.QuadContourSet(self, *args, **kwargs)
  File "[site-packages-path]/matplotlib/contour.py", line 1424, in __init__
    ContourSet.__init__(self, ax, *args, **kwargs)
  File "[site-packages-path]/matplotlib/contour.py", line 863, in __init__
    self._process_args(*args, **kwargs)
  File "[site-packages-path]/matplotlib/contour.py", line 1472, in _process_args
    x0 = ma.minimum(x)
  File "[site-packages-path]/numpy/ma/core.py", line 6385, in __call__
    return self.reduce(a)
  File "[site-packages-path]/numpy/ma/core.py", line 6401, in reduce
    MaskedArrayFutureWarning, stacklevel=2)
numpy.ma.core.MaskedArrayFutureWarning: In the future the default for ma.minimum.reduce will be axis=0, not the current None, to match np.minimum.reduce. Explicitly pass 0 or None to silence this warning.
```

**Comment by pelson** [comment]
Thanks @rcomer. Happy to take that one 👍
