### ISSUE TITLE
Problem with netcdftime?

### ISSUE THREAD

**Issue by ehogan** [SciTools/iris#2907]
I found #2322 and @djkirkham reported that the issue was fixed [here](https://github.com/SciTools/iris/issues/2322#issuecomment-337908527) (on [April 3](https://github.com/SciTools/iris/pull/2440); Iris 1.13.0 was [released](https://github.com/SciTools/iris/releases/tag/v1.13.0) on May 17), but I am seeing the same issue when using a time constraint using a clean Conda installation of Iris (following the instructions [here](http://scitools.org.uk/iris/docs/latest/installing.html)):
```
% conda create --name iris-test -c conda-forge iris
[...]
    netcdf4:                       1.3.1-py27_0          conda-forge
[...]
% source activate iris-test
(iris-test) % python
Python 2.7.14 | packaged by conda-forge | (default, Oct  5 2017, 14:19:56) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import iris
>>> print iris.__version__
1.13.0
>>> from iris.time import PartialDateTime
>>> iris.FUTURE.cell_datetime_objects = True
>>> filename = 'aq112a.p51851may.pp'
>>> cube = iris.load_cube(filename, iris.AttributeConstraint(STASH='m01s03i236') & iris.Constraint(time=lambda cell: PartialDateTime(1851, 5) <= cell.point <= PartialDateTime(1851, 6)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/local/ehogan/miniconda/envs/iris-test/lib/python2.7/site-packages/iris/__init__.py", line 371, in load_cube
    cubes = _load_collection(uris, constraints, callback).merged().cubes()
  File "/data/local/ehogan/miniconda/envs/iris-test/lib/python2.7/site-packages/iris/__init__.py", line 311, in _load_collection
    result = iris.cube._CubeFilterCollection.from_cubes(cubes, constraints)
  File "/data/local/ehogan/miniconda/envs/iris-test/lib/python2.7/site-packages/iris/cube.py", line 145, in from_cubes
    collection.add_cube(cube)
  File "/data/local/ehogan/miniconda/envs/iris-test/lib/python2.7/site-packages/iris/cube.py", line 158, in add_cube
    pair.add(cube)
  File "/data/local/ehogan/miniconda/envs/iris-test/lib/python2.7/site-packages/iris/cube.py", line 110, in add
    sub_cube = self.constraint.extract(cube)
  File "/data/local/ehogan/miniconda/envs/iris-test/lib/python2.7/site-packages/iris/_constraints.py", line 151, in extract
    resultant_CIM = self._CIM_extract(cube)
  File "/data/local/ehogan/miniconda/envs/iris-test/lib/python2.7/site-packages/iris/_constraints.py", line 214, in _CIM_extract
    self.rhs._CIM_extract(cube))
  File "/data/local/ehogan/miniconda/envs/iris-test/lib/python2.7/site-packages/iris/_constraints.py", line 175, in _CIM_extract
    resultant_CIM = resultant_CIM & coord_constraint.extract(cube)
  File "/data/local/ehogan/miniconda/envs/iris-test/lib/python2.7/site-packages/iris/_constraints.py", line 290, in extract
    r = np.array([call_func(cell) for cell in coord.cells()])
  File "<stdin>", line 1, in <lambda>
  File "netcdftime/_netcdftime.pyx", line 1307, in netcdftime._netcdftime.datetime.__richcmp__
TypeError: cannot compare netcdftime._netcdftime.Datetime360Day(1851, 5, 16, 0, 0, 0, 0, -1, 136) and PartialDateTime(year=1851, month=6)
```

Note that an installation of Iris using `netcdf4=1.2.4` works fine:
```
% module load scitools/default-current
% python
Python 2.7.12 | Met Office - SciTools | (default, Sep 22 2016, 17:01:57) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import iris
>>> print iris.__version__
1.13.0
>>> from iris.time import PartialDateTime
>>> iris.FUTURE.cell_datetime_objects = True
>>> filename = 'aq112a.p51851may.pp'
>>> cube = iris.load_cube(filename, iris.AttributeConstraint(STASH='m01s03i236') & iris.Constraint(time=lambda cell: PartialDateTime(1851, 5) <= cell.point <= PartialDateTime(1851, 6)))
>>> print cube
air_temperature / (K)               (latitude: 324; longitude: 432)
     Dimension coordinates:
          latitude                           x               -
          longitude                          -               x
     Scalar coordinates:
          forecast_period: 11880.0 hours, bound=(11520.0, 12240.0) hours
          forecast_reference_time: 1850-01-01 00:00:00
          height: 1.5 m
          time: 1851-05-16 00:00:00, bound=(1851-05-01 00:00:00, 1851-06-01 00:00:00)
     Attributes:
          STASH: m01s03i236
          source: Data from Met Office Unified Model
          um_version: 10.7
     Cell methods:
          mean: time (1 hour)
```
Is this expected?

**Comment by djkirkham** [comment]
Thanks for raising this issue.

There's a slight difference between this issue and https://github.com/SciTools/iris/issues/2322. In that issue the comparison was between a `Cell` and a `PartialDateTime`, whereas here the comparison is between a `netcdftime.datetime` (`cell.point`) and a `PartialDateTime`. In the former case we could work around the issue in the `Cell` comparison method, but we can't do that here.

The underlying issue was introduced into the `netcdftime` library some time after v1.2.4. Unfortunately there's nothing we can do until a fix is put into the library.

A workaround is to make sure `PartialDateTime` is always on the left hand side of the comparison, e.g.
```
PartialDateTime(1851, 5) <= cell.point and PartialDateTime(1851, 6) >= cell.point 
```

**Comment by ehogan** [comment]
Awesome, thank you very much! :)

Do you know if / when a fix will be added to the library?

**Comment by djkirkham** [comment]
I reported the issue some time ago, and although it's a simple fix nothing's been done. It's probably worth me putting up a fix myself, but we'd still have to wait for a release of the library, I don't know when that might be done.

**Comment by ehogan** [comment]
Great, thank you for the information! :)
