### ISSUE TITLE
Cell comparison fails with 0-d numpy arrays

### ISSUE THREAD

**Issue by djkirkham** [SciTools/iris#2914]
Cell comparison fails with 0-d numpy arrays, but should probably be supported.
```
>>> from iris.coords import Cell
>>> import numpy as np
>>> b = np.array(1.5)
>>> c = Cell(1.3)
>>> b < c
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/iris/coords.py", line 360, in __gt__
    return self.__common_cmp__(other, operator.gt)
  File ".../lib/iris/coords.py", line 265, in __common_cmp__
    "{}.".format(type(other)))
TypeError: Unexpected type of other <type 'numpy.ndarray'>.
```

**Comment by pelson** [comment]
Thought this should have been fixed by https://github.com/SciTools/iris/pull/1947. Looks like a bug to me.
