### ISSUE TITLE
reading ECMWF grib

### ISSUE THREAD

**Issue by mattchri** [SciTools/iris#2920]
I am trying to open ECMWF grib files in Python by using the iris module and get a strange error.

```python
>>> import iris
>>> fname = '/badc/ecmwf-era-interim/data/sp/fm/1999/01/20/spfm199901200003.grb'
>>> cubes = iris.load(fname)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/group_workspaces/cems2/nceo_generic/users/mchristensen/miniconda2/lib/python2.7/site-packages/iris/__init__.py", line 341, in load
    return _load_collection(uris, constraints, callback).merged().cubes()
  File "/group_workspaces/cems2/nceo_generic/users/mchristensen/miniconda2/lib/python2.7/site-packages/iris/__init__.py", line 311, in _load_collection
    result = iris.cube._CubeFilterCollection.from_cubes(cubes, constraints)
  File "/group_workspaces/cems2/nceo_generic/users/mchristensen/miniconda2/lib/python2.7/site-packages/iris/cube.py", line 144, in from_cubes
    for cube in cubes:
  File "/group_workspaces/cems2/nceo_generic/users/mchristensen/miniconda2/lib/python2.7/site-packages/iris/__init__.py", line 298, in _generate_cubes
    for cube in iris.io.load_files(part_names, callback, constraints):
  File "/group_workspaces/cems2/nceo_generic/users/mchristensen/miniconda2/lib/python2.7/site-packages/iris/io/__init__.py", line 201, in load_files
    for cube in handling_format_spec.handler(fnames, callback):
  File "/group_workspaces/cems2/nceo_generic/users/mchristensen/miniconda2/lib/python2.7/site-packages/iris/fileformats/rules.py", line 1047, in load_cubes
    user_callback_wrapper=loadcubes_user_callback_wrapper):
  File "/group_workspaces/cems2/nceo_generic/users/mchristensen/miniconda2/lib/python2.7/site-packages/iris/fileformats/rules.py", line 960, in _load_pairs_from_fields_and_filenames
    for field, filename in fields_and_filenames:
  File "/group_workspaces/cems2/nceo_generic/users/mchristensen/miniconda2/lib/python2.7/site-packages/iris/fileformats/rules.py", line 1024, in _generate_all_fields_and_filenames
    filename, **loader.field_generator_kwargs):
  File "/group_workspaces/cems2/nceo_generic/users/mchristensen/miniconda2/lib/python2.7/site-packages/iris_grib/__init__.py", line 700, in _load_generate
    message = GribWrapper(message_id, grib_fh=grib_fh)
  File "/group_workspaces/cems2/nceo_generic/users/mchristensen/miniconda2/lib/python2.7/site-packages/iris_grib/__init__.py", line 169, in __init__
    self._confirm_in_scope()
  File "/group_workspaces/cems2/nceo_generic/users/mchristensen/miniconda2/lib/python2.7/site-packages/iris_grib/__init__.py", line 199, in _confirm_in_scope
    if self.alternativeRowScanning == 1:
  File "/group_workspaces/cems2/nceo_generic/users/mchristensen/miniconda2/lib/python2.7/site-packages/iris_grib/__init__.py", line 239, in __getattr__
    raise AttributeError("Cannot find GRIB key %s" % key)
AttributeError: Cannot find GRIB key alternativeRowScanning
```

Any information you may have would be really helpful. I am trying to read divergence of geopotential flux data.

**Comment by dkillick** [comment]
Hi @mattchri – thanks for getting in touch with us about this issue. Technically, it looks like this issue has occurred in the [`iris_grib`](https://github.com/SciTools/iris-grib) module, which provides Iris with its GRIB functionality. This is no problem, I can try and answer the issue here still!

I've taken a look at the `iris_grib` code that raised this error, and it's expecting that all GRIB messages will contain the key `alternativeRowScanning`, which your message does not contain. I've also taken a look at the GRIB manuals produced by the WMO (see the [GRIB documents here](http://www.wmo.int/pages/prog/www/WMOCodes/WMO306_vI2/LatestVERSION/LatestVERSION.html)). Unfortunately there's no direct correlation between the keys provided by the Python grib-api library and the contents of the GRIB manuals, but it does appear that GRIB messages (whose grid definition template describes a representation of the earth) must contain something that describes scanning mode.

On the basis of this I think the GRIB messages you have might be malformed. Are you getting the same behaviour from other datasets from the same source? It might be worth checking with your data provider to see if they can help you out at all with this.

Hope this helps some.

**Comment by pelson** [comment]
Thanks for the detailed answer @dkillick. I hope it helped @mattchri?

I'm going to go ahead and close this issue. Ideally, please ask questions on StackOverflow, and use the issue tracker for reporting bugs (I completely accept that there is a very hazy line between a "bug" and a "question"!). If you believe there is a problem we can fix, then please consider raising a bug at https://github.com/SciTools/iris-grib.

Thanks!
