### ISSUE TITLE
cf_units 1.2.0 breaking tests

### ISSUE THREAD

**Issue by pelson** [SciTools/iris#2935]
Tests like:
```
======================================================================
FAIL: test_diff_wrt_x (iris.tests.test_analysis_calculus.TestCalculusSimple1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/scitools_iris-2.0.0rc1-py2.7.egg/iris/tests/test_analysis_calculus.py", line 292, in test_diff_wrt_x
    self.assertCMLApproxData(t, ('analysis', 'calculus', 'handmade_simple_wrt_x.cml'))
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/scitools_iris-2.0.0rc1-py2.7.egg/iris/tests/__init__.py", line 307, in assertCMLApproxData
    self.assertCML(cubes, reference_filename, checksum=False)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/scitools_iris-2.0.0rc1-py2.7.egg/iris/tests/__init__.py", line 406, in assertCML
    self._check_same(xml, reference_path)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/scitools_iris-2.0.0rc1-py2.7.egg/iris/tests/__init__.py", line 496, in _check_same
    type_comparison_name)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/scitools_iris-2.0.0rc1-py2.7.egg/iris/tests/__init__.py", line 235, in _assert_str_same
    self.fail("%s do not match: %s\n%s" % (type_comparison_name, reference_filename, diff))
AssertionError: CML do not match: /home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/scitools_iris-2.0.0rc1-py2.7.egg/iris/tests/results/analysis/calculus/handmade_simple_wrt_x.cml
--- Reference
+++ Test result
@@ -3 +3 @@
-  <cube dtype="float32" long_name="derivative_of_x_wind_wrt_x" units="0.277777777777778 meter-second^-1">
+  <cube dtype="float32" long_name="derivative_of_x_wind_wrt_x" units="0.277777777777778 m.s-1">
```

Full log: https://travis-ci.org/SciTools/iris/jobs/327615098

**Comment by dkillick** [comment]
Ah, I think this explains the sudden test failures on #2933...

**Comment by dkillick** [comment]
Guess it's [this PR](https://github.com/SciTools/cf_units/pull/79) responsible for these test failures... Time to update a whole load of CML then 😒

**Comment by pelson** [comment]
@dkillick - assigned 😉

**Comment by pelson** [comment]
@dkillick - when done, could you also add a what's new, as this is sure to catch other out.
