### ISSUE TITLE
Unable to load files then using distributed

### ISSUE THREAD

**Issue by jacobtomlinson** [SciTools/iris#2976]
### Versions
Iris: 2.0.0
Dask: 10.17.1
Distributed: 1.21.2

### Issue

I get an error when loading with a distributed dask cluster, but not when I run without.

This works:

```python
import iris
cube = iris.load('/path/to/netcdf_file.nc')
```

This does not

```python
import iris
import dask
import distributed
client = distributed.Client('scheduler ip')
cube = iris.load('/path/to/netcdf_file.nc')
```

The scheduler and workers are running the same environment as the notebook I'm running this from.

### Error

```
distributed.scheduler - ERROR - error from worker tcp://100.96.10.58:37171: No such file or directory
distributed.utils - ERROR - No such file or directory
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/utils.py", line 238, in f
    result[0] = yield make_coro()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/client.py", line 1363, in _gather
    traceback)
  File "/opt/conda/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.6/site-packages/dask/array/core.py", line 74, in getter
    c = a[b]
  File "/opt/conda/lib/python3.6/site-packages/iris/fileformats/netcdf.py", line 391, in __getitem__
    dataset = netCDF4.Dataset(self.path)
  File "netCDF4/_netCDF4.pyx", line 1873, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:13852)
  File "netCDF4/_netCDF4.pyx", line 1579, in netCDF4._netCDF4._ensure_nc_success (netCDF4/_netCDF4.c:12638)
OSError: No such file or directory

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-7-751451431897> in <module>()
----> 1 cube = iris.load(fs[0])

/opt/conda/lib/python3.6/site-packages/iris/__init__.py in load(uris, constraints, callback)
    341 
    342     """
--> 343     return _load_collection(uris, constraints, callback).merged().cubes()
    344 
    345 

/opt/conda/lib/python3.6/site-packages/iris/cube.py in merged(self, unique)
    181         """
    182         return _CubeFilterCollection([pair.merged(unique) for pair in
--> 183                                       self.pairs])
    184 
    185 

/opt/conda/lib/python3.6/site-packages/iris/cube.py in <listcomp>(.0)
    180 
    181         """
--> 182         return _CubeFilterCollection([pair.merged(unique) for pair in
    183                                       self.pairs])
    184 

/opt/conda/lib/python3.6/site-packages/iris/cube.py in merged(self, unique)
    123 
    124         """
--> 125         return _CubeFilter(self.constraint, self.cubes.merge(unique))
    126 
    127 

/opt/conda/lib/python3.6/site-packages/iris/cube.py in merge(self, unique)
    454 
    455             if proto_cube is None:
--> 456                 proto_cube = iris._merge.ProtoCube(cube)
    457                 proto_cubes.append(proto_cube)
    458 

/opt/conda/lib/python3.6/site-packages/iris/_merge.py in __init__(self, cube)
   1096         # Extract the scalar and vector coordinate data and metadata
   1097         # from the cube.
-> 1098         coord_payload = self._extract_coord_payload(cube)
   1099 
   1100         # The coordinate signature defines the scalar and vector

/opt/conda/lib/python3.6/site-packages/iris/_merge.py in _extract_coord_payload(self, cube)
   1673                 # coordinate, it's quicker to roll our own than use
   1674                 # Coord.cell().
-> 1675                 points = coord.points
   1676                 bounds = coord.bounds
   1677                 points_dtype = points.dtype

/opt/conda/lib/python3.6/site-packages/iris/coords.py in _points_getter(self)
    577     def _points_getter(self):
    578         """The coordinate points values as a NumPy array."""
--> 579         return self._points_dm.data.view()
    580 
    581     def _points_setter(self, points):

/opt/conda/lib/python3.6/site-packages/iris/_data_manager.py in data(self)
    214             try:
    215                 # Realise the lazy data.
--> 216                 result = as_concrete_data(self._lazy_array)
    217                 # Assign the realised result.
    218                 self._real_array = result

/opt/conda/lib/python3.6/site-packages/iris/_lazy_data.py in as_concrete_data(data)
    126         # Recorded in https://github.com/dask/dask/issues/2111.
    127         dtype = data.dtype
--> 128         data = np.asanyarray(data.compute())
    129         if isinstance(data, ma.core.MaskedConstant):
    130             data = ma.masked_array(data.data, dtype=dtype, mask=data.mask)

/opt/conda/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    141         dask.base.compute
    142         """
--> 143         (result,) = compute(self, traverse=False, **kwargs)
    144         return result
    145 

/opt/conda/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    390     postcomputes = [a.__dask_postcompute__() if is_dask_collection(a)
    391                     else (None, a) for a in args]
--> 392     results = get(dsk, keys, **kwargs)
    393     results_iter = iter(results)
    394     return tuple(a if f is None else f(next(results_iter), *a)

/opt/conda/lib/python3.6/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, **kwargs)
   2046                 secede()
   2047             try:
-> 2048                 results = self.gather(packed, asynchronous=asynchronous)
   2049             finally:
   2050                 for f in futures.values():

/opt/conda/lib/python3.6/site-packages/distributed/client.py in gather(self, futures, errors, maxsize, direct, asynchronous)
   1483             return self.sync(self._gather, futures, errors=errors,
   1484                              direct=direct, local_worker=local_worker,
-> 1485                              asynchronous=asynchronous)
   1486 
   1487     @gen.coroutine

/opt/conda/lib/python3.6/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    606             return future
    607         else:
--> 608             return sync(self.loop, func, *args, **kwargs)
    609 
    610     def __repr__(self):

/opt/conda/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    252             e.wait(10)
    253     if error[0]:
--> 254         six.reraise(*error[0])
    255     else:
    256         return result[0]

/opt/conda/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

/opt/conda/lib/python3.6/site-packages/distributed/utils.py in f()
    236             yield gen.moment
    237             thread_state.asynchronous = True
--> 238             result[0] = yield make_coro()
    239         except Exception as exc:
    240             logger.exception(exc)

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1053 
   1054                     try:
-> 1055                         value = future.result()
   1056                     except Exception:
   1057                         self.had_exception = True

/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py in result(self, timeout)
    236         if self._exc_info is not None:
    237             try:
--> 238                 raise_exc_info(self._exc_info)
    239             finally:
    240                 self = None

/opt/conda/lib/python3.6/site-packages/tornado/util.py in raise_exc_info(exc_info)

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1061                     if exc_info is not None:
   1062                         try:
-> 1063                             yielded = self.gen.throw(*exc_info)
   1064                         finally:
   1065                             # Break up a reference to itself

/opt/conda/lib/python3.6/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1361                             six.reraise(type(exception),
   1362                                         exception,
-> 1363                                         traceback)
   1364                     if errors == 'skip':
   1365                         bad_keys.add(key)

/opt/conda/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

/opt/conda/lib/python3.6/site-packages/dask/array/core.py in getter()
     72         lock.acquire()
     73     try:
---> 74         c = a[b]
     75         if asarray:
     76             c = np.asarray(c)

/opt/conda/lib/python3.6/site-packages/iris/fileformats/netcdf.py in __getitem__()
    389 
    390     def __getitem__(self, keys):
--> 391         dataset = netCDF4.Dataset(self.path)
    392         try:
    393             variable = dataset.variables[self.variable_name]

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:13852)()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success (netCDF4/_netCDF4.c:12638)()

OSError: No such file or directory
```

**Comment by jacobtomlinson** [comment]
Looks like something had gone wrong with my filesystem mounts and the netCDF file was not accessible on the workers.
