### ISSUE TITLE
Fix unit test

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#2991]
Reference failure
```shell
======================================================================
ERROR: Failure: AttributeError (/home/travis/miniconda/envs/test-environment/lib/libesmf_fullylinked.so: undefined symbol: ESMC_InterfaceIntSet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/scitools_iris-2.1.0.dev0-py2.7.egg/iris/tests/experimental/regrid/test_regrid_conservative_via_esmpy.py", line 38, in <module>
    import ESMF
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/ESMF/__init__.py", line 56, in <module>
    from api.esmpymanager import *
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/ESMF/api/esmpymanager.py", line 11, in <module>
    from ESMF.interface.cbindings import *
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/ESMF/interface/cbindings.py", line 171, in <module>
    _ESMF.ESMC_InterfaceIntSet.restype = ct.c_int
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/travis/miniconda/envs/test-environment/lib/libesmf_fullylinked.so: undefined symbol: ESMC_InterfaceIntSet
```
From travis-ci [log](https://travis-ci.org/SciTools/iris/builds/356169553?utm_source=github_status&utm_medium=notification)

**Comment by pelson** [comment]
@bjlittle - given travis is green, was this fixed?

**Comment by pelson** [comment]
Ping @bjlittle. Feel free to close this if so.
