### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by pelson** [SciTools/iris#3035]
e.g. https://travis-ci.org/SciTools/iris/jobs/386077814:

```
======================================================================
FAIL: test__repr__ (iris.tests.unit.coords.test_CellMeasure.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.1.0.dev0-py3.6.egg/iris/tests/unit/coords/test_CellMeasure.py", line 134, in test__repr__
    self.assertEqual(self.measure.__repr__(), expected)
AssertionError: "CellMeasure(array([10., 12., 16.,  9.]), measure=area, stand[117 chars]y'})" != "CellMeasure(array([ 10.,  12.,  16.,   9.]), measure=area, s[121 chars]y'})"
- CellMeasure(array([10., 12., 16.,  9.]), measure=area, standard_name='cell_area', units=Unit('m^2'), long_name='measured_area', var_name='area', attributes={'notes': '1m accuracy'})
+ CellMeasure(array([ 10.,  12.,  16.,   9.]), measure=area, standard_name='cell_area', units=Unit('m^2'), long_name='measured_area', var_name='area', attributes={'notes': '1m accuracy'})
?                    +     +     +    +
======================================================================
FAIL: test__str__ (iris.tests.unit.coords.test_CellMeasure.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/scitools_iris-2.1.0.dev0-py3.6.egg/iris/tests/unit/coords/test_CellMeasure.py", line 127, in test__str__
    self.assertEqual(self.measure.__str__(), expected)
AssertionError: "CellMeasure(array([10., 12., 16.,  9.]), measure=area, stand[117 chars]y'})" != "CellMeasure(array([ 10.,  12.,  16.,   9.]), measure=area, s[121 chars]y'})"
- CellMeasure(array([10., 12., 16.,  9.]), measure=area, standard_name='cell_area', units=Unit('m^2'), long_name='measured_area', var_name='area', attributes={'notes': '1m accuracy'})
+ CellMeasure(array([ 10.,  12.,  16.,   9.]), measure=area, standard_name='cell_area', units=Unit('m^2'), long_name='measured_area', var_name='area', attributes={'notes': '1m accuracy'})
?                    +     +     +    +
```

cc @dkillick, as this is very close to #2918 - not sure it is related though...

**Comment by pelson** [comment]
I hear from @bjlittle that this test result is intermittent. This is also backed up with the fact that sometimes on master the test fails, but other times (e.g. 3034) it passes. This is really worrying, and points to a test order issue. I'll dig a little.

**Comment by pelson** [comment]
Have been able to reproduce on my mac using:

```
$ python requirements/gen_conda_requirements.py --groups test > conda-requirements.txt 
$ conda create -n iris-minimal --file conda-requirements.txt 
$ nosetests lib/iris/tests/unit/coords/test_CellMeasure.py -sv

```
