### ISSUE TITLE
Iris won't read in old dynamics dump

### ISSUE THREAD

**Issue by nhsavage** [SciTools/iris#3075]
When trying to read in old dynamics start dumps Iris fails. Even if converted to pp the code still fails:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/__init__.py", line 341, in load
    return _load_collection(uris, constraints, callback).merged().cubes()
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/__init__.py", line 311, in _load_collection
    result = iris.cube._CubeFilterCollection.from_cubes(cubes, constraints)
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/cube.py", line 144, in from_cubes
    for cube in cubes:
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/__init__.py", line 298, in _generate_cubes
    for cube in iris.io.load_files(part_names, callback, constraints):
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/io/__init__.py", line 198, in load_files
    constraints):
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/fileformats/rules.py", line 1047, in load_cubes
    user_callback_wrapper=loadcubes_user_callback_wrapper):
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/fileformats/rules.py", line 962, in _load_pairs_from_fields_and_filenames
    cube, factories, references = _make_cube(field, converter)
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/fileformats/rules.py", line 901, in _make_cube
    metadata = converter(field)
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/fileformats/pp_rules.py", line 694, in convert
    dim_coords_and_dims, other_aux_coords_and_dims = _all_other_rules(f)
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/fileformats/pp_rules.py", line 959, in _all_other_rules
    if f.lbproc == 0:
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/fileformats/pp.py", line 1273, in lbproc
    return self._lbproc
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/fileformats/pp.py", line 1159, in __getattr__
    setattr(self, key[1:], value)
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/fileformats/pp.py", line 1278, in lbproc
    value = _LBProc(value)
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/fileformats/pp.py", line 713, in __init__
    raise ValueError('Negative numbers not supported with '
ValueError: Negative numbers not supported with splittable integers object
>>> cubelist=iris.load_cube('cnrmla.dak5c10.pp','surface height')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/__init__.py", line 371, in load_cube
    cubes = _load_collection(uris, constraints, callback).merged().cubes()
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/__init__.py", line 311, in _load_collection
    result = iris.cube._CubeFilterCollection.from_cubes(cubes, constraints)
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/cube.py", line 144, in from_cubes
    for cube in cubes:
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/__init__.py", line 298, in _generate_cubes
    for cube in iris.io.load_files(part_names, callback, constraints):
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/io/__init__.py", line 198, in load_files
    constraints):
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/fileformats/rules.py", line 1047, in load_cubes
    user_callback_wrapper=loadcubes_user_callback_wrapper):
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/fileformats/rules.py", line 962, in _load_pairs_from_fields_and_filenames
    cube, factories, references = _make_cube(field, converter)
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/fileformats/rules.py", line 901, in _make_cube
    metadata = converter(field)
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/fileformats/pp_rules.py", line 694, in convert
    dim_coords_and_dims, other_aux_coords_and_dims = _all_other_rules(f)
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/fileformats/pp_rules.py", line 959, in _all_other_rules
    if f.lbproc == 0:
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/fileformats/pp.py", line 1273, in lbproc
    return self._lbproc
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/fileformats/pp.py", line 1159, in __getattr__
    setattr(self, key[1:], value)
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/fileformats/pp.py", line 1278, in lbproc
    value = _LBProc(value)
  File "/opt/scitools/environments/default/2018_05_03/lib/python2.7/site-packages/iris/fileformats/pp.py", line 713, in __init__
    raise ValueError('Negative numbers not supported with '
ValueError: Negative numbers not supported with splittable integers object
```

**Comment by nhsavage** [comment]
this is probably because the old dynamics dumps contain zero length fields. I will see if I can fix this issue first using a callback
