### ISSUE TITLE
ValueError: differing coordinates (pressure) remaining which cannot be ignored.

### ISSUE THREAD

**Issue by puneet336** [SciTools/iris#3080]
Hi,
I have a python script which fails when I am try to perform Root of sum of squares on 2 iris cubes.
The version of iris - 2.0.0 & i am getting same error with iris v1.13.0 , numpy version - 1.14.0.
machine - centos 7 & python is from the prebuild version of uvcdat 2.4.1 -   https://github.com/CDAT/cdat/wiki . I have unstalled iris on top of prebuilt uvcdat.

Though, the error which i am getting seems similar to the one[ already reported as bug](https://github.com/SciTools/iris/issues/2446 ) . This code used to work fine on my previous machine on iris 1.13.0 version (code attached
[script.py.txt](https://github.com/SciTools/iris/files/2166249/script.py.txt)

).

```
AttributeConstraint({'STASH': 'm01s03i226'})
y_wind / (m s-1)                    (time: 576; pressure: 8; latitude: 357; longitude: 285)
     Dimension coordinates:
          time                           x              -            -               -
          pressure                       -              x            -               -
          latitude                       -              -            x               -
          longitude                      -              -            -               x
     Auxiliary coordinates:
          forecast_period                x              -            -               -
     Scalar coordinates:
          forecast_reference_time: 2018-07-01 00:00:00
     Attributes:
          STASH: m01s15i202
          source: Data from Met Office Unified Model
          um_version: 10.6
Traceback (most recent call last):
  File "script.py", line 88, in <module>
    windspeed = (uwind ** 2 + vwind ** 2) ** 0.5
  File "/usr/local/uvcdat/iris/1.13.0/lib/python2.7/site-packages/iris/cube.py", line 3109, in __add__
    return iris.analysis.maths.add(self, other, ignore=True)
  File "/usr/local/uvcdat/iris/1.13.0/lib/python2.7/site-packages/iris/analysis/maths.py", line 198, in add
    ignore=ignore, in_place=in_place)
  File "/usr/local/uvcdat/iris/1.13.0/lib/python2.7/site-packages/iris/analysis/maths.py", line 281, in _add_subtract_common
    in bad_coord_grps}))
ValueError: This operation cannot be performed as there are differing coordinates (pressure) remaining which cannot be ignored.
```
Though, i am now trying to modify the multiplication logic (line#88) to the one mentioned under [Example 2 ](https://scitools.org.uk/iris/docs/v1.9.1/iris/iris/analysis/maths.html#iris.analysis.maths.multiply) at - 

Please let me know if i can provide more data on this issue.

**Comment by puneet336** [comment]
@rcomer , thanks for the reply,
I tried comparing the output  of runs on both system (they have shared storage - hence no difference in input file/code). 

Output from new system(/machine) - 
```
user1@server2:~/TEST> AttributeConstraint({'STASH': 'm01s03i226'})
y_wind / (m s-1)                    (time: 576; pressure: 8; latitude: 357; longitude: 285)
     Dimension coordinates:
          time                           x              -            -               -
          pressure                       -              x            -               -
          latitude                       -              -            x               -
          longitude                      -              -            -               x
     Auxiliary coordinates:
          forecast_period                x              -            -               -
     Scalar coordinates:
          forecast_reference_time: 2018-07-01 00:00:00
     Attributes:
          STASH: m01s15i202
          source: Data from Met Office Unified Model
          um_version: 10.6
standard_name difference: 'x_wind' vs 'y_wind'
coord_system difference: <bound method Cube.coord_system of <iris 'Cube' of x_wind / (m s-1) (latitude: 12; longitude: 10)>> vs <bound method Cube.coord_system of <iris 'Cube' of y_wind / (m s-1) (pressure: 1; latitude: 12; longitude: 285)>>
Traceback (most recent call last):
  File "poststamp_final_oper_1.5m_wind_space.py", line 103, in <module>
    coord_diffs(uwind,vwind)
  File "/home/user1/TEST/coord_comparison.py", line 12, in coord_diffs
    if getattr(coord1, attr) != getattr(coord2, attr):
AttributeError: 'Cube' object has no attribute 'circular'
```

Here is the output from old machine - 
```
user1@server1:~/TEST> /home/apps/SiteSoftwares/gnu/PYTHONPACKAGES/2.7.9/ucs4/gnu/4.8.5/MATPLOTLIB/2.2.2/lib64/python2.7/site-packages/matplotlib-2.2.2-py2.7-linux-x86_64.egg/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: The mpl_toolkits.axes_grid module was deprecated in version 2.1. Use mpl_toolkits.axes_grid1 and mpl_toolkits.axisartist provies the same functionality instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
AttributeConstraint({'STASH': 'm01s03i226'})
y_wind / (m s-1)                    (time: 576; latitude: 357; longitude: 285)
     Dimension coordinates:
          time                           x              -               -
          latitude                       -              x               -
          longitude                      -              -               x
     Auxiliary coordinates:
          forecast_period                x              -               -
     Scalar coordinates:
          forecast_reference_time: 2018-07-01 00:00:00
          height: 10.0 m
     Attributes:
          STASH: m01s03i226
          source: Data from Met Office Unified Model
          um_version: 10.6
standard_name difference: 'x_wind' vs 'y_wind'
coord_system difference: <bound method Cube.coord_system of <iris 'Cube' of x_wind / (m s-1) (latitude: 12; longitude: 10)>> vs <bound method Cube.coord_system of <iris 'Cube' of y_wind / (m s-1) (latitude: 12; longitude: 10)>>
Traceback (most recent call last):
  File "poststamp_final_oper_1.5m_wind_space.py", line 103, in <module>
    coord_diffs(uwind,vwind)
  File "/home/user1/TEST/coord_comparison.py", line 12, in coord_diffs
    if getattr(coord1, attr) != getattr(coord2, attr):
AttributeError: 'Cube' object has no attribute 'circular'
```
Still not sure why there is a difference in vwind cube, despite the input data source being same!!

**Comment by rcomer** [comment]
Your STASHConstraint does not seem to be working: you request STASH 3226 but get STASH 15202 (on the new system).  I think you need to look at how you set this up.  I’m not that familiar with AttributeConstraints but I think you can/should use your `varSTASH` directly, rather than creating another constraint from it.

I wonder if the difference between the systems is that you are relying on the order of the cubelist (i.e. to get the `ywind` you index at `[20]`).  Possibly the loaded order is different between the two systems, but I’m only speculating.

**Comment by rcomer** [comment]
Hi @puneet336, since it's been a while I'm going to assume you got this sorted in your code.  So I'll close this issue now.  Closing it shouldn't stop you making further comments if you want/need to though.
