### ISSUE TITLE
Error loading ancillary file with 2.2.0

### ISSUE THREAD

**Issue by MartinDix** [SciTools/iris#3225]
With 2.1.0, there's no problem with non-time varying ancillary files. E.g.
```
>>> c = iris.load_cube('/PATH/umdir/ancil/atmos/n216e/land_sea_mask/igbp/v4/qrparm.mask')
>>> print(c)
land_binary_mask / (1)              (latitude: 324; longitude: 432)
     Dimension coordinates:
          latitude                           x               -
          longitude                          -               x
     Attributes:
          STASH: m01s00i030
          source: Data from Met Office Unified Model
          um_version: 9.2
```

However with 2.2.0 it seems to be trying to create a time axis and is upset by the year 0.
```
>>> c = iris.load_cube('/PATH/umdir/ancil/atmos/n216e/land_sea_mask/igbp/v4/qrparm.mask')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/PATH/lib/python3.6/site-packages/iris/__init__.py", line 373, in load_cube
    cubes = _load_collection(uris, constraints, callback)
  File "/PATH/lib/python3.6/site-packages/iris/__init__.py", line 313, in _load_collection
    result = iris.cube._CubeFilterCollection.from_cubes(cubes, constraints)
  File "/PATH/lib/python3.6/site-packages/iris/cube.py", line 145, in from_cubes
    for cube in cubes:
  File "/PATH/lib/python3.6/site-packages/iris/__init__.py", line 300, in _generate_cubes
    for cube in iris.io.load_files(part_names, callback, constraints):
  File "/PATH/lib/python3.6/site-packages/iris/io/__init__.py", line 207, in load_files
    constraints):
  File "/PATH/lib/python3.6/site-packages/iris/fileformats/rules.py", line 429, in load_cubes
    user_callback_wrapper=loadcubes_user_callback_wrapper):
  File "/PATH/lib/python3.6/site-packages/iris/fileformats/rules.py", line 350, in _load_pairs_from_fields_and_filenames
    cube, factories, references = _make_cube(field, converter)
  File "/PATH/lib/python3.6/site-packages/iris/fileformats/rules.py", line 293, in _make_cube
    metadata = converter(field)
  File "/PATH/lib/python3.6/site-packages/iris/fileformats/pp_load_rules.py", line 665, in convert
    t1=f.t1, t2=f.t2, lbft=f.lbft)
  File "/PATH/lib/python3.6/site-packages/iris/fileformats/pp_load_rules.py", line 511, in _convert_time_coords
    t1_epoch_hours = date2hours(t1)
  File "/PATH/lib/python3.6/site-packages/iris/fileformats/pp_load_rules.py", line 489, in date2hours
    epoch_hours = np.float_(epoch_hours_unit.date2num(t))
  File "/PATH/lib/python3.6/site-packages/cf_units/__init__.py", line 1947, in date2num
    return cdf_utime.date2num(date)
  File "cftime/_cftime.pyx", line 766, in cftime._cftime.utime.date2num
  File "cftime/_cftime.pyx", line 413, in cftime._cftime.JulianDayFromDate
  File "cftime/_cftime.pyx", line 1818, in cftime._cftime._IntJulianDayFromDate
ValueError: date 0000-00-00 does not exist in the standard calendar
```

**Comment by tv3141** [comment]
This looks like the errors caused by `cftime 1.0.2.1` https://github.com/SciTools/iris/pull/3215.

**Comment by bjlittle** [comment]
@MartinDix Thanks for raising this issue. Our `travis-ci` tests were failing due to a change in `cftime` from `1.0.1` to `1.0.2.1`.

For the moment, pin `cftime` back to version `1.0.1` and let me know if that fixes your issue.

In the meantime, I'll investigate the root of the problem with `cftime` version `1.0.2.1` and `iris`.

Is that okay for now?

**Comment by MartinDix** [comment]
Going back to cftime 1.0.0 fixes it.

Thanks

**Comment by bjlittle** [comment]
@MartinDix good to hear that you're now unblocked.

We've temporarily pinned `cftime` for `iris` on `conda-forge` to circumvent this issue until we source the root problem and put up a fix.

Thanks

**Comment by SimonTett** [comment]
Just came across this bug. Unistalled iris then reinstalled it -- it still wanted to install cftime=1.0.3.4. SO I manually installed cftime=1.0.1. I think the bug is because t=0 is standard for constant time ancillary files (perhaps only for HadCM3). A fix might be:
        try:
            epoch_hours = np.float_(epoch_hours_unit.date2num(t))
        except ValueError:
            epoch_hours = np.float_(epoch_hours_unit.date2num('1-1-1'))
