### ISSUE TITLE
Don't nest compute calls

### ISSUE THREAD

**Issue by DPeterK** [SciTools/iris#3237]
In some cases Iris is nesting a compute call within a compute call. This has the undesirable behaviour of generating a loop that increments the total number of threads being used by the realisation operation, which can cause various problems, particularly when running on a cluster:

*  in the less serious, running in parallel on the cluster takes a lot longer than running synchronously on the cluster (if you interrupt the job it looks like the majority of the time is taken up switching threads)
* in the more serious, the maximum number of allowed threads is hit and the job fails.

This is happening in a case where a cube loaded from a PP file with `lbpack=2` (packed on masked land/sea points) is realised. In this case compute is called twice, one call nested inside the other, for a single PP field - the original call to realise the field's data and the nested call to realise the attached land/sea mask that comes from a separate PP field.

Here's the full stacktrace:
```python
cube.data
```
```python-traceback
Traceback (most recent call last):
  File "/.../create_jules_ic_v2.py", line 279, in <module>
    main()                           
  File "/.../create_jules_ic_v2.py", line 274, in main
    nameoffile=create_jules_ic(Ddate,INDIR,UM_FILE_IN,OUTDIR)              
  File "/.../create_jules_ic_v2.py", line 152, in create_jules_ic
    print(type(cube_vegfrac.data <=0.0001))  
  File "/.../python2.7/site-packages/iris/cube.py", line 1644, in data
    return self._data_manager.data
  File "/.../python2.7/site-packages/iris/_data_manager.py", line 216, in data
    result = as_concrete_data(self._lazy_array)
  File "/.../python2.7/site-packages/iris/_lazy_data.py", line 128, in as_concrete_data
    data = np.asanyarray(data.compute())
  File "/.../python2.7/site-packages/dask/base.py", line 143, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/.../python2.7/site-packages/dask/base.py", line 392, in compute
    results = get(dsk, keys, **kwargs)
  File "/.../python2.7/site-packages/dask/threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "/.../python2.7/site-packages/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/.../python2.7/site-packages/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/.../python2.7/site-packages/dask/local.py", line 270, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/.../python2.7/site-packages/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/.../python2.7/site-packages/dask/array/core.py", line 74, in getter
    c = a[b]
  File "/.../python2.7/site-packages/iris/fileformats/pp.py", line 647, in __getitem__
    self.mdi, self.mask)
  File "/.../python2.7/site-packages/iris/fileformats/pp.py", line 770, in _data_bytes_to_shaped_array
    land_mask = mask.data.astype(np.bool)
  File "/.../python2.7/site-packages/iris/fileformats/pp.py", line 1033, in data
    self._data = as_concrete_data(self._data)
  File "/.../python2.7/site-packages/iris/_lazy_data.py", line 128, in as_concrete_data
    data = np.asanyarray(data.compute())
  File "/.../python2.7/site-packages/dask/base.py", line 143, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/.../python2.7/site-packages/dask/base.py", line 392, in compute
    results = get(dsk, keys, **kwargs)
  File "/.../python2.7/site-packages/dask/threaded.py", line 70, in get
    pool = ThreadPool(num_workers)
  File "/.../python2.7/multiprocessing/pool.py", line 727, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/.../python2.7/multiprocessing/pool.py", line 159, in __init__
    self._repopulate_pool()
  File "/.../python2.7/multiprocessing/pool.py", line 223, in _repopulate_pool
    w.start()
  File "/.../python2.7/multiprocessing/dummy/__init__.py", line 75, in start
    threading.Thread.start(self)
  File "/.../python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
```

To fix this we can make sure that the original field and the land/sea mask are realised together and not separately. Note that there might be other cases where such nested compute calls might be possible within Iris.

Originally raised as https://github.com/dask/dask/issues/4240, but re-raised here as it's now clear that the origin of the problem is in Iris.

**Comment by bjlittle** [comment]
Closed by https://github.com/SciTools/iris/pull/3255
