### ISSUE TITLE
IRIS can not load when installed using Conda

### ISSUE THREAD

**Issue by elkelke** [SciTools/iris#3268]
I just made a clean environment using miniconda
```
conda create -n sci python=3
source activate sci
conda install -c conda-forge nco
conda install -c anaconda scipy
conda install spyder
conda install -c conda-forge iris
```
but when I run `import iris` I get the following error:

```
import iris
Traceback (most recent call last):

  File "<ipython-input-2-089b5db944e7>", line 1, in <module>
    import iris

  File "/Users/elke/miniconda3/envs/sci/lib/python3.7/site-packages/iris/__init__.py", line 113, in <module>
    import iris.fileformats

  File "/Users/elke/miniconda3/envs/sci/lib/python3.7/site-packages/iris/fileformats/__init__.py", line 31, in <module>
    from . import netcdf

  File "/Users/elke/miniconda3/envs/sci/lib/python3.7/site-packages/iris/fileformats/netcdf.py", line 41, in <module>
    import netCDF4

  File "/Users/elke/miniconda3/envs/sci/lib/python3.7/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *

ImportError: dlopen(/Users/elke/miniconda3/envs/sci/lib/python3.7/site-packages/netCDF4/_netCDF4.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libssl.1.0.0.dylib
  Referenced from: /Users/elke/miniconda3/envs/sci/lib/libssh2.1.dylib
  Reason: image not found
```

I tried to make a system link `ln -s ~/miniconda3/envs/sci/lib/libssl.1.1.dylib ~/miniconda3/envs/sci/lib/libssl.1.0.0.dylib` which resulted in a similar error:

```
import iris
Traceback (most recent call last):

  File "<ipython-input-3-089b5db944e7>", line 1, in <module>
    import iris

  File "/Users/elke/miniconda3/envs/sci/lib/python3.7/site-packages/iris/__init__.py", line 113, in <module>
    import iris.fileformats

  File "/Users/elke/miniconda3/envs/sci/lib/python3.7/site-packages/iris/fileformats/__init__.py", line 31, in <module>
    from . import netcdf

  File "/Users/elke/miniconda3/envs/sci/lib/python3.7/site-packages/iris/fileformats/netcdf.py", line 41, in <module>
    import netCDF4

  File "/Users/elke/miniconda3/envs/sci/lib/python3.7/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *

ImportError: dlopen(/Users/elke/miniconda3/envs/sci/lib/python3.7/site-packages/netCDF4/_netCDF4.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /Users/elke/miniconda3/envs/sci/lib/libssh2.1.dylib
  Reason: image not found
```

So I made another system link `ln -s ~/miniconda3/envs/sci/lib/libcrypto.1.1.dylib ~/miniconda3/envs/sci/lib/libcrypto.1.0.0.dylib` thinking I was on the correct path. However, now I have this error:
```
import iris
Traceback (most recent call last):

  File "<ipython-input-5-089b5db944e7>", line 1, in <module>
    import iris

  File "/Users/elke/miniconda3/envs/sci/lib/python3.7/site-packages/iris/__init__.py", line 113, in <module>
    import iris.fileformats

  File "/Users/elke/miniconda3/envs/sci/lib/python3.7/site-packages/iris/fileformats/__init__.py", line 31, in <module>
    from . import netcdf

  File "/Users/elke/miniconda3/envs/sci/lib/python3.7/site-packages/iris/fileformats/netcdf.py", line 41, in <module>
    import netCDF4

  File "/Users/elke/miniconda3/envs/sci/lib/python3.7/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *

ImportError: dlopen(/Users/elke/miniconda3/envs/sci/lib/python3.7/site-packages/netCDF4/_netCDF4.cpython-37m-darwin.so, 2): Symbol not found: _EVP_CIPHER_CTX_cleanup
  Referenced from: /Users/elke/miniconda3/envs/sci/lib/libssh2.1.dylib
  Expected in: /Users/elke/miniconda3/envs/sci/lib/libcrypto.1.1.dylib
 in /Users/elke/miniconda3/envs/sci/lib/libssh2.1.dylib
```

If someone can explain the last error and/or has a fix for this problem please let me know!

**Comment by DPeterK** [comment]
I think installing `scipy` from `anaconda` might be causing this, as you're installing it from a different channel to everything else. Different channels have different approaches for building things, which can cause odd issues like missing linking libraries. You also shouldn't need to explicitly install scipy (unless for some reason you need a particular build of scipy), as Iris depends on NumPy which depends on scipy, so scipy will get installed when you install Iris.

I was able to make a working conda env containing the libraries you need by running the following:

```bash
conda create -n sci -c conda-forge nco iris
source activate sci
conda install spyder
```

**Comment by QuLogic** [comment]
NumPy for sure does not depend on scipy, but Iris does.

**Comment by ocefpaf** [comment]
> I was able to make a working conda env containing the libraries you need by running the following

Installing everything in a single command helps conda's solver to avoid installing packages that are not compatible with each other. Note that, if you are using `conda >4.6.1`, you can also use a `.condarc` like this one to help:

```
channel_priority: strict
channels:
  - conda-forge
  - defaults

create_default_packages:
  - blas=*=openblas
```

The channel order and the strict priority will ensure that your packages are downloaded from `conda-forge` unless they exist only on `defaults`. This will increase the stability of your envs when updating packages or installing with multiple commands like you did there.

**Comment by pelson** [comment]
Some great help provided here, thanks all. This is likely to be resolved by the last suggestion, so closing this out.

Feel free to re-open if this is something that can be fixed in Iris itself, but most likely this is an issue for https://github.com/conda-forge/iris-feedstock (feel free to cross link any issues).

Thanks all!
