### ISSUE TITLE
can't import iris (cf_units related)

### ISSUE THREAD

**Issue by forkozi** [SciTools/iris#3270]
I'm new to iris.  Great package, but I can't import it!  I'm using Python 3.6, 64-bit, in Microsoft Visual Studio.

The conda-forge channel was used to install iris, but I get the following error when I try to import iris.

I see that the error references cf_units, but I've seen in other posts that iris doesn't use that anymore?

Thanks,
Nick

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\nickf\AppData\Local\conda\conda\envs\paper3\lib\site-packages\iris\__init__.py", line 110, in <module>
    import iris.cube
  File "C:\Users\nickf\AppData\Local\conda\conda\envs\paper3\lib\site-packages\iris\cube.py", line 41, in <module>
    from iris._cube_coord_common import CFVariableMixin
  File "C:\Users\nickf\AppData\Local\conda\conda\envs\paper3\lib\site-packages\iris\_cube_coord_common.py", line 26, in <module>
    import cf_units
  File "C:\Users\nickf\AppData\Local\conda\conda\envs\paper3\lib\site-packages\cf_units\__init__.py", line 44, in <module>
    from cf_units import _udunits2 as _ud
ImportError: DLL load failed: The specified module could not be found.
```

Here's my package list...

```
# Name                    Version                   Build  Channel
antlr-python-runtime      4.7.2                 py36_1000    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
basemap                   1.2.0           py36h6c86909_1000    conda-forge
blas                      1.0                         mkl
bokeh                     1.0.4                 py36_1000    conda-forge
boost-cpp                 1.68.0            h6a4c333_1000    conda-forge
bzip2                     1.0.6             hfa6e2cd_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cartopy                   0.17.0          py36hdc29d4d_1000    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cf-units                  2.1.1           py36h452e1ab_1000    conda-forge
cf_units                  2.0.1           py36h452e1ab_1002    conda-forge
cffi                      1.12.1           py36hfa6e2cd_0    conda-forge
cftime                    1.0.3.4         py36h452e1ab_1000    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               0.7.0                      py_0    conda-forge
cryptography              2.5              py36h7a1dbc1_0
curl                      7.63.0            h2a8f88b_1000
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.9.0.1         py36hfa6e2cd_1001    conda-forge
dask                      1.1.1                      py_0    conda-forge
dask-core                 1.1.1                      py_0    conda-forge
decorator                 4.3.2                      py_0    conda-forge
distributed               1.25.3                   py36_0    conda-forge
expat                     2.2.5             he025d50_1002    conda-forge
freetype                  2.9.1             h5db478b_1005    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
gdal                      2.2.2            py36hcebd033_1
geos                      3.6.2             he025d50_1004    conda-forge
geotiff                   1.4.2             h0d924fb_1005    conda-forge
gettext                   0.19.8.1          hb01d8f6_1001    conda-forge
glib                      2.58.2            hc0c2ac7_1001    conda-forge
hdf4                      4.2.13            hf8e6fe8_1002    conda-forge
hdf5                      1.10.2               he51fdeb_2    conda-forge
heapdict                  1.0.0                 py36_1000    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                   py36_1000    conda-forge
imageio                   2.5.0                    py36_0    conda-forge
intel-openmp              2019.1                      144
iris                      2.2.0                 py36_1003    conda-forge
iris-sample-data          2.1.0                     <pip>
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
kealib                    1.4.9                h4380d0d_2    conda-forge
kiwisolver                1.0.1           py36he980bc4_1002    conda-forge
krb5                      1.16.1               hc04afaa_7
libcurl                   7.63.0            h2a8f88b_1000
libffi                    3.2.1             h6538335_1005    conda-forge
libgdal                   2.2.4                h47ac16f_8    conda-forge
libiconv                  1.15              hfa6e2cd_1004    conda-forge
libkml                    1.3.0             h4fd0f3b_1009    conda-forge
libnetcdf                 4.6.1              haecec74_200    conda-forge
libpng                    1.6.36            h7602738_1000    conda-forge
libpq                     11.1                 h3235a2c_0
libspatialite             4.3.0a            h582a839_1023    conda-forge
libssh2                   1.8.0                h7a1dbc1_4
libtiff                   4.0.10            h36446d0_1001    conda-forge
libxml2                   2.9.8             h9ce36c8_1005    conda-forge
libxslt                   1.1.32            heafd4d3_1002    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.3.1            py36heafd4d3_0    conda-forge
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
markupsafe                1.1.0           py36hfa6e2cd_1000    conda-forge
matplotlib                3.0.2                 py36_1002    conda-forge
matplotlib-base           3.0.2           py36h3e3dc42_1002    conda-forge
mkl                       2019.1                      144
mkl_fft                   1.0.10                   py36_0    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
msgpack-python            0.6.1            py36he980bc4_0    conda-forge
msys2-conda-epoch         20160418                      1
netcdf4                   1.4.1           py36h8d81a0c_200    conda-forge
networkx                  2.2                        py_1    conda-forge
numpy                     1.15.4           py36h19fb1c0_0
numpy-base                1.15.4           py36hc3f5095_0
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.0             h25a6d84_1003    conda-forge
openssl                   1.1.1a            hfa6e2cd_1000    conda-forge
owslib                    0.17.1                     py_0    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.1           py36h6538335_0    conda-forge
partd                     0.3.9                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.42                 hd6b2f15_0
pillow                    5.4.1           py36h9a613e6_1000    conda-forge
pip                       19.0.2                   py36_0    conda-forge
poppler                   0.67.0               heddaa77_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.1                 h3235a2c_0
proj4                     4.9.3                hfa6e2cd_8    conda-forge
psutil                    5.5.1            py36hfa6e2cd_0    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pyhdf                     0.9.0                    py36_2    conda-forge
pykdtree                  1.3.1           py36h452e1ab_1002    conda-forge
pyke                      1.1.1                 py36_1000    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyproj                    1.9.5.1         py36haf3c679_1006    conda-forge
pyqt                      5.9.2            py36h6538335_2
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
python                    3.6.6                he025d50_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
pywavelets                1.0.1           py36h452e1ab_1000    conda-forge
pyyaml                    3.13            py36hfa6e2cd_1001    conda-forge
qt                        5.9.7            vc14h73c81de_0
requests                  2.21.0                py36_1000    conda-forge
scikit-image              0.14.2           py36h6538335_1    conda-forge
scipy                     1.2.0            py36h29ff71c_0
setuptools                40.8.0                   py36_0    conda-forge
shapely                   1.6.4           py36hc90234e_1000    conda-forge
sip                       4.19.8          py36h6538335_1000    conda-forge
six                       1.12.0                py36_1000    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.26.0            hfa6e2cd_1000    conda-forge
statsmodels               0.9.0           py36hfa6e2cd_1000    conda-forge
tblib                     1.3.2                      py_1    conda-forge
tk                        8.6.9             hfa6e2cd_1000    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1.1           py36hfa6e2cd_1000    conda-forge
udunits2                  2.2.27.6          h252784a_1001    conda-forge
urllib3                   1.24.1                py36_1000    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wheel                     0.33.0                   py36_0    conda-forge
win_inet_pton             1.0.1                 py36_1002    conda-forge
wincertstore              0.2                   py36_1002    conda-forge
xarray                    0.11.3                   py36_0    conda-forge
xerces-c                  3.2.0                h6538335_2    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
yaml                      0.1.7             hfa6e2cd_1001    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11            h2fa13f4_1004    conda-forge
```

**Comment by QuLogic** [comment]
> cf-units                  2.1.1           py36h452e1ab_1000    conda-forge
> cf_units                  2.0.1           py36h452e1ab_1002    conda-forge

This is weird; you should have only one of them installed, I think just `cf-units`. Try removing both and then installing just `cf-units`.

**Comment by forkozi** [comment]
I tried your suggestion, but I'm still getting the same error.

**Comment by forkozi** [comment]
Thank you for your suggestion.  I'm really striking out here.

**Comment by forkozi** [comment]
Thank you for you suggestion.  Unfortunately, I'm still out of luck.  I've tried a number of conda environments with different versions of Python and netcdf4 and iris, but no go.  Do you have any other ideas about what might be causing the error?  I see from the issues that udunits2, cf_units, and cf-units have a bit of a tricky past.  Are there any PATH settings I should be aware of outside of the conda installation?  Thanks again.

**Comment by pelson** [comment]
@forkozi sorry you're having these issues. Could you try creating a clean environment with just cf-units in it to test this out please?

On a linux machine, this looks something like

```
conda create --name clean_cf_units --channel conda-forge cf-units
conda activate clean_cf_units
```

Then test it works with:

```
$ python
>>> import cf_units
```

If this works, the problem is that you have some inconsistencies in your conda environment and the best way to solve this is to re-install some of the packages. If it doesn't work, you've found a (pretty rudimentary) bug with the build of cf-units for Windows.

FWIW, Iris makes use of cf-units (formerly known as cf_units), which itself was formerly part of the core SciTools/Iris codebase. The *actual* functionality has remained remarkably consistent (from a user perspective) throughout.

HTH

**Comment by forkozi** [comment]
@pelson Thanks for the suggestion.  I tried it, and it worked.  I then tried installing iris, and that worked, too.  I don't know what in the world was different that time, but I'm glad I'm up and running.  I guess your message was the Github equivalent of having the teacher come stand by you to get it to work!

**Comment by hafez-ahmad** [comment]
I have it , it worked on cmd but it doesnot work in the spyder ide
 import iris
import iris.plot as iplt
Traceback (most recent call last):

  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\cf_units\__init__.py", line 188, in <module>
    _ud_system = _ud.read_xml()

  File "cf_units/_udunits2.pyx", line 206, in cf_units._udunits2.read_xml

  File "cf_units/_udunits2.pyx", line 116, in cf_units._udunits2.wrap_system

  File "cf_units/_udunits2.pyx", line 196, in cf_units._udunits2._raise_error

UdunitsError: UT_OPEN_DEFAULT: b'No such file or directory'
