### ISSUE TITLE
Bad exception when collapsing with a string coordinate

### ISSUE THREAD

**Issue by pelson** [SciTools/iris#330]
Improve the exception when attempting to collapse a coordinate which is Alphanumeric:

```
import iris
from iris.cube import Cube
from iris.coord_systems import GeogCS
import numpy

cube = Cube(numpy.arange(12, dtype=numpy.int32).reshape((3, 4)))
cube.add_aux_coord(iris.coords.AuxCoord(points=['a', 'b', 'c'], standard_name='realization', units='no_unit'), 0)
cube.add_dim_coord(iris.coords.DimCoord(points=[-1, 0, 1], long_name='index', units='1'), 0)
cube.add_dim_coord(iris.coords.DimCoord(points=[-1, 0, 1, 2], standard_name='height', units='m'), 1)

cube.collapsed('index', iris.analysis.MEAN)
```

Raises the exception:

```
Traceback (most recent call last):
  File "lib/iris/cube.py", line 1848, in collapsed
    collapsed_cube.replace_coord(coord.collapsed(local_dims))
  File "lib/iris/coords.py", line 680, in collapsed
    lower_bound, upper_bound = numpy.min(self.points), numpy.max(self.points)
  File "numpy/core/fromnumeric.py", line 1895, in amin
    return amin(axis, out)
TypeError: cannot perform reduce with flexible type

```

**Comment by ajdawson** [comment]
This is fixed. In fact, the provided example no longer raises an exception at all.

**Comment by pelson** [comment]
Yay! We fixed a bug from 2013! 😆
