### ISSUE TITLE
problem with UDUNITS2 after install

### ISSUE THREAD

**Issue by rsignell-usgs** [SciTools/iris#404]
I just installed Iris for the first time, and upon import:

``` python
import iris

I get:
    ---> 24 import iris.unit
     25 
     26 

/home/rsignell/epd-7.2-1/lib/python2.7/site-packages/iris/unit.py in <module>()
    326             _error_msg = ': "%s"' % _strerror(_errno)
    327             ctypes.set_errno(0)
--> 328         raise OSError('[%s] Failed to open UDUNITS-2 XML unit database %s' % (_status_msg, _error_msg))
    329 
    330 ################################################################################

OSError: [UT_OPEN_DEFAULT] Failed to open UDUNITS-2 XML unit database : "Permission denied"


I did create a site.cfg file

rsignell@gam:/usr/local/python27_epd/lib/python2.7/site-packages/iris$ more etc/site.cfg
[System]
udunits2_path = /home/rsignell/lib/libudunits2.so

but that points to the shared library, not the XML unit database, which is in 

/home/rsignell/share/units/udunits2.xml

Is there a way to tell Iris to look there?

Thanks,
Rich
```

**Comment by hafez-ahmad** [comment]
import iris
import iris.plot as iplt
Traceback (most recent call last):

  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\cf_units\__init__.py", line 188, in <module>
    _ud_system = _ud.read_xml()

  File "cf_units/_udunits2.pyx", line 206, in cf_units._udunits2.read_xml

  File "cf_units/_udunits2.pyx", line 116, in cf_units._udunits2.wrap_system

  File "cf_units/_udunits2.pyx", line 196, in cf_units._udunits2._raise_error

UdunitsError: UT_OPEN_DEFAULT: b'No such file or directory'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\cf_units\__init__.py", line 195, in <module>
    _ud_system = _ud.read_xml(_alt_xml_path.encode())

  File "cf_units/_udunits2.pyx", line 206, in cf_units._udunits2.read_xml

  File "cf_units/_udunits2.pyx", line 116, in cf_units._udunits2.wrap_system

  File "cf_units/_udunits2.pyx", line 196, in cf_units._udunits2._raise_error

UdunitsError: UT_OPEN_ARG: b'Permission denied'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-1-f781a2ec7638>", line 3, in <module>
    import iris

  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\iris\__init__.py", line 110, in <module>
    import iris.cube

  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\iris\cube.py", line 53, in <module>
    from iris._cube_coord_common import CFVariableMixin

  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\iris\_cube_coord_common.py", line 27, in <module>
    import cf_units

  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\cf_units\__init__.py", line 200, in <module>
    % (e.status_msg(), error_msg))

OSError: [UT_OPEN_ARG] Failed to open UDUNITS-2 XML unit database: "b'Permission denied'"


runfile('C:/Users/hafez/personal/python_projects/Oceanography/ESNO.py', wdir='C:/Users/hafez/personal/python_projects/Oceanography')
Traceback (most recent call last):

  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\cf_units\__init__.py", line 188, in <module>
    _ud_system = _ud.read_xml()

  File "cf_units/_udunits2.pyx", line 206, in cf_units._udunits2.read_xml

  File "cf_units/_udunits2.pyx", line 116, in cf_units._udunits2.wrap_system

  File "cf_units/_udunits2.pyx", line 196, in cf_units._udunits2._raise_error

UdunitsError: UT_OPEN_DEFAULT: b'No such file or directory'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\cf_units\__init__.py", line 195, in <module>
    _ud_system = _ud.read_xml(_alt_xml_path.encode())

  File "cf_units/_udunits2.pyx", line 206, in cf_units._udunits2.read_xml

  File "cf_units/_udunits2.pyx", line 116, in cf_units._udunits2.wrap_system

  File "cf_units/_udunits2.pyx", line 196, in cf_units._udunits2._raise_error

UdunitsError: UT_OPEN_ARG: b'Permission denied'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\hafez\personal\python_projects\Oceanography\ESNO.py", line 11, in <module>
    import iris

  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\iris\__init__.py", line 110, in <module>
    import iris.cube

  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\iris\cube.py", line 53, in <module>
    from iris._cube_coord_common import CFVariableMixin

  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\iris\_cube_coord_common.py", line 27, in <module>
    import cf_units

  File "C:\Users\hafez\anaconda3\envs\ocean\lib\site-packages\cf_units\__init__.py", line 200, in <module>
    % (e.status_msg(), error_msg))

OSError: [UT_OPEN_ARG] Failed to open UDUNITS-2 XML unit database: "b'Permission denied'"
