### ISSUE TITLE
CubeList.sort() without key argument return a TypeError

### ISSUE THREAD

**Issue by jodemaey** [SciTools/iris#4075]
## 🐛 Bug Report
Hi there,

Maybe this is well known but I got the following error trying to sort a CubeList without a `key` argument being passed (default behavior).

## How To Reproduce
This doesn't work:
```
In[26]: iris.__version__
Out[26]: '3.0.1'
In[27]: cubes
Out[27]: 
[<iris 'Cube' of surface_temperature / (K) (time: 41; latitude: 125; longitude: 93)>,
<iris 'Cube' of Maximum temperature at 2 metres in the last 6 hours / (K) (time: 41; latitude: 125; longitude: 93)>,
<iris 'Cube' of 2 metre temperature / (K) (time: 41; latitude: 125; longitude: 93)>]
In[28]: cubes.sort()
Traceback (most recent call last):
  File "/home/jodemaey/anaconda3/envs/trygg/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-28-ee4e5154b37b>", line 1, in <module>
    cubes.sort()
TypeError: '<' not supported between instances of 'Cube' and 'Cube'
```
However this works:
```
In[29]: cubes.sort(key=lambda item: item.name())
In[30]: cubes
Out[30]: 
[<iris 'Cube' of 2 metre temperature / (K) (time: 41; latitude: 125; longitude: 93)>,
<iris 'Cube' of Maximum temperature at 2 metres in the last 6 hours / (K) (time: 41; latitude: 125; longitude: 93)>,
<iris 'Cube' of surface_temperature / (K) (time: 41; latitude: 125; longitude: 93)>]
```

## Expected behaviour
I expected CubeList.sort() to sort according to a default strategy (like compare the name), not trying to compare Cube instance with < (which doesn't work).

## Environment 
 - OS & Version: Ubuntu 20.04 LTS
 - Iris Version: 3.0.1 (from conda-forge)

## Additional context
I can't provide the data, but I don't think it is related to the problem.
Sorry if this was already reported (I can't find any previous message related to this).

**Comment by pp-mo** [comment]
I think making this work is simply **_equivalent_** to saying that "cube1 < cube2" has a defined meaning.
That is how Python sorting is supposed to work.

The problem is, I really don't see what that should/could be.
We could just compare names, as suggested, but potentially if those are missing/equal we should then also compare coords, or data sizes or numbers of dimensions.  We could distinguish otherwise-equal cubes by e.g. their attributes or the names/attributes of their coords.  

But I don't think that any of that is a natural + obvious approach.
So actually, _I don't think we **should** define the sorting order for cubes_.
In which case, the fact that this causes an error is not really a problem in itself, but just what you ought to expect.

Sorry if that sounds a bit strong.
What is your experience that highlighted this as a problem ?

**Comment by jodemaey** [comment]
> Sorry if that sounds a bit strong.
Non-taking ;-) .

Actually imho I think you are right. There is so many different things that can be sorted, and therefore a "default strategy" would indeed be useless. But somehow then I would have expected the `key` argument to be mandatory.

In any case, as you said an error is raised, so no big deal.

**Comment by jodemaey** [comment]
Maybe a final comment on this: if you don't make the keyword `key` mandatory, I would suggest that you change the error being displayed to make the user aware of the real problem (instead of the Python error stating that 2 cubes cannot be compared with '<').

**Comment by pp-mo** [comment]
> Non-taking ;-) .

Thanks for your understanding !

**Comment by pp-mo** [comment]
>  if you don't make the keyword key mandatory, I would suggest that you change the error being displayed

I think perhaps you still don't have all the context here ? 
This is all simply **_inherited_** behaviour, provided by the regular `list` object.  
So to improve the user experience, we would have to specialise it for the CubeList class, i.e. we must provide a specific implementation of `__lt__`, **_even_** to just get a different error message. 

Basically, I was reluctant to add to the CubeList class for this purpose, preferring the interpretation that "this is the error you can expect from such a case in Python".  But this is where inheritance can get dangerous !

**Comment by jodemaey** [comment]
Ah ok I get it now. Thanks.
