### ISSUE TITLE
`iris.quickplot` fails due to missing `cftime` attribute with `nc-time-axis<1.3.1`

### ISSUE THREAD

**Issue by valeriupredoi** [SciTools/iris#4350]
Hey guys, here's an example minimal code:
```python
import iris
import iris.quickplot
import matplotlib.pyplot as plt

cube = iris.load_cube("/home/users/valeriu/esmvaltool_var_test/esmvaltool_output/recipe_python_20211001_115743/work/timeseries/script1/tas_amsterdam_CMIP6_BCC-ESM1_Amon_historical_r1i1p1f1_tas_1850-2000.nc")

plot_function = getattr(iris.quickplot, "plot")
fig = plt.figure()
plot_function(cube)
```

this fails with the following trace:
```
(esmvaltool-stock-latest) [valeriu@sci2 esmvaltool_var_test]$ python test_qp.py 
Traceback (most recent call last):
  File "/home/users/valeriu/esmvaltool_var_test/test_qp.py", line 10, in <module>
    plot_function(cube)
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock-latest/lib/python3.9/site-packages/iris/quickplot.py", line 294, in plot
    result = iplt.plot(*args, **kwargs)
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock-latest/lib/python3.9/site-packages/iris/plot.py", line 1564, in plot
    return _draw_1d_from_points("plot", _plot_args, *args, **kwargs)
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock-latest/lib/python3.9/site-packages/iris/plot.py", line 817, in _draw_1d_from_points
    result = draw_method(u, v, *args, **kwargs)
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock-latest/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2840, in plot
    return gca().plot(
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock-latest/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 1743, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock-latest/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 273, in __call__
    yield from self._plot_args(this, kwargs)
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock-latest/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 394, in _plot_args
    self.axes.xaxis.update_units(x)
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock-latest/lib/python3.9/site-packages/matplotlib/axis.py", line 1468, in update_units
    self.set_units(default)
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock-latest/lib/python3.9/site-packages/matplotlib/axis.py", line 1540, in set_units
    self._update_axisinfo()
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock-latest/lib/python3.9/site-packages/matplotlib/axis.py", line 1507, in _update_axisinfo
    self.set_default_intervals()
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock-latest/lib/python3.9/site-packages/matplotlib/axis.py", line 2236, in set_default_intervals
    xmin = self.converter.convert(valmin, self.units, self)
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock-latest/lib/python3.9/site-packages/nc_time_axis/__init__.py", line 288, in convert
    ut = cftime.utime(cls.standard_unit, calendar=first_value.calendar)
AttributeError: module 'cftime' has no attribute 'utime'
```

I have the following usual suspects in my environment:
```
(esmvaltool-stock-latest) [valeriu@sci2 esmvaltool_var_test]$ conda list iris
# packages in environment at /home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock-latest:
#
# Name                    Version                   Build  Channel
iris                      3.1.0            py39hf3d152e_1    conda-forge
(esmvaltool-stock-latest) [valeriu@sci2 esmvaltool_var_test]$ conda list cftime
# packages in environment at /home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock-latest:
#
# Name                    Version                   Build  Channel
cftime                    1.5.1            py39hce5d2b2_0    conda-forge
(esmvaltool-stock-latest) [valeriu@sci2 esmvaltool_var_test]$ conda list matplotlib
# packages in environment at /home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock-latest:
#
# Name                    Version                   Build  Channel
matplotlib                3.3.4            py39hf3d152e_0    conda-forge
matplotlib-base           3.3.4            py39h2fa2bec_0    conda-forge
```

Cheers muchly, let me know if you need any more details on this, and have a good weekend :grinning: :beer:

**Comment by rcomer** [comment]
Hi @valeriupredoi it looks like the offending call is in `nc-time-axis`.  What version of that are you using?

**Comment by valeriupredoi** [comment]
shoot! I totally missed the key offending dep, I got this:
```
(esmvaltool-stock-latest) [valeriu@sci2 esmvaltool_var_test]$ conda list nc-time-axis
# packages in environment at /home/users/valeriu/miniconda3-June2021/envs/esmvaltool-stock-latest:
#
# Name                    Version                   Build  Channel
nc-time-axis              1.2.0              pyhd8ed1ab_2    conda-forge
```

**Comment by rcomer** [comment]
OK, I think if you upgrade `nc-time-axis` to latest 1.3.1, you should be fine 👍

**Comment by valeriupredoi** [comment]
I just did and all works fine :+1: - you guys want to put a pin in your conda file so others don't run into this? The env is lax enough to allow `nc-time-axis` 1.2.0

**Comment by valeriupredoi** [comment]
@rcomer I have removed a pin on `nc-time-axis` that we have introduced in the past due to a bug of the latest (1.3.1) with matplotlib 3.4+ (see https://github.com/ESMValGroup/ESMValTool/pull/2327) - if you guys want to pin the dep in your iris conda spec file that's up to you, but from my point the issue is solved (by you, many thanks for spotting the offending dep, I might have to invest in a pair of glasses :eyeglasses: :grin: )

**Comment by trexfeathers** [comment]
See #4332 .

**Comment by rcomer** [comment]
nc-time-axis is now pinned by #4356 👍
