### ISSUE TITLE
Cubes with string data won't save, or index

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#4412]
## 🐛 Bug Report
Cubes with string data seem to be a bit broken.
You can create one, but either indexing it, or saving to netcdf will fail ...
```
Python 3.8.10 | packaged by conda-forge | (default, Sep 13 2021, 21:46:58) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import iris
>>> iris.__version__
'3.2.dev0'
>>> 
>>> from iris.cube import Cube
>>> cube = Cube(['this', 'that'])
>>> print(cube)
unknown / (unknown)                 (-- : 2)
>>> cube.data
array(['this', 'that'], dtype='<U4')
>>> 
>>> cube[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/h05/itpp/git/iris/iris_main/lib/iris/cube.py", line 2475, in __getitem__
    cube = Cube(data)
  File "/home/h05/itpp/git/iris/iris_main/lib/iris/cube.py", line 894, in __init__
    raise TypeError("Invalid data type: {!r}.".format(data))
TypeError: Invalid data type: 'this'.
>>> 
>>> iris.save(cube, 'tmp.nc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/h05/itpp/git/iris/iris_main/lib/iris/io/__init__.py", line 428, in save
    saver(source, target, **kwargs)
  File "/home/h05/itpp/git/iris/iris_main/lib/iris/fileformats/netcdf.py", line 3200, in save
    sman.write(
  File "/home/h05/itpp/git/iris/iris_main/lib/iris/fileformats/netcdf.py", line 1214, in write
    cf_var_cube = self._create_cf_data_variable(
  File "/home/h05/itpp/git/iris/iris_main/lib/iris/fileformats/netcdf.py", line 2805, in _create_cf_data_variable
    self._lazy_stream_data(
  File "/home/h05/itpp/git/iris/iris_main/lib/iris/fileformats/netcdf.py", line 2927, in _lazy_stream_data
    fill_value_to_check = netCDF4.default_fillvals[dtype.str[1:]]
AttributeError: type object 'str' has no attribute 'str'
>>> 
```

This is showing operation under current main branch (after recent changes to netcdf save),
However, despite much that has changed, these operations did already fail at 3.0, and even 2.4.

Meanwhile, **_coordinates_** with string content do seem to work OK in both these respects.
Maybe just because they are much more commonly used, so they get exercised.
( and even tested, e.g. https://github.com/SciTools/iris/blob/main/lib/iris/tests/unit/coords/test_Coord.py#L279-L302 )

**Comment by wjbenfold** [comment]
Looks related to #4101

**Comment by pelson** [comment]
Hi friends! 😄 

Just to say that this can also be triggered by coordinates of "zero-terminated bytes" (non-unicode strings). Perhaps this is reasonable to not support it, since in the numpy docs they are "not recommended", but would be good to give a decent error...


```
import numpy as np
import iris
import iris.cube
import iris.coords

cube = iris.cube.Cube([1, 2])
bytes_data = np.array(['one', 'two'], dtype='|S5')
cube.add_aux_coord(iris.coords.AuxCoord(bytes_data, long_name='some_bytes'), 0)

iris.save(cube, 'delme.nc')
```

```
site-packages/iris/fileformats/netcdf.py:2894, in Saver._lazy_stream_data(data, fill_value, fill_warn, cf_var)
   2892         fill_value_to_check = fill_value
   2893     else:
-> 2894         fill_value_to_check = netCDF4.default_fillvals[dtype.str[1:]]
   2895 else:
   2896     fill_value_to_check = None

AttributeError: type object 'str' has no attribute 'str'
```

The fix in this case is to use Unicode string ("|U5").

**Comment by pp-mo** [comment]
Still a live issue

**Comment by pp-mo** [comment]
Fixed #7098
