### ISSUE TITLE
time constraint not working with load_cube() but works with .extract()

### ISSUE THREAD

**Issue by am-thyst** [SciTools/iris#4639]
## 🐛 Bug Report
I am loading cubes from .pp files with iris.load_cube(). I'm trying to do like this: `iris.load_cube(filepath,var_name&time_constaint)`, which works for the majority of my files but doesn't work for files with single-level variables ("pa" files).

## How To Reproduce
(I'm unsure whether it's reproducible on other people's data!)
```python
import iris
yr=2017; mth =9; day=22; hr=1
filepath =  "/home/original/"
time_constraint = iris.Constraint(time=iris.time.PartialDateTime(year=yr,month=mth,day=day,hour=hr))
# this line works:
w = iris.load_cube(filepath+'umnsaa_pd*.pp','upward_air_velocity'&time_constraint)
# but this one doesn't:
bld = iris.load_cube(filepath+'umnsaa_pa*.pp','atmosphere_boundary_layer_thickness'&time_constraint)
```
error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./miniconda3/envs/newenv/lib/python3.10/site-packages/iris/__init__.py", line 340, in load_cube
    cubes = _load_collection(uris, constraints, callback).cubes()
  File "./miniconda3/envs/newenv/lib/python3.10/site-packages/iris/__init__.py", line 275, in _load_collection
    result = _CubeFilterCollection.from_cubes(cubes, constraints)
  File "./miniconda3/envs/newenv/lib/python3.10/site-packages/iris/cube.py", line 105, in from_cubes
    collection.add_cube(cube)
  File "./miniconda3/envs/newenv/lib/python3.10/site-packages/iris/cube.py", line 118, in add_cube
    pair.add(cube)
  File "./miniconda3/envs/newenv/lib/python3.10/site-packages/iris/cube.py", line 69, in add
    sub_cube = self.constraint.extract(cube)
  File "./miniconda3/envs/newenv/lib/python3.10/site-packages/iris/_constraints.py", line 165, in extract
    resultant_CIM = self._CIM_extract(cube)
  File "./miniconda3/envs/newenv/lib/python3.10/site-packages/iris/_constraints.py", line 235, in _CIM_extract
    self.lhs._CIM_extract(cube), self.rhs._CIM_extract(cube)
  File "./miniconda3/envs/newenv/lib/python3.10/site-packages/iris/_constraints.py", line 189, in _CIM_extract
    resultant_CIM = resultant_CIM & coord_constraint.extract(cube)
  File "./miniconda3/envs/newenv/lib/python3.10/site-packages/iris/_constraints.py", line 323, in extract
    r = np.array([call_func(cell) for cell in coord.cells()])
  File "./miniconda3/envs/newenv/lib/python3.10/site-packages/iris/_constraints.py", line 323, in <listcomp>
    r = np.array([call_func(cell) for cell in coord.cells()])
  File "./miniconda3/envs/newenv/lib/python3.10/site-packages/iris/_constraints.py", line 306, in call_func
    return c == self._coord_thing
  File "./miniconda3/envs/newenv/lib/python3.10/site-packages/iris/coords.py", line 1359, in __eq__
    return self.contains_point(other)
  File "./miniconda3/envs/newenv/lib/python3.10/site-packages/iris/coords.py", line 1533, in contains_point
    raise TypeError(
TypeError: Cannot determine whether a point lies within a bounded region for datetime-like objects.
```

However, this is my work-around that works:
```
bld = iris.load_cube(filepath+'umnsaa_pa*.pp','atmosphere_boundary_layer_thickness').extract(time_constraint)
<iris 'Cube' of atmosphere_boundary_layer_thickness / (m) (latitude: 550; longitude: 380)>
```

## Environment 
 - OS & Version: CentOS Linux vn. 7 (Core)
 - Iris Version: 3.2.0.post0
</details>

**Comment by wjbenfold** [comment]
Hi @am-thyst, thanks for raising this, it definitely looks odd.

I'm not quite sure why this is only showing up in some files (do both types have bounded times?). I'm also not sure why extract is helping (maybe the name constraint is getting rid of all the bounded times?).

If you wanted to arrange giving us access to files that demonstrate this we can take a look?

fyi, an alternative workaround is to use a lambda instead of PartialDateTime for bounded times, e.g.

`time_constraint = iris.Constraint(time=lambda cell: cell.point.year == 1992 and cell.point.month == 10 and cell.point.day == 1 and cell.point.hour == 2)`
