### ISSUE TITLE
RuntimeError: main thread is not in main loop

### ISSUE THREAD

**Issue by krikru** [SciTools/iris#4879]
## 🐛 Bug Report
When repeatedly loading a netCDF file into an iris CubeList, concatenating it into a cube, and plotting the first time slice of it, the error message
```
RuntimeError: main thread is not in main loop
```
is printed, and the script halts momentarily, before continuing like nothing ever happened.

## How To Reproduce

These steps to reproduce the behavior works for me:

### 1. Download ERA5 data

Download hourly the ERA5 data file for the year 2008, the variable `temperature`, and the pressure levels `1000`, `850`, `700` and `500` using the bash command

```bash
era5cli hourly --startyear 2008 --endyear 2008 --threads 6 --hours 0 6 12 18 --levels 1000 850 700 500 --variables temperature
```

This should give the file `era5_temperature_2008_hourly.nc`.

### 2. Reduce the spatial and temporal resolution of the data and crop

Increase the spatial scale of the data (reduce the resolution) to 2 degrees in both latitude and longitude and crop the latitude to the interval [36, 72] degrees (resulting in 19 unique latitude values) and the longitude to [-10, 32] degrees (22 unique longitude values).

Also aggregate the data for each day by calculating the daily mean (this gives 366 unique time values, one per day).

Give the new, low resolution file the name `low_res_era5_temperature_2008_hourly.nc` and put it in your home folder (`~`). This file should be much smaller than the original one.

### 3. Use iris to trigger the error

Run the following code:

```python


################################################################################
# IMPORTS
################################################################################


import matplotlib.pyplot as plt
import iris
from iris import cube
import iris.quickplot as qplt
from iris.util import equalise_attributes, unify_time_units
from datetime import datetime


################################################################################
# OPTIONS
################################################################################


should_plot_cube = True
file_path = '~/low_res_era5_temperature_2008_hourly.nc'


################################################################################
# FUNCTIONS
################################################################################


def main():
    # Load cube into a CubeList
    cube_list = iris.cube.CubeList([iris.load_cube(file_path)])

    # Concatenate years
    equalise_attributes(cube_list)
    unify_time_units(cube_list)
    print("{}: Before concatenating".format(datetime.now()))
    cube = cube_list.concatenate_cube()  # This is the function call in which the RuntimeError exception is raised
    print("{}: After concatenating".format(datetime.now()))

    # Guess bounds for dimension coords to prevent warning "Coordinate '<name>' is not bounded, guessing contiguous bounds"
    for coord in cube.coords():
        if isinstance(coord, iris.coords.DimCoord) and not coord.has_bounds():
            coord.guess_bounds()

    if should_plot_cube:
        # Plot first time slice of first height level of cube (this needs to be done for the exception to be raised)
        qplt.pcolormesh(cube[0, 0])
        plt.gca().coastlines()
        plt.show()


if __name__ == '__main__':
    while True:
        main()

```

## Expected behaviour

For me, this plots a couple of figures before halting for about half a minute and printing error messages during the call to `concatenate_cube`, then continuing as normal.

## Environment 
 - OS & Version:  Red Hat Enterprise Linux, version 8.5 (Ootpa)
 - Iris Version: 3.2.1
 - IDE: PyCharm 2022.1.3 (Community Edition)
 - mamba 0.22.1
 - conda 4.12.0
 - Python 3.10.5
 - matplotlib-base 3.5.2
 - tk 8.6.12

## Additional context

This is the output I get:

```
2022-07-27 09:03:51.137175: Before concatenating
2022-07-27 09:03:51.149643: After concatenating
2022-07-27 09:03:52.858487: Before concatenating
2022-07-27 09:03:52.868713: After concatenating
2022-07-27 09:03:53.635076: Before concatenating
2022-07-27 09:03:53.646487: After concatenating
2022-07-27 09:03:54.355593: Before concatenating
2022-07-27 09:03:54.367502: After concatenating
2022-07-27 09:03:54.962006: Before concatenating
2022-07-27 09:03:54.974568: After concatenating
2022-07-27 09:03:55.589351: Before concatenating
2022-07-27 09:03:55.600623: After concatenating
2022-07-27 09:03:56.213049: Before concatenating
2022-07-27 09:03:56.224121: After concatenating
2022-07-27 09:03:56.860654: Before concatenating
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x14ed69733880>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 4046, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x14ed69733880>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 4046, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x14ed69733880>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 4046, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x14ed69733880>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 4046, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x14ed69733880>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 4046, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x14ed69733880>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 4046, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x14ed6971c1f0>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x14ed69733880>
Traceback (most recent call last):
  File "/home/sm_krikr/installed_software/mambaforge/envs/mldown/lib/python3.10/tkinter/__init__.py", line 4046, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
2022-07-27 09:05:28.094443: After concatenating
2022-07-27 09:06:31.327562: Before concatenating
2022-07-27 09:06:31.337681: After concatenating
2022-07-27 09:06:32.311972: Before concatenating
2022-07-27 09:06:32.323198: After concatenating
2022-07-27 09:06:33.120662: Before concatenating
2022-07-27 09:06:33.131096: After concatenating
2022-07-27 09:06:33.807861: Before concatenating
2022-07-27 09:06:33.819105: After concatenating
...
```

Some observations:
 - I don't seem to get this error if I set `should_plot_cube` to `False`, so the plotting is involved in triggering this error.
 - ~~I don't get this error if I set `should_import_tkinter` to `True`. I guess this may mean that either iris or matplotlib loads a different version of tkinter?~~ I still get the error if I import `tkinter`; it is just delayed to a later call of `concatenate_cube`. Bummer; I thought I had a workaround.
 - I don't seem to get this error if I load the original netCDF file instead of the one with reduced resolution and spatial extension.
 - If I run `main()` in a loop it executes fine a few times after the first execution, but eventually triggers the same error (although it might be for another netCDF file).

**Comment by trexfeathers** [comment]
Thanks for getting in touch @krikru. We agree this is likely a plotting issue, and probably resides within Matplotlib. Do you get the same error if you use the `QtAgg` Matplotlib backend?

```
import matplotlib
matplotlib.use("QtAgg")
```

Failing that: `Qt5Agg` instead?

**Comment by krikru** [comment]
Hi @trexfeathers,

Thanks for your response. Of course, now I can't reproduce the error, even without changing my code, so it seems like it occurs very sporadically. This may have something to do with the fact that I am running the scipt from a shared login node on a super computer, and that other people may or may not have been using the same node at the same time. I'm also trying to run the code from a compute node in the same computer cluster (which should be exclusively reserved for to me) but I can't seem to reproduce the error there either (and there the plot window seem to be much slower over all for some reason).

If the error ever re-appears, I will try using QtAgg or Qt5Agg and see if it helps. Although, at this point, I can't be sure whether anything I try _actually_ works or whether it just seems to work and will stop working later (like I thought that importing tkinter worked, which it turned out later that it didn't).
