### ISSUE TITLE
Failure to build CF Standard Names with setup.py std_names

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#4951]
## 🐛 Bug Report
Since the introduction of #4903 we are now are unable to successfully perform the commands:
 - `python setup.py develop`
 - `python setup.py std_names`

Note that, 
 - `pip install --editable .` does work and successfully builds the `iris.std_names`
 - The `iris.std_names` are successfully built when performing `python setup.py build` or `python -m build --wheel`

These failures are due to the `editable_mode` attribute being unavailable from `setuptools` commands or custom commands.

## How To Reproduce
Steps to reproduce the behaviour:

<details><summary> python setup.py develop</summary>
...

Using /net/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages
Finished processing dependencies for scitools-iris==3.4.0.dev18
Traceback (most recent call last):
  File "/net/home/h05/itwl/projects/git/iris/setup.py", line 123, in <module>
    setup(
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
    self.run_command(cmd)
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/net/home/h05/itwl/projects/git/iris/setup.py", line 96, in run
    if self.editable_mode:
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 105, in __getattr__
    raise AttributeError(attr)
AttributeError: editable_mode
</details>

<details><summary> python setup.py std_names</summary>
running std_names
Traceback (most recent call last):
  File "/net/home/h05/itwl/projects/git/iris/setup.py", line 123, in <module>
    setup(
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
    self.run_command(cmd)
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/net/home/h05/itwl/projects/git/iris/setup.py", line 96, in run
    if self.editable_mode:
  File "/home/h05/itwl/.conda/envs/iris-dev/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 105, in __getattr__
    raise AttributeError(attr)
AttributeError: editable_mode
</details>

## Expected behaviour
Expect to successfully perform an "editable" install using `develop`, and build the CF Standard Names as part of that installation, or standalone with the `std_names` custom command. 

## Environment 
 - Iris Version: `main`, `3.3.0`
</details>

**Comment by bjlittle** [comment]
BTW I don't think it's necessary for the resolution of this issue to force a patch release, as developers can work around it i.e., use `pip install --editable .` instead of `python setup.py develop`, and explicitly call `tools/generate_std_names.py`.
