### ISSUE TITLE
Arithmetic failure when duplicate scalar coord present

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#5146]
## 🐛 Bug Report

Due to having done arithmetic with cubes that have similar scalar coordinates, I ended up with both on my cube, which is fine.  However, when I tried to do subsequent arithmetic, I got an exception.

## How To Reproduce
Steps to reproduce the behaviour:

```python
import iris.cube
import iris.coords

cube = iris.cube.Cube(1)
coord1 = iris.coords.DimCoord(1, standard_name="longitude")
coord2 = iris.coords.DimCoord(1, standard_name="longitude", long_name="longitude")

cube.add_aux_coord(coord1)
cube.add_aux_coord(coord2)

cube - cube
```

```
Traceback (most recent call last):
  File "[my-path]/double_scalar_coord.py", line 11, in <module>
    cube - cube
  File "[git-path]/iris/lib/iris/common/lenient.py", line 124, in lenient_client_inner
    result = func(*args, **kwargs)
  File "[git-path]/iris/lib/iris/analysis/maths.py", line 328, in subtract
    return _add_subtract_common(
  File "[git-path]/iris/lib/iris/analysis/maths.py", line 370, in _add_subtract_common
    result = _binary_op_common(
  File "[git-path]/iris/lib/iris/analysis/maths.py", line 871, in _binary_op_common
    resolver = Resolve(cube, other)
  File "[git-path]/iris/lib/iris/common/resolve.py", line 327, in __init__
    self(lhs, rhs)
  File "[git-path]/iris/lib/iris/common/resolve.py", line 387, in __call__
    self._metadata_mapping()
  File "[git-path]/iris/lib/iris/common/resolve.py", line 1243, in _metadata_mapping
    self._as_compatible_cubes()
  File "[git-path]/iris/lib/iris/common/resolve.py", line 487, in _as_compatible_cubes
    add_coord(coord)
  File "[git-path]/iris/lib/iris/common/resolve.py", line 479, in add_coord
    new_src_cube.add_aux_coord(coord, tgt_dims)
  File "[git-path]/iris/lib/iris/cube.py", line 1162, in add_aux_coord
    raise iris.exceptions.CannotAddError(
iris.exceptions.CannotAddError: Duplicate coordinates are not permitted.
```

## Expected behaviour

No exception.

## Environment 
 - OS & Version: RHEL7
 - Iris Version: `main`

**Comment by trexfeathers** [comment]
Thanks @rcomer 🙂

I'm surprised that these two coordinates could both be added to the same `Cube`. I know they're not identical, but they are where it matters, and we can see that they then break downstream assumptions. So I'd ideally want to prevent that.

What would happen to your original case if the original `cube.add_aux_coord(coord2)` has been disallowed?

**Comment by rcomer** [comment]
Thanks @trexfeathers, I've come up with another minimal example that better illustrates how I got to this situation in the first place!

```python
import iris.cube
import iris.coords

model_coord = iris.coords.DimCoord(1, standard_name="longitude",
                                   coord_system=iris.coord_systems.GeogCS(6371229.0))
obs_coord = iris.coords.DimCoord(1, standard_name="longitude")

model_cube1 = iris.cube.Cube(1, aux_coords_and_dims=[(model_coord, None)])
model_cube2 = iris.cube.Cube(1, aux_coords_and_dims=[(model_coord, None)])

obs_cube = iris.cube.Cube(1, aux_coords_and_dims=[(obs_coord, None)])

bias_cube1 = model_cube1 - obs_cube
bias_cube2 = model_cube2 - obs_cube

for i, cube in enumerate([bias_cube1, bias_cube2]):
    # Coord system disappears if you save to NetCDF and re-load.
    for coord in cube.coords():
        coord.coord_system = None

# [apply np.abs to bias cubes]

bias_diff = bias_cube1 - bias_cube2
```

So possibly the `long_name` was a red herring, although it did exist in my original case.  The coordinates from my original case look like this:

```
DimCoord :  longitude / (degrees)
    points: [180.]
    bounds: [[  0., 360.]]
    shape: (1,)  bounds(1, 2)
    dtype: float32
    standard_name: 'longitude'
    coord_system: GeogCS(6371229.0)
DimCoord :  longitude / (degrees)
    points: [180.]
    bounds: [[  0., 360.]]
    shape: (1,)  bounds(1, 2)
    dtype: float32
    standard_name: 'longitude'
    long_name: 'longitude'
    var_name: 'longitude'
```

There are various differences, but the `coord_system` appears to be the problem.  If I remove it from the original coord, I only get one longitude coordinate on my "bias" cube.

**Comment by rcomer** [comment]
I should probably add that I started with global data and the scalar coords came out of the `collapsed` method.

**Comment by trexfeathers** [comment]
I believe @pp-mo has an explanation, do you think you could write it down?!

**Comment by trexfeathers** [comment]
_Think_ this was as follows:

* Two scalar coords, with the same `standard_name`, one with a `coord_system`
* Saved to NetCDF
* During loading, the `coord_system` either needs to be on both, or on neither. Can't cope with the mixture

**Comment by trexfeathers** [comment]
The @SciTools/peloton thinks this is too niche to try and fix 🙈
